@php
 $blocks=collect($landingBlocks??[])->values();$get=fn($type)=>(array)($blocks->firstWhere('block_type',$type)??[]);$items=fn($b)=>collect($b['dynamic_items']??[])->filter()->values()->whenEmpty(fn($x)=>$x->push(...collect(data_get($b,'data.content.items',[]))->filter()->values()->all()));$img=fn($x,$f)=>data_get($x,'image',data_get($x,'image_url',$f));$money=fn($v)=>(float)$v>0?number_format((float)$v,0,',','.').'đ':'Liên hệ';
 $hero=$get('hero_slider');$cats=$get('e804_categories');$daily=$get('e804_daily_deals');$featured=$get('e804_featured_categories');$brands=$get('e804_official_brands');$best=$get('e804_best_brands');$weekly=$get('e804_weekly_deals');$recommend=$get('e804_recommendations');$news=$get('e804_news');$slides=collect($hero['dynamic_items']??data_get($hero,'data.content.slides',[]));
@endphp
@extends('theme-e804::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','E804 Mall')))
@section('content')
<main class="e804-main">
<section id="gioi-thieu" class="e804-section xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider"><div class="e804-container e804-hero-layout"><aside class="e804-left"><div class="e804-catbox xd-landing-block" data-landing-block-id="{{ data_get($cats,'id') }}" data-block-type="e804_categories"><h2><i class="fa-solid fa-list"></i> Danh mục</h2>@foreach($items($cats)->take(11) as $i=>$item)<a href="{{ data_get($item,'url','#san-pham') }}" data-e804-mega-trigger="{{ $i }}"><span>{{ data_get($item,'title') }}</span><i class="fa-solid fa-angle-right"></i></a>@endforeach<a href="#danh-muc">Xem thêm ...</a></div><div class="e804-trends"><h2><i class="fa-solid fa-magnifying-glass"></i> Xu hướng tìm kiếm</h2>@foreach(['Khỏe đẹp','Nhà cửa','Sách','Bách hóa','Hải sản','Điện thoại','Laptop'] as $x)<a href="#san-pham">{{ $x }}</a>@endforeach</div></aside><div class="e804-hero-center"><article class="e804-hero"><img src="{{ $img($slides->first(),asset('themes/E804/images/hero-marketplace.png')) }}" alt="E804 Marketplace"><div><small>SIÊU HỘI MUA SẮM</small><h1>Hàng hay <b>giá tốt</b><br>mỗi ngày</h1><p>Khám phá hàng ngàn sản phẩm tuyển chọn cho mọi nhu cầu.</p><a href="#deals">Mua ngay <i class="fa-solid fa-arrow-right"></i></a></div></article><div class="e804-actions">@foreach([['fa-percent','Top 100 ưu đãi'],['fa-tags','Mã giảm giá'],['fa-gift','Quà tặng'],['fa-shop','Xả kho'],['fa-star','Tìm kiếm nhiều']] as [$icon,$label])<a href="#deals"><i class="fa-solid {{ $icon }}"></i><span>{{ $label }}</span></a>@endforeach</div><div class="e804-mega" data-e804-mega><button data-e804-mega-close aria-label="Đóng">×</button><div><h3>Tã, bỉm & chăm sóc bé</h3><a href="#">Tã quần</a><a href="#">Dinh dưỡng cho bé</a><a href="#">Thực phẩm ăn dặm</a></div><div><h3>Đồ dùng gia đình</h3><a href="#">Chăm sóc mẹ</a><a href="#">Đồ dùng cho bé</a><a href="#">Đồ chơi phát triển</a></div><div><h3>Ưu đãi nổi bật</h3><a href="#">Combo tiết kiệm</a><a href="#">Hàng mới về</a><a href="#">Giao nhanh hôm nay</a></div></div></div><aside class="e804-side-promos"><article><img src="{{ asset('themes/E804/images/campaign-marketplace.png') }}" alt="Khuyến mãi"><div><b>Bắt trend giá sốc</b><span>Deal mới mỗi ngày</span></div></article><article><img src="{{ asset('themes/E804/images/hero-marketplace.png') }}" alt="Freeship"><div><b>Siêu sale freeship</b><span>Nhận x4 ưu đãi</span></div></article></aside></div></section>

<section id="deals" class="e804-section xd-landing-block" data-landing-block-id="{{ data_get($daily,'id') }}" data-block-type="e804_daily_deals"><div class="e804-container e804-panel"><header class="e804-title"><h2>Giá tốt mỗi ngày</h2><a href="#san-pham">Xem tất cả <i class="fa-solid fa-arrow-right"></i></a></header><div class="e804-products">@foreach($items($daily)->take(5) as $item)@include('theme-e804::partials.product-card',['item'=>$item,'compact'=>false])@endforeach</div></div></section>

<section id="danh-muc" class="e804-section xd-landing-block" data-landing-block-id="{{ data_get($featured,'id') }}" data-block-type="e804_featured_categories"><div class="e804-container e804-panel"><header class="e804-title"><h2><i class="fa-solid fa-award"></i> Danh mục nổi bật</h2><a href="#">Xem tất cả →</a></header><div class="e804-featured">@foreach($items($featured)->take(18) as $i=>$item)<a href="{{ data_get($item,'url','#') }}"><span><i class="{{ data_get($item,'icon','fa-solid fa-cube') }}"></i></span><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></div></section>

<section class="e804-section xd-landing-block" data-landing-block-id="{{ data_get($brands,'id') }}" data-block-type="e804_official_brands"><div class="e804-container e804-panel e804-official"><header class="e804-title"><h2><i class="fa-solid fa-certificate"></i> Thương hiệu chính hãng</h2><a href="#">Xem tất cả →</a></header><div class="e804-brand-grid">@foreach($items($brands)->take(6) as $i=>$item)<article><img src="{{ $img($item,asset('themes/E804/images/campaign-marketplace.png')) }}" alt="{{ data_get($item,'title') }}"><b>{{ data_get($item,'title') }}</b></article>@endforeach</div></div></section>

<section class="e804-section"><div class="e804-container e804-split"><div class="e804-panel xd-landing-block" data-landing-block-id="{{ data_get($best,'id') }}" data-block-type="e804_best_brands"><header class="e804-title"><h2><i class="fa-solid fa-fire"></i> Thương hiệu bán chạy</h2><a href="#">Xem tất cả →</a></header><div class="e804-brand-pills">@foreach(['BLUE HOME','LUMINA','E804 TECH','PURE LAB'] as $x)<span>{{ $x }}</span>@endforeach</div><div class="e804-products e804-grid3">@foreach($items($best)->take(6) as $item)@include('theme-e804::partials.product-card',['item'=>$item,'compact'=>false])@endforeach</div></div><aside class="e804-panel xd-landing-block" data-landing-block-id="{{ data_get($weekly,'id') }}" data-block-type="e804_weekly_deals"><header class="e804-title"><h2><i class="fa-solid fa-ticket"></i> Deal hot trong tuần</h2></header><div class="e804-weekly">@foreach($items($weekly)->take(7) as $item)@include('theme-e804::partials.product-card',['item'=>$item,'compact'=>true])@endforeach</div></aside></div></section>

<section id="goi-y" class="e804-section xd-landing-block" data-landing-block-id="{{ data_get($recommend,'id') }}" data-block-type="e804_recommendations"><div class="e804-container e804-panel"><header class="e804-title"><h2><i class="fa-solid fa-grip"></i> Gợi ý hôm nay</h2></header><div class="e804-tabs" data-e804-tabs>@foreach(['Dành cho bạn','Deal seal hot','Freeship','Xu hướng','Hàng hiệu quốc tế','Hàng mới'] as $i=>$x)<button class="{{ $i===0?'is-active':'' }}">{{ $x }}</button>@endforeach</div><div class="e804-products e804-grid5">@foreach($items($recommend)->take(10) as $item)@include('theme-e804::partials.product-card',['item'=>$item,'compact'=>false])@endforeach</div><a class="e804-more" href="#san-pham">Xem thêm</a></div></section>

<section id="tin-tuc" class="e804-section xd-landing-block" data-landing-block-id="{{ data_get($news,'id') }}" data-block-type="e804_news"><div class="e804-container e804-panel"><header class="e804-title"><h2>Tin tức mới nhất</h2><a href="{{ route('site.blog.index') }}">Xem thêm Tin tức mới nhất →</a></header>@php $newsItems=$items($news); @endphp<div class="e804-news"><article class="e804-news-lead"><img src="{{ $img($newsItems->first(),asset('themes/E804/images/campaign-marketplace.png')) }}" alt="Tin mới"><h3>{{ data_get($newsItems->first(),'title','Bí quyết mua sắm thông minh mỗi ngày') }}</h3><p>{{ data_get($newsItems->first(),'summary','Cập nhật xu hướng, mẹo lựa chọn và cách tận dụng ưu đãi hiệu quả.') }}</p></article><div class="e804-news-list">@foreach($newsItems->slice(1,4) as $item)<article><img src="{{ $img($item,asset('themes/E804/images/hero-marketplace.png')) }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title') }}</h3></article>@endforeach</div><aside><h3>MẸO VẶT</h3>@foreach($newsItems->take(5) as $item)<article><img src="{{ $img($item,asset('themes/E804/images/campaign-marketplace.png')) }}" alt=""><span>{{ data_get($item,'title') }}</span></article>@endforeach</aside></div></div></section>
</main>
@endsection
