@php
    $homeUrl = route('site.home', ['locale' => app()->getLocale()]); $shell = $themeShellData ?? $themeHomeData ?? [];
    $branding = (array) data_get($shell, 'branding', data_get($siteProfile ?? [], 'branding', []));
    $company = trim((string) data_get($branding, 'company_name', 'AUTO850 Euro Auto Care')) ?: 'AUTO850 Euro Auto Care';
    $logo = trim((string) data_get($branding, 'logo_url', '')); $hotline = trim((string) data_get($branding, 'support_hotline', '1900 6750'));
    $location = trim((string) data_get($branding, 'support_location', '70 Lữ Gia, Phường 15, Quận 11, TP.HCM')); $email = trim((string) data_get($branding, 'support_email', 'support@htvietnam.vn'));
    $nav = collect(data_get($shell, 'top_menu', data_get($menus ?? [], 'primary-navigation', data_get($menus ?? [], 'primary', []))))->filter(fn ($item) => is_array($item) && filled(data_get($item, 'label')))->values();
@endphp
<header class="a850-header">
<div class="sf-language-mobile-slot">@include('partials.storefront-language-switcher')</div><div class="a850-top"><div class="a850-wrap"><span><i class="fa-solid fa-location-dot"></i>{{ $location }}</span><a href="mailto:{{ $email }}"><i class="fa-regular fa-envelope"></i>{{ $email }}</a><a href="tel:{{ preg_replace('/\D+/', '', $hotline) }}"><i class="fa-solid fa-phone"></i>{{ $hotline }}</a><div class="a850-social"><a href="#"><i class="fa-brands fa-facebook-f"></i></a><a href="#"><i class="fa-brands fa-youtube"></i></a><a href="#"><i class="fa-brands fa-instagram"></i></a>
            @include('partials.storefront-language-switcher')
        </div></div></div>
<div class="a850-main"><div class="a850-wrap"><a class="a850-logo" href="{{ $homeUrl }}">@if($logo)<img src="{{ $logo }}" alt="{{ $company }}">@else<span class="a850-logo-car"><i class="fa-solid fa-car-side"></i></span><span><b>AUTO<span>850</span></b><small>EURO AUTO CARE</small></span>@endif</a>
<button class="a850-menu" type="button" data-a850-menu aria-label="@themeT('menu.open', 'Mở menu')"><i class="fa-solid fa-bars"></i></button><nav data-a850-nav>@forelse($nav as $item)<a href="{{ data_get($item, 'url', '#') }}">{{ data_get($item, 'label') }}</a>@empty<a href="{{ $homeUrl }}">@themeT('home', 'Trang chủ')</a><a href="#gioi-thieu">@themeT('about', 'Giới thiệu')</a><a href="#san-pham">@themeT('products', 'Sản phẩm')</a><a href="#dich-vu">@themeT('services', 'Dịch vụ')</a><a href="#tin-tuc">@themeT('news', 'Tin tức')</a><a href="#faq">FAQ</a>@endforelse</nav>
<a class="a850-call" href="tel:{{ preg_replace('/\D+/', '', $hotline) }}"><i class="fa-solid fa-phone"></i><span><small>Gọi ngay</small><b>{{ $hotline }}</b></span></a>@guest('customer')<button class="a850-icon" type="button" data-xd-auth-open="login" aria-label="@themeT('auth.login', 'Đăng nhập')"><i class="fa-regular fa-user"></i></button>@else<a class="a850-icon" href="{{ route('customer.account', ['locale' => app()->getLocale()]) }}"><i class="fa-regular fa-user"></i></a>@endguest<a class="a850-icon" href="{{ route('site.cart.index', ['locale' => app()->getLocale()]) }}"><i class="fa-solid fa-cart-shopping"></i><em>{{ (int) ($cartCount ?? 0) }}</em></a><a class="a850-cta" href="#dat-lich">@themeT('book_now', 'Đặt lịch ngay') <i class="fa-solid fa-arrow-right"></i></a></div></div></header>
