<style>
:root{--xd6-red:#ff3b30;--xd6-red-deep:#b81019;--xd6-black:#09090b;--xd6-panel:#151518;--xd6-line:#2a2a2e;--xd6-white:#f7f5f2;--xd6-muted:#aaa7a3;--wide:min(1320px,calc(100% - 64px));--gold:var(--xd6-red);--ink:var(--xd6-white);--muted:var(--xd6-muted)}
html{scroll-behavior:smooth}
body{background:var(--xd6-black);color:var(--xd6-white);font-family:"Segoe UI",Arial,sans-serif}
.xd5-page{overflow:hidden;background:var(--xd6-black)}
.xd5-header{position:absolute;background:linear-gradient(180deg,rgba(9,9,11,.96),rgba(9,9,11,.55),transparent);border:0}
.xd5-utility{border-color:rgba(255,255,255,.1);color:var(--xd6-muted);letter-spacing:.06em}
.xd5-nav-wrap{min-height:106px}.xd5-nav-wrap nav{justify-content:flex-end;gap:34px;font-size:13px;letter-spacing:.12em}.xd5-nav-wrap nav a{position:relative}.xd5-nav-wrap nav a:after{position:absolute;right:0;bottom:-9px;left:0;height:2px;background:var(--xd6-red);content:"";transform:scaleX(0);transform-origin:right;transition:transform .25s}.xd5-nav-wrap nav a:hover:after{transform:scaleX(1);transform-origin:left}
.xd5-brand{font-size:0}.xd5-brand:after{content:"BLACK / DIGITAL";font-size:20px;font-weight:900;letter-spacing:.16em}.xd5-brand img{max-width:170px;max-height:62px}.xd5-brand:has(img):after{display:none}
.xd5-hotline{display:inline-flex;align-items:center;min-height:45px;padding:0 18px;border:1px solid rgba(255,255,255,.22);font-size:14px;letter-spacing:.05em}
.xd5-hero,.xd5-hero-copy{min-height:820px}.xd5-hero{background:#09090b}.xd5-hero__slide{overflow:hidden}.xd5-hero__slide:after{position:absolute;inset:0;background:linear-gradient(90deg,rgba(9,9,11,.95) 0 42%,rgba(9,9,11,.2) 76%),linear-gradient(0deg,rgba(9,9,11,.75),transparent 48%);content:""}.xd5-hero__slide img{position:absolute;inset:0;filter:saturate(.72) contrast(1.08);transform:scale(1.03);transition:transform 8s ease}.xd5-hero__slide.is-active img{transform:scale(1.11)}.xd5-veil{display:none}.xd5-hero-copy{align-items:flex-end;padding-bottom:105px}.xd5-hero-copy>div{max-width:820px;margin:0}.xd5-kicker,.xd5-eyebrow{font-size:12px;font-weight:800;letter-spacing:.24em;text-transform:uppercase}.xd5-hero h1{max-width:790px;margin:18px 0;font-size:clamp(52px,7.4vw,112px);font-weight:900;letter-spacing:-.07em;line-height:.88;text-transform:uppercase}.xd5-hero p{max-width:620px;color:#d2cfca;font-size:18px}.xd5-btn{min-height:56px;align-items:center;padding:0 28px;border:1px solid var(--xd6-red);background:var(--xd6-red);letter-spacing:.06em;text-transform:uppercase;transition:.25s}.xd5-btn:hover{background:transparent;color:var(--xd6-red)}
.xd5-section{position:relative;padding:120px 0;background:var(--xd6-black);border-top:1px solid var(--xd6-line)}.xd5-section:nth-of-type(even){background:var(--xd6-panel)}.xd5-title{max-width:900px;margin:16px 0 0;font-size:clamp(38px,5vw,72px);font-weight:850;letter-spacing:-.055em;line-height:.98}
.xd5-services{grid-template-columns:repeat(3,1fr);gap:1px;margin-top:66px;background:var(--xd6-line)}.xd5-service{position:relative;min-height:480px;padding:38px;background:var(--xd6-black);border:0;box-shadow:none;transition:background .28s,transform .28s}.xd5-service:before{display:block;margin-bottom:70px;color:var(--xd6-red);content:"0" counter(xd6-service);counter-increment:xd6-service;font-size:14px;font-weight:800;letter-spacing:.18em}.xd5-services{counter-reset:xd6-service}.xd5-service h3{font-size:27px;line-height:1.12}.xd5-service p{color:var(--xd6-muted)}.xd5-service img{height:190px;margin-top:26px;filter:grayscale(1);transition:.3s}.xd5-service:hover{z-index:2;background:var(--xd6-red);color:#fff;transform:translateY(-10px)}.xd5-service:hover:before,.xd5-service:hover p{color:#fff}.xd5-service:hover img{filter:grayscale(0)}
.xd5-about{grid-template-columns:1.08fr .92fr;gap:100px}.xd5-about-media{min-height:610px}.xd5-about-media:before{position:absolute;top:-25px;left:-25px;width:42%;height:42%;border-top:4px solid var(--xd6-red);border-left:4px solid var(--xd6-red);content:""}.xd5-about-media img{width:88%;height:570px;filter:grayscale(1)}.xd5-about-badge{right:0;bottom:0;width:42%;padding:42px 24px;background:var(--xd6-red);font-weight:700;letter-spacing:.08em;text-transform:uppercase}.xd5-about-badge b{font-size:62px;letter-spacing:-.06em}.xd5-progress{height:3px;margin-top:12px;background:#333}.xd5-progress i{background:var(--xd6-red)}
.xd6-gallery{background:#0d0d0f}.xd6-gallery__head{display:flex;align-items:end;justify-content:space-between;gap:30px}.xd6-gallery__grid{display:grid;grid-template-columns:repeat(12,1fr);gap:18px;margin-top:55px}.xd6-gallery__card{position:relative;grid-column:span 4;min-height:360px;overflow:hidden;background:#222}.xd6-gallery__card:nth-child(4n+1){grid-column:span 7}.xd6-gallery__card:nth-child(4n+2){grid-column:span 5}.xd6-gallery__card img{width:100%;height:100%;object-fit:cover;filter:grayscale(1);transition:.45s}.xd6-gallery__card span{position:absolute;right:18px;bottom:18px;left:18px;padding:18px;background:rgba(9,9,11,.86);font-size:18px;font-weight:700}.xd6-gallery__card:hover img{filter:grayscale(0);transform:scale(1.04)}
.xd6-faq__layout{display:grid;grid-template-columns:.72fr 1.28fr;gap:90px}.xd6-faq__list{border-top:1px solid var(--xd6-line)}.xd6-faq__item{border-bottom:1px solid var(--xd6-line)}.xd6-faq__question{display:flex;width:100%;justify-content:space-between;padding:28px 0;border:0;background:transparent;color:#fff;font-weight:750;text-align:left}.xd6-faq__answer{padding:0 50px 28px 0;color:var(--xd6-muted)}
.xd5-posts{grid-template-columns:1.25fr repeat(2,1fr);gap:18px}.xd5-post{background:#111;border:1px solid var(--xd6-line);box-shadow:none}.xd5-post img{height:310px;filter:grayscale(.8)}.xd5-post div{padding:30px}.xd5-post h3{font-size:22px}.xd5-post p{color:var(--xd6-muted)}
.xd5-footer{padding:80px 0 36px;background:#050506;border-top:1px solid var(--xd6-red)}.xd5-footer-top{align-items:flex-end;border-color:var(--xd6-line)}.xd5-footer-grid{grid-template-columns:1.3fr .7fr 1fr}.xd5-footer h3{letter-spacing:.12em;text-transform:uppercase}.xd5-footer input{background:#151518;color:#fff}.xd5-footer button{background:var(--xd6-red)}
[data-xd-reveal]{opacity:0;transform:translateY(48px);transition:opacity .75s cubic-bezier(.2,.7,.2,1),transform .75s cubic-bezier(.2,.7,.2,1);transition-delay:var(--reveal-delay,0ms)}[data-xd-reveal].is-visible{opacity:1;transform:none}
@media(max-width:900px){.xd5-services{grid-template-columns:1fr 1fr}.xd6-gallery__card,.xd6-gallery__card:nth-child(n){grid-column:span 6}.xd6-faq__layout{grid-template-columns:1fr}.xd5-posts{grid-template-columns:1fr 1fr}.xd5-post:first-child{grid-column:1/-1}}
@media(max-width:620px){:root{--wide:min(100% - 32px,1320px)}.xd5-header{position:relative;background:#09090b}.xd5-nav-wrap{min-height:76px;flex-wrap:wrap}.xd5-brand:after{font-size:16px}.xd5-hero,.xd5-hero-copy{min-height:650px}.xd5-hero-copy{padding-bottom:70px}.xd5-hero h1{font-size:50px}.xd5-section{padding:78px 0}.xd5-services,.xd5-posts{grid-template-columns:1fr}.xd5-post:first-child{grid-column:auto}.xd5-service{min-height:400px}.xd5-about{gap:55px}.xd5-about-media{min-height:440px}.xd5-about-media img{width:100%;height:420px}.xd6-gallery__card,.xd6-gallery__card:nth-child(n){grid-column:1/-1;min-height:290px}.xd5-footer-top{align-items:start}.xd5-footer-grid{gap:38px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}[data-xd-reveal]{opacity:1;transform:none;transition:none}.xd5-hero__slide img{transition:none}}
</style>
