@php
  $blocks=collect($landingBlocks??[])->values();$get=fn(string $type)=>(array)($blocks->firstWhere('block_type',$type)??[]);$items=fn(array $block)=>collect($block['dynamic_items']??[])->filter()->values()->whenEmpty(fn($list)=>$list->push(...collect(data_get($block,'data.content.items',[]))->filter()->values()->all()));
  $hero=$get('hero_tools');$categories=$get('e807_categories');$deals=$get('e807_deals');$new=$get('e807_new');$promo=$get('e807_promo_trio');$best=$get('e807_best');$duo=$get('e807_promo_duo');$about=$get('e807_about');$news=$get('e807_news');$testimonials=$get('e807_testimonials');$knowledge=$get('e807_knowledge');$brands=$get('e807_brands');$policies=$get('e807_policies');$heroImage=data_get($hero,'media.image_url',asset('themes/E807/images/hero-tools.png'));$collection=asset('themes/E807/images/tool-collection.png');
@endphp
@extends('theme-e807::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','E807 Pro Tools')))
@section('content')
<main class="e807-main">
<section class="e807-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_tools" style="background-image:url('{{ $heroImage }}')"><div class="e807-container"><div class="e807-hero-copy"><small>{{ data_get($hero,'data.subtitle','GIẢI PHÁP DỤNG CỤ CHUYÊN NGHIỆP') }}</small><h1>{{ data_get($hero,'data.title','Sức mạnh cho mọi công trình') }}</h1><p>{{ data_get($hero,'data.description','Dụng cụ bền bỉ · hiệu suất vượt trội · hỗ trợ tận tâm') }}</p><a href="#san-pham">{{ data_get($hero,'data.button_label','Khám phá ngay') }}</a></div></div></section>
<section id="danh-muc" class="e807-section xd-landing-block" data-landing-block-id="{{ data_get($categories,'id') }}" data-block-type="e807_categories"><div class="e807-container">@include('theme-e807::partials.heading',['title'=>'Danh mục','accent'=>'nổi bật'])<div class="e807-categories">@foreach($items($categories)->take(12) as $i=>$item)<a href="{{ data_get($item,'url','#san-pham') }}"><span><i class="{{ data_get($item,'icon',['fa-solid fa-screwdriver-wrench','fa-solid fa-screwdriver','fa-solid fa-wind','fa-solid fa-gear'][$i%4]) }}"></i></span><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></div></section>
<section id="deal" class="e807-deals xd-landing-block" data-landing-block-id="{{ data_get($deals,'id') }}" data-block-type="e807_deals" style="background-image:linear-gradient(90deg,rgba(8,8,8,.96),rgba(8,8,8,.72)),url('{{ $collection }}')"><div class="e807-container">@include('theme-e807::partials.heading',['title'=>'Deal','accent'=>'cực hấp dẫn','light'=>true])<p class="e807-deal-note">Thời gian chỉ còn · Ưu đãi được cập nhật liên tục</p><div class="e807-products">@foreach($items($deals)->take(5) as $item)@include('theme-e807::partials.product-card',['item'=>$item])@endforeach</div></div></section>
<section id="san-pham" class="e807-section xd-landing-block" data-landing-block-id="{{ data_get($new,'id') }}" data-block-type="e807_new"><div class="e807-container">@include('theme-e807::partials.heading',['title'=>'Sản phẩm','accent'=>'mới'])<div class="e807-products">@foreach($items($new)->take(5) as $item)@include('theme-e807::partials.product-card',['item'=>$item])@endforeach</div></div></section>
<section class="e807-section e807-soft xd-landing-block" data-landing-block-id="{{ data_get($promo,'id') }}" data-block-type="e807_promo_trio"><div class="e807-container e807-promo-grid">@foreach($items($promo)->take(3) as $item)<article style="background-image:linear-gradient(90deg,rgba(0,0,0,.78),rgba(0,0,0,.1)),url('{{ data_get($item,'image',$collection) }}')"><small>{{ data_get($item,'price_label','Từ 1.120.000đ') }}</small><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p><a href="{{ data_get($item,'url','#san-pham') }}">Xem ngay</a></article>@endforeach</div></section>
<section class="e807-section xd-landing-block" data-landing-block-id="{{ data_get($best,'id') }}" data-block-type="e807_best"><div class="e807-container">@include('theme-e807::partials.heading',['title'=>'Sản phẩm','accent'=>'bán chạy'])<div class="e807-products e807-grid5">@foreach($items($best)->take(10) as $item)@include('theme-e807::partials.product-card',['item'=>$item])@endforeach</div></div></section>
<section class="e807-section xd-landing-block" data-landing-block-id="{{ data_get($duo,'id') }}" data-block-type="e807_promo_duo"><div class="e807-container e807-duo">@foreach($items($duo)->take(2) as $item)<article style="background-image:linear-gradient(90deg,rgba(0,0,0,.82),rgba(0,0,0,.12)),url('{{ data_get($item,'image',$collection) }}')"><small>{{ data_get($item,'price_label') }}</small><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p><a href="#san-pham">Xem ngay</a></article>@endforeach</div></section>
<section id="gioi-thieu" class="e807-section xd-landing-block" data-landing-block-id="{{ data_get($about,'id') }}" data-block-type="e807_about"><div class="e807-container e807-about"><div class="e807-about-image" style="background-image:url('{{ $collection }}')"></div><div>@include('theme-e807::partials.heading',['title'=>'Giải pháp','accent'=>'toàn diện'])<p>{{ data_get($about,'data.description','Chúng tôi mang đến hệ sinh thái dụng cụ cơ khí đáng tin cậy cho nhà thầu, kỹ sư và người yêu thích DIY.') }}</p>@foreach(['Sản phẩm chất lượng cao','Đội ngũ giàu kinh nghiệm','Luôn đồng hành và hỗ trợ','Nhiều ưu đãi thiết thực'] as $line)<span><i class="fa-solid fa-circle-check"></i>{{ $line }}</span>@endforeach</div></div></section>
<section class="e807-section e807-soft xd-landing-block" data-landing-block-id="{{ data_get($news,'id') }}" data-block-type="e807_news"><div class="e807-container">@include('theme-e807::partials.heading',['title'=>'Tin tức','accent'=>'mới nhất'])<div class="e807-news">@foreach($items($news)->take(4) as $item)<article><img src="{{ data_get($item,'image',$collection) }}" alt="{{ data_get($item,'title') }}"><div><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p><a href="{{ data_get($item,'url','#') }}">Đọc tiếp →</a></div></article>@endforeach</div></div></section>
<section class="e807-testimonials xd-landing-block" data-landing-block-id="{{ data_get($testimonials,'id') }}" data-block-type="e807_testimonials" style="background-image:linear-gradient(90deg,rgba(0,0,0,.94),rgba(0,0,0,.72)),url('{{ $collection }}')"><div class="e807-container">@include('theme-e807::partials.heading',['title'=>'Feedback','accent'=>'từ khách hàng','light'=>true])<div>@foreach($items($testimonials)->take(3) as $item)<article><h3>{{ data_get($item,'title') }}</h3><small>{{ data_get($item,'role','Khách hàng') }}</small><p>{{ data_get($item,'summary') }}</p></article>@endforeach</div></div></section>
<section class="e807-section xd-landing-block" data-landing-block-id="{{ data_get($knowledge,'id') }}" data-block-type="e807_knowledge"><div class="e807-container">@include('theme-e807::partials.heading',['title'=>'Chia sẻ','accent'=>'kiến thức'])<div class="e807-knowledge">@foreach($items($knowledge)->take(3) as $item)<article><img src="{{ data_get($item,'image',$collection) }}" alt="{{ data_get($item,'title') }}"><time>23<br><small>T08</small></time><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></article>@endforeach</div></div></section>
<section class="e807-section e807-soft xd-landing-block" data-landing-block-id="{{ data_get($brands,'id') }}" data-block-type="e807_brands"><div class="e807-container">@include('theme-e807::partials.heading',['title'=>'Thương hiệu','accent'=>'nổi bật'])<div class="e807-brands">@foreach($items($brands)->take(6) as $item)<span>{{ data_get($item,'title') }}</span>@endforeach</div></div></section>
<section class="e807-policy xd-landing-block" data-landing-block-id="{{ data_get($policies,'id') }}" data-block-type="e807_policies"><div class="e807-container"><b>CHÍNH SÁCH:</b>@foreach($items($policies)->take(4) as $item)<span><i class="{{ data_get($item,'icon','fa-solid fa-truck-fast') }}"></i><strong>{{ data_get($item,'title') }}</strong><small>{{ data_get($item,'summary') }}</small></span>@endforeach</div></section>
</main>
@endsection

