<style>
    :root { --xd9-blue: #075aa8; --xd9-orange: #f26522; --xd9-ink: #20252c; }
    .xd5-page { font-family: "Segoe UI", Roboto, Arial, Helvetica, sans-serif; color: var(--xd9-ink); }
    .xd5-header, .xd5-benefits, .xd5-contact, .xd5-footer { background: var(--xd9-blue); }
    .xd5-brand span, .xd5-kicker, .xd5-eyebrow, .xd5-footer-top small { color: var(--xd9-orange); }
    .xd5-btn, .xd5-contact button { background: var(--xd9-orange); border-radius: 0; color: #fff; }
    .xd5-service { border-top-color: var(--xd9-blue); }
    .xd5-progress i { background: var(--xd9-orange); }
    .xd5-partner{min-width:0}.xd5-partner img{max-width:min(180px,100%)}
    .xd5-hero::after { background: linear-gradient(90deg, rgba(7, 90, 168, .92), rgba(7, 90, 168, .25)); }
    #top>.xd5-header{background:#fff;color:#07335b}.xd5-header .xd5-utility{background:#07335b;color:#fff;border-bottom:0}.xd5-header .xd5-nav-wrap{background:#fff}.xd5-nav-wrap nav a:hover{color:var(--xd9-orange)}.xd5-header .xd5-nav-wrap>button{color:#07335b;border-color:#07335b55}.xd5-hotline{color:var(--xd9-blue)}
    .xd5-contact{position:relative;isolation:isolate;overflow:hidden}.xd9-contact-background{position:absolute;inset:0;z-index:-2;width:100%;height:100%;object-fit:cover}.xd5-contact:before{content:"";position:absolute;inset:0;z-index:-1;background:linear-gradient(100deg,rgba(4,40,74,.94),rgba(7,90,168,.72))}.xd5-contact-grid{gap:60px}.xd5-contact p{color:#edf5ff}.xd5-contact .xd5-eyebrow{color:#ffc47d}
    .xd9-news-slider .xd5-posts{display:flex;gap:24px;overflow-x:auto;scroll-snap-type:x mandatory;overscroll-behavior-x:contain;scrollbar-width:thin;scrollbar-color:#8bb7dc transparent;padding:6px 0 20px}.xd9-news-slider .xd5-post{display:flex;flex:0 0 calc((100% - 48px)/3);flex-direction:column;min-width:0;scroll-snap-align:start;border:1px solid #e4eaf0;border-radius:12px;overflow:hidden;box-shadow:none}.xd9-news-slider .xd5-post>img{display:block;aspect-ratio:16/10;height:auto;flex-shrink:0}.xd9-news-slider .xd5-post>div{display:flex;flex:1;flex-direction:column;padding:24px}.xd9-news-slider .xd5-post h3{font-size:20px;line-height:1.4}.xd9-news-slider .xd5-post p{color:#687078}.xd9-news-slider .xd5-btn{align-self:flex-start;margin-top:auto}.xd9-news-controls{display:flex;justify-content:flex-end;gap:10px;margin-top:16px}.xd9-news-controls button{display:grid;place-items:center;width:44px;height:44px;border:1px solid #bfd0e0;border-radius:50%;background:#fff;color:var(--xd9-blue);font-size:22px;cursor:pointer}.xd9-news-controls button:disabled{opacity:.35;cursor:default}.xd9-news-controls button:hover:not(:disabled){background:var(--xd9-blue);color:#fff}.xd9-news-controls button:focus-visible,.xd9-news-slider .xd5-posts:focus-visible{outline:3px solid var(--xd9-orange);outline-offset:3px}@media(max-width:900px){.xd9-news-slider .xd5-post{flex-basis:calc((100% - 24px)/2)}}@media(max-width:600px){.xd9-news-slider .xd5-posts{gap:16px}.xd9-news-slider .xd5-post{flex-basis:88%}.xd5-contact-grid{gap:32px}.xd5-contact-card{padding:24px}.xd5-contact:before{background:rgba(4,40,74,.86)}}
#top.xd9-inner-page>.xd5-header{position:relative;top:auto;left:auto}
</style>
