@php
  $shell=$themeShellData??$themeHomeData??[];$branding=(array)data_get($shell,'branding',data_get($siteProfile??[],'branding',[]));
  $t=fn(string $key):string=>app(\App\Core\Themes\ThemeTranslationService::class)->bladeText('E803',app()->getLocale(),$key);
  $name=trim((string)($branding['company_name']??data_get($siteProfile??[],'site_name','')))?:$t('E803.brand.default');$logo=trim((string)($branding['logo_url']??''));
  $nav=collect(data_get($shell,'top_menu',data_get($menus??[],'primary-navigation',[])))->filter(fn($item)=>is_array($item)&&filled($item['label']??null))->values();
  if($nav->isEmpty())$nav=collect([['label'=>$t('E803.nav.home'),'url'=>route('site.home')],['label'=>$t('E803.nav.about'),'url'=>'#gioi-thieu'],['label'=>$t('E803.nav.builder'),'url'=>'#build-pc'],['label'=>$t('E803.nav.deals'),'url'=>'#deals'],['label'=>$t('E803.nav.products'),'url'=>'#san-pham'],['label'=>$t('E803.nav.stores'),'url'=>'#footer'],['label'=>$t('E803.nav.news'),'url'=>'#tin-tuc'],['label'=>$t('E803.nav.contact'),'url'=>route('site.contact')]]);
@endphp
<header class="e803-header">
  <div class="e803-head e803-container"><a class="e803-logo" href="{{ route('site.home') }}">@if($logo)<img src="{{ $logo }}" alt="{{ $name }}">@else<span>E803</span><b>PC</b>@endif</a><form class="e803-search" action="{{ route('site.catalog.search') }}"><input name="q" placeholder="{{ $t('E803.search') }}"><button aria-label="{{ $t('E803.search') }}"><i class="fa-solid fa-magnifying-glass"></i></button></form><div class="e803-quick"><a href="#build-pc"><i class="fa-solid fa-microchip"></i><span>Xây dựng<br>cấu hình</span></a><a href="tel:{{ data_get($branding,'support_hotline','19006750') }}"><i class="fa-solid fa-headset"></i><span>Hotline<br>{{ data_get($branding,'support_hotline','1900 6750') }}</span></a><a href="#footer"><i class="fa-solid fa-store"></i><span>Hệ thống<br>showroom</span></a><a href="#san-pham" aria-label="Yêu thích"><i class="fa-regular fa-heart"></i><em>0</em></a><a href="{{ route('site.cart.index') }}"><i class="fa-solid fa-cart-shopping"></i><span>{{ $t('E803.cart') }}</span><em>{{ (int)data_get($shell,'cart_count',0) }}</em></a></div><button class="e803-toggle" data-e803-toggle aria-label="Menu"><i class="fa-solid fa-bars"></i></button></div>
  <div class="e803-nav"><nav class="e803-container" data-e803-nav>@foreach($nav as $item)<a href="{{ $item['url']??'#' }}">{{ $item['label'] }}</a>@endforeach<div class="e803-auth">@guest('customer')<button data-xd-auth-open="login">{{ $t('E803.auth.login') }}</button><button data-xd-auth-open="register">{{ $t('E803.auth.register') }}</button>@else<a href="{{ route('customer.account') }}">Tài khoản</a>@endguest</div></nav></div>
</header>
@include('partials.storefront-language-switcher')
