@php
$shell=$themeShellData??$themeHomeData??[];$branding=(array)data_get($shell,'branding',data_get($siteProfile??[],'branding',[]));
$t=fn(string $key):string=>app(\App\Core\Themes\ThemeTranslationService::class)->bladeText('SHOP603',app()->getLocale(),$key);
$phone=$branding['support_hotline']??'1900 6750';$address=$branding['support_location']??'Tầng 6, Tòa nhà Ladeco, 266 Đội Cấn, Phường Liễu Giai, Quận Ba Đình, TP Hà Nội';
$links=[['label'=>$t('SHOP603.nav.home'),'url'=>route('site.home')],['label'=>$t('SHOP603.nav.men'),'url'=>route('site.catalog.search',['q'=>'nam'])],['label'=>$t('SHOP603.nav.products'),'url'=>'#san-pham-hot'],['label'=>$t('SHOP603.nav.boys'),'url'=>route('site.catalog.search',['q'=>'bé trai'])],['label'=>$t('SHOP603.nav.girls'),'url'=>route('site.catalog.search',['q'=>'bé gái'])],['label'=>$t('SHOP603.nav.news'),'url'=>route('site.blog.index')],['label'=>$t('SHOP603.nav.contact'),'url'=>route('site.contact')]];
@endphp
<footer class="s603-footer"><div class="s603-container s603-footer-grid">
    <section class="s603-footer-brand"><a class="s603-logo" href="{{ route('site.home') }}"><span>A</span><b>lena</b></a><h3>{{ $t('SHOP603.footer.tagline') }}</h3><p><i class="fa-solid fa-location-dot"></i><span>{{ $address }}</span></p><p><i class="fa-regular fa-clock"></i><span>{{ $t('SHOP603.footer.hours') }}</span></p><p><i class="fa-solid fa-phone"></i><span>{{ $t('SHOP603.hotline') }}<strong>{{ $phone }}</strong></span></p></section>
    @foreach([['title'=>$t('SHOP603.footer.about'),'links'=>$links],['title'=>$t('SHOP603.footer.support'),'links'=>$links],['title'=>$t('SHOP603.footer.services'),'links'=>$links]] as $column)<section><h2>{{ $column['title'] }}</h2>@foreach($column['links'] as $link)<a href="{{ $link['url'] }}">{{ $link['label'] }}</a>@endforeach @if($loop->last)<div class="s603-social"><a href="#"><i class="fa-brands fa-youtube"></i></a><a href="#"><i class="fa-brands fa-instagram"></i></a><a href="#"><i class="fa-brands fa-facebook-f"></i></a></div>@endif</section>@endforeach
</div></footer>
