@php
$blocks=collect($landingBlocks??[])->filter(fn($block)=>(bool)data_get($block,'is_visible',true))->values();$byAnchor=fn(string $anchor):array=>(array)($blocks->first(fn($block)=>data_get($block,'anchor_id')===$anchor)??[]);$items=function(array $block){$dynamic=collect(data_get($block,'dynamic_items',[]))->filter()->values();return $dynamic->isNotEmpty()?$dynamic:collect(data_get($block,'data.content.items',[]))->filter()->values();};$hero=$byAnchor('top');$categories=$byAnchor('danh-muc');$promotions=$byAnchor('khuyen-mai');$promoDuo=$byAnchor('banner-uu-dai');$favorites=$byAnchor('yeu-thich');$posts=$byAnchor('bai-viet');$partners=$byAnchor('doi-tac');$slides=collect(data_get($hero,'dynamic_items',[]))->filter()->values();if($slides->isEmpty())$slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values();$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null);$blockUpdateUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.update',['block'=>'__BLOCK_ID__']):'';$blockSourcePreviewUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.source-preview',['block'=>'__BLOCK_ID__']):'';$blockPayload=$canEditLanding?$blocks->filter(fn($block)=>filled(data_get($block,'id')))->keyBy('id')->toArray():[];
@endphp
@extends('theme-foot406::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','FOOT406')))
@section('content')
<main class="f406-main"><section class="f406-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider">@include('theme-foot406::partials.edit-button',['block'=>$hero])<div class="f406-slider" data-f406-slider>@forelse($slides as $index=>$slide)<article class="f406-slide {{ $index===0?'is-active':'' }}" data-f406-slide style="--hero-image:url('{{ data_get($slide,'image','/theme-demo/ec903/deal-tea.webp') }}')"><div class="f406-slide__copy" data-f406-reveal><small>{{ data_get($slide,'kicker',data_get($hero,'data.subtitle')) }}</small><h1>{{ data_get($slide,'title',data_get($hero,'data.title')) }}</h1><p>{{ data_get($slide,'summary',data_get($hero,'data.description')) }}</p><a href="{{ data_get($slide,'link_url','#khuyen-mai') }}">{{ data_get($slide,'button_label',data_get($hero,'data.button_label','Khám phá thực đơn')) }}</a></div></article>@empty<article class="f406-slide is-active" data-f406-slide style="--hero-image:url('/theme-demo/ec903/deal-tea.webp')"><div class="f406-slide__copy"><h1>{{ data_get($hero,'data.title','Hương vị tươi mát mỗi ngày') }}</h1></div></article>@endforelse
@if($slides->count()>1)<button data-f406-prev type="button"><i class="fa-solid fa-chevron-left"></i></button><button data-f406-next type="button"><i class="fa-solid fa-chevron-right"></i></button>@endif</div></section>

<section class="f406-section xd-landing-block" id="danh-muc" data-landing-block-id="{{ data_get($categories,'id') }}" data-block-type="foot406_categories">@include('theme-foot406::partials.edit-button',['block'=>$categories])<div class="f406-container"><header class="f406-heading" data-f406-reveal><h2>{{ data_get($categories,'data.title','Chào mừng bạn đến với cửa hàng') }}</h2><p>{{ data_get($categories,'data.description') }}</p></header><div class="f406-categories">@forelse($items($categories) as $item)<a href="{{ data_get($item,'url','#') }}" data-f406-reveal><span><img src="{{ data_get($item,'image','/theme-demo/ec903/deal-tea.webp') }}" alt="{{ data_get($item,'title') }}"></span><strong>{{ data_get($item,'title') }}</strong></a>@empty<p>Danh mục đang được cập nhật.</p>@endforelse</div></div></section>

<section class="f406-section xd-landing-block" id="khuyen-mai" data-landing-block-id="{{ data_get($promotions,'id') }}" data-block-type="foot406_promo_products">@include('theme-foot406::partials.edit-button',['block'=>$promotions])<div class="f406-container"><header class="f406-heading" data-f406-reveal><i class="fa-solid fa-martini-glass-citrus"></i><h2>{{ data_get($promotions,'data.title','Đồ uống khuyến mãi') }}</h2></header><div class="f406-products f406-products--five">@foreach($items($promotions) as $item)@include('theme-foot406::partials.product-card',['item'=>$item])@endforeach</div></div></section>

<section class="f406-section f406-section--compact xd-landing-block" id="banner-uu-dai" data-landing-block-id="{{ data_get($promoDuo,'id') }}" data-block-type="foot406_promo_duo">@include('theme-foot406::partials.edit-button',['block'=>$promoDuo])<div class="f406-container f406-promo-duo">@foreach($items($promoDuo) as $item)<a href="{{ data_get($item,'url','#') }}" data-f406-reveal><img src="{{ data_get($item,'image') }}" alt="{{ data_get($item,'title') }}"><span><strong>{{ data_get($item,'title') }}</strong><small>{{ data_get($item,'summary') }}</small></span></a>@endforeach</div></section>

<section class="f406-section xd-landing-block" id="yeu-thich" data-landing-block-id="{{ data_get($favorites,'id') }}" data-block-type="foot406_favorites">@include('theme-foot406::partials.edit-button',['block'=>$favorites])<div class="f406-container"><header class="f406-heading" data-f406-reveal><i class="fa-solid fa-martini-glass-citrus"></i><h2>{{ data_get($favorites,'data.title','Đồ uống yêu thích') }}</h2></header><div class="f406-products f406-products--five">@foreach($items($favorites) as $item)@include('theme-foot406::partials.product-card',['item'=>$item])@endforeach</div></div></section>

<section class="f406-section f406-post-section xd-landing-block" id="bai-viet" data-landing-block-id="{{ data_get($posts,'id') }}" data-block-type="foot406_latest_posts">@include('theme-foot406::partials.edit-button',['block'=>$posts])<div class="f406-container"><header class="f406-heading" data-f406-reveal><h2>{{ data_get($posts,'data.title','Các bài viết mới nhất') }}</h2></header><div class="f406-posts">@foreach($items($posts) as $item)<article data-f406-reveal><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','/theme-demo/ec903/food-brunch.webp') }}" alt="{{ data_get($item,'title') }}"></a><div><h3><a href="{{ data_get($item,'url','#') }}">{{ data_get($item,'title') }}</a></h3><small><i class="fa-regular fa-calendar"></i> {{ data_get($item,'published_at',data_get($item,'date')) }}</small><p>{{ data_get($item,'summary',data_get($item,'excerpt')) }}</p></div></article>@endforeach</div></div></section>

<section class="f406-section f406-section--compact xd-landing-block" id="doi-tac" data-landing-block-id="{{ data_get($partners,'id') }}" data-block-type="foot406_partners">@include('theme-foot406::partials.edit-button',['block'=>$partners])<div class="f406-container f406-partners">@foreach($items($partners) as $item)<a href="{{ data_get($item,'url','#') }}" data-f406-reveal><img src="{{ data_get($item,'image') }}" alt="{{ data_get($item,'title') }}"></a>@endforeach</div></section></main>
@endsection
