@php
    $shell = $themeShellData ?? $themeHomeData ?? [];
    $branding = (array) data_get($shell, 'branding', data_get($siteProfile ?? [], 'branding', []));
    $name = trim((string) ($branding['company_name'] ?? data_get($siteProfile ?? [], 'site_name', 'BEAN Style'))) ?: 'BEAN Style';
    $phone = trim((string) ($branding['support_hotline'] ?? '1800 6750'));
    $email = trim((string) ($branding['support_email'] ?? 'support@htvietnam.vn'));
    $address = trim((string) ($branding['support_location'] ?? '70 Lữ Gia, Phường 15, Quận 11, TP.HCM'));
    $t = fn (string $key): string => app(\App\Core\Themes\ThemeTranslationService::class)->bladeText('SHOP601', app()->getLocale(), $key);
@endphp
<footer id="footer" class="s601-footer"><div class="s601-container s601-footer__grid">
    <section class="s601-footer-brand"><div class="s601-logo"><span>BEAN</span> Style</div><p>{{ $t('SHOP601.footer.description') }}</p><p><b>Địa chỉ:</b> {{ $address }}<br><b>Điện thoại:</b> {{ $phone }}<br><b>Email:</b> {{ $email }}</p><div class="s601-social"><i class="fa-brands fa-facebook-f"></i><i class="fa-brands fa-instagram"></i><i class="fa-brands fa-tiktok"></i><i class="fa-brands fa-youtube"></i></div><h3>{{ $t('SHOP601.footer.payment') }}</h3><div class="s601-pay"><span>momo</span><span>ZaloPay</span><span>VNPAY</span><span>VISA</span></div></section>
    <section class="s601-footer-main"><form class="s601-newsletter" method="POST" action="{{ route('site.newsletter.subscribe', \App\Support\FrontendLocalization::routeParameterDefaults()) }}">@csrf<div><h3>{{ $t('SHOP601.footer.newsletter_title') }}</h3><p>{{ $t('SHOP601.footer.newsletter_text') }}</p></div><label><input type="email" name="email" required placeholder="{{ $t('SHOP601.footer.newsletter_placeholder') }}"><button>{{ $t('SHOP601.footer.newsletter_button') }}</button></label></form><div class="s601-footer-links"><nav><h3>{{ $t('SHOP601.footer.info') }}</h3><a href="{{ route('site.home') }}">Trang chủ</a><a href="{{ route('site.catalog.search') }}">Sản phẩm</a><a href="{{ route('site.blog.index') }}">Tin tức</a><a href="{{ route('site.contact') }}">Liên hệ</a></nav><nav><h3>{{ $t('SHOP601.footer.policy') }}</h3><a href="#footer">Chính sách thành viên</a><a href="#footer">Chính sách thanh toán</a><a href="#footer">Chính sách đổi sản phẩm</a><a href="#footer">Chính sách bảo mật</a></nav><nav><h3>{{ $t('SHOP601.footer.guide') }}</h3><a href="#footer">Hướng dẫn mua hàng</a><a href="#footer">Hướng dẫn đổi trả</a><a href="#footer">Hướng dẫn thanh toán</a><a href="{{ route('site.contact') }}">Liên hệ</a></nav><nav><h3>{{ $t('SHOP601.footer.support') }}</h3><p>Mua hàng trực tuyến</p><b>{{ $phone }} (24/7)</b><p>{{ $email }}</p><div class="s601-qr">▦</div></nav></div><small>{{ $t('SHOP601.footer.rights') }}</small></section>
</div></footer>
