@extends('theme-shop605::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','OH!Under')))
@section('content')
@php
$blocks=collect($landingBlocks??[])->values();$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null);$editorLocales=collect(\App\Support\FrontendLocalization::supportedLocales())->map(fn($locale)=>['code'=>$locale,'label'=>strtoupper($locale)])->all();$get=fn(string $t):array=>(array)($blocks->firstWhere('block_type',$t)??[]);$items=fn(array $b)=>collect($b['dynamic_items']??[])->filter()->values()->whenEmpty(fn($l)=>$l->push(...collect(data_get($b,'data.content.items',[]))->filter()->values()->all()));$img=fn($x,$f)=>data_get($x,'image',data_get($x,'image_url',$f));
$hero=$get('hero_slider');$benefits=$get('shop605_benefits');$sale=$get('shop605_sale');$new=$get('shop605_new');$best=$get('shop605_best');$editorial=$get('shop605_editorial');$collections=$get('shop605_collections');$story=$get('shop605_story');$news=$get('latest_posts');$footerCta=$get('shop605_footer');
$fallback=collect([['title'=>'Áo ngực su không gọng','price'=>359000,'original_price'=>429000,'image'=>'/theme-demo/shop605/product-women-knit.png','url'=>'#'],['title'=>'Đồ mặc nhà cotton','price'=>399000,'original_price'=>429000,'image'=>'/theme-demo/shop605/product-women-rose.png','url'=>'#'],['title'=>'Bộ mặc nhà lụa','price'=>559000,'image'=>'/theme-demo/shop605/product-men-green.png','url'=>'#'],['title'=>'Áo ngực ren không gọng','price'=>329000,'image'=>'/theme-demo/shop605/ad-lac-quan.png','url'=>'#']]);$shopItems=fn(array $b)=>$items($b)->filter(fn($item)=>!filled(data_get($item,'url'))||str_contains((string)data_get($item,'url'),'shop605-'))->values();$products=fn(array $b)=>$shopItems($b)->whenEmpty(fn($l)=>$l->push(...$fallback->all()));$heroItems=collect(data_get($hero,'dynamic_items',[]))->concat($fallback)->unique(fn($item)=>$img($item,'/theme-demo/shop605/hero-fashion.png'))->take(3);
@endphp
<main class="s605-main">
<section class="s605-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider">@include('theme-shop605::partials.edit-button',['block'=>$hero])<div class="s605-hero-grid">@foreach($heroItems as $item)<img src="{{ $img($item,'/theme-demo/shop605/hero-fashion.png') }}" alt="{{ data_get($item,'title','OH!Under') }}">@endforeach</div><div class="s605-dots">• ⦿</div></section>
<section class="s605-benefits xd-landing-block" data-landing-block-id="{{ data_get($benefits,'id') }}" data-block-type="shop605_benefits">@include('theme-shop605::partials.edit-button',['block'=>$benefits])<div class="s605-wrap">@foreach($items($benefits) as $item)<article><i class="{{ data_get($item,'icon','fa-solid fa-truck') }}"></i><b>{{ data_get($item,'title') }}</b></article>@endforeach</div></section>
<section class="s605-sale xd-landing-block" data-landing-block-id="{{ data_get($sale,'id') }}" data-block-type="shop605_sale">@include('theme-shop605::partials.edit-button',['block'=>$sale])<div class="s605-wrap"><header><h2>{{ data_get($sale,'data.title','END OF SEASON SALE - MUA 1 TẶNG 1') }}</h2><div class="s605-countdown"><b>159</b>:<b>02</b>:<b>14</b>:<b>00</b></div><a href="#">Xem Tất Cả →</a></header><div class="s605-product-grid s605-four">@foreach($products($sale)->take(4) as $item)@include('theme-shop605::partials.product-card',['item'=>$item])@endforeach</div></div></section>
<section class="s605-new xd-landing-block" data-landing-block-id="{{ data_get($new,'id') }}" data-block-type="shop605_new">@include('theme-shop605::partials.edit-button',['block'=>$new])<div class="s605-wrap s605-new-grid"><aside><h2><em>Sản phẩm</em> mới 〰</h2><button>Đồ mặc nhà →</button><button>Đồ lót →</button><button>Đồ ngủ →</button><a href="#">Xem tất cả →</a></aside><div class="s605-product-grid s605-three">@foreach($products($new)->take(3) as $item)@include('theme-shop605::partials.product-card',['item'=>$item,'overlay'=>true])@endforeach</div></div></section>
<section class="s605-best xd-landing-block" data-landing-block-id="{{ data_get($best,'id') }}" data-block-type="shop605_best">@include('theme-shop605::partials.edit-button',['block'=>$best])<div class="s605-wrap"><h2>〰 <span>Sản phẩm</span> bán chạy 〰</h2><div class="s605-product-grid s605-five">@foreach($products($best)->take(10) as $item)@include('theme-shop605::partials.product-card',['item'=>$item,'overlay'=>true])@endforeach</div></div></section>
<section class="s605-editorial xd-landing-block" data-landing-block-id="{{ data_get($editorial,'id') }}" data-block-type="shop605_editorial">@include('theme-shop605::partials.edit-button',['block'=>$editorial])<img src="{{ data_get($editorial,'media.image','/theme-demo/shop605/hero-fashion.png') }}" alt="Mùa yêu dấu"><div><h2><em>BST</em> {{ data_get($editorial,'data.title','Mùa yêu dấu') }} 〰</h2><p>{{ data_get($editorial,'data.description','Hãy thả mình vào tiết trời xuân hè với những mẫu sản phẩm không thể xinh yêu hơn tại OH!Under.') }}</p><a href="#">Khám phá BST →</a></div></section>
<section class="s605-collections xd-landing-block" data-landing-block-id="{{ data_get($collections,'id') }}" data-block-type="shop605_collections">@include('theme-shop605::partials.edit-button',['block'=>$collections])<div class="s605-wrap"><h2>〰 <em>OH!Under</em> Collection 〰</h2><div class="s605-mosaic">@foreach($items($collections)->whenEmpty(fn($l)=>$l->push(...$fallback->all()))->take(6) as $item)<article><img src="{{ $img($item,'/theme-demo/shop605/product-women-rose.png') }}" alt="{{ data_get($item,'title') }}"><div><b>{{ data_get($item,'title','BST Mùa yêu dấu') }}</b><a href="#">Xem Bộ Sưu Tập</a></div></article>@endforeach</div></div></section>
<section class="s605-story xd-landing-block" data-landing-block-id="{{ data_get($story,'id') }}" data-block-type="shop605_story">@include('theme-shop605::partials.edit-button',['block'=>$story])<img src="/theme-demo/shop605/product-women-rose.png" alt="Khách hàng"><div><h2>〰 <em>Khách hàng</em> cảm nhận gì về OH! Under 〰</h2><p>{{ data_get($story,'data.description','Với OH!Under, sự thành công không chỉ đến từ niềm đam mê và sáng tạo, mà còn là nỗ lực thấu hiểu và trân trọng phái đẹp. 90% khách hàng quay lại là minh chứng cho chất lượng sản phẩm và dịch vụ tận tâm.') }}</p><a href="#">Xem thêm</a></div><img src="/theme-demo/shop605/ad-lac-quan.png" alt="Khách hàng OH!Under"></section>
<section class="s605-news xd-landing-block" data-landing-block-id="{{ data_get($news,'id') }}" data-block-type="latest_posts">@include('theme-shop605::partials.edit-button',['block'=>$news])<div class="s605-wrap"><h2>〰 <em>Blog</em> & Chia sẻ 〰</h2><div>@foreach($shopItems($news)->take(3) as $item)<article><img src="{{ $img($item,'/theme-demo/shop605/ad-lac-quan.png') }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title') }}</h3><p>{{ \Illuminate\Support\Str::limit(strip_tags((string)data_get($item,'summary')),150) }}</p><a href="{{ data_get($item,'url','#') }}">Đọc tiếp →</a></article>@endforeach</div></div></section>
</main>
@endsection
