@php
    $blocks = collect($landingBlocks ?? [])->values();
    $canEditLanding = auth('admin')->check() && request('mod') === 'admin' && is_array($landingPage ?? null);
    $blockUpdateUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.update', ['block' => '__BLOCK_ID__']) : '';
    $blockSourcePreviewUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.source-preview', ['block' => '__BLOCK_ID__']) : '';
    $blockPayload = $canEditLanding ? $blocks->keyBy('id')->toArray() : [];
    $editorLocales = [];
    $block = fn ($type) => $blocks->firstWhere('block_type', $type) ?? [];
    $items = fn ($value) => collect($value['dynamic_items'] ?? [])->filter()->isNotEmpty() ? collect($value['dynamic_items'])->filter()->values()->all() : collect(data_get($value, 'data.content.items', []))->filter()->values()->all();
    $hero=$block('hero_slider'); $about=$block('about_experience'); $services=$block('content_mosaic'); $solutions=$block('project_gallery'); $process=$block('process_steps'); $products=$block('featured_products'); $testimonials=$block('testimonials'); $partners=$block('partner_logos'); $news=$block('bizmax_latest_posts');
    $slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values(); if($slides->isEmpty()) $slides=collect([['title'=>'Nhanh chong - An toan cung XD321 Cargo','summary'=>'Toi uu moi hanh trinh van chuyen tu noi dia den quoc te.','image'=>'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=2200&q=90','button_label'=>'Xem them','link_url'=>'#dich-vu']]);
    $testimonial=$items($testimonials)[0] ?? [];
    $short=fn($value,$limit=130)=>\Illuminate\Support\Str::limit(strip_tags((string)$value),$limit);
@endphp
@extends('theme-xd321::layout')
@section('title', data_get($landingPage ?? [], 'meta_title', data_get($siteProfile ?? [], 'site_name', 'XD321 Cargo')))
@section('content')
<main class="x321-main">
<section class="x321-hero">@foreach($slides as $index=>$slide)<article class="x321-hero__slide {{ $index===0?'is-active':'' }}" data-x321-slide><img src="{{ data_get($slide,'image') }}" alt="{{ data_get($slide,'title') }}"><div></div><div class="x321-container"><p>{{ data_get($hero,'data.subtitle','XD321 Cargo') }}</p><h1>{{ data_get($slide,'title') }}</h1><span>{{ data_get($slide,'summary') }}</span><a href="{{ data_get($slide,'link_url','#dich-vu') }}" class="x321-button">{{ data_get($slide,'button_label','Xem them') }} <b>-></b></a></div></article>@endforeach</section>
<section id="gioi-thieu" class="x321-section"><div class="x321-container"><header class="x321-head"><h2>{{ data_get($about,'data.title','Gioi thieu ve XD321 Cargo') }}</h2><p>{{ data_get($about,'data.description','Giai phap van chuyen an toan, nhanh chong va hieu qua.') }}</p></header><div class="x321-about"><div><p>{{ data_get($about,'data.description','') }}</p><img src="{{ data_get($about,'media.image','https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1000&q=85') }}" alt="{{ data_get($about,'data.title') }}"></div><article><img src="https://images.unsplash.com/photo-1494412651409-8963ce7935a7?auto=format&fit=crop&w=1000&q=85" alt="Logistics"><h3>{{ data_get($about,'data.content.years','15+') }} nam kinh nghiem</h3><p>Ket noi hang hoa toan cau bang dich vu linh hoat, minh bach va dang tin cay.</p><a class="x321-button" href="#lien-he">Tu van ngay -></a></article></div></div></section>
<section id="dich-vu" class="x321-section x321-services"><div class="x321-container"><header class="x321-head"><h2>{{ data_get($services,'data.title','Dich vu van chuyen') }}</h2><p>{{ data_get($services,'data.description','Ket noi van tai toan cau, toi uu chuoi cung ung va dam bao giao hang dung hen.') }}</p></header><div class="x321-cards">@forelse($items($services) as $item)<article><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item,'title') }}"><div><h3>{{ data_get($item,'title','Dich vu logistics') }}</h3><p>{{ $short(data_get($item,'summary',data_get($item,'description','')),120) }}</p><a href="{{ data_get($item,'url','#') }}">Xem chi tiet -></a></div></article>@empty <p>Dang cap nhat dich vu.</p>@endforelse</div></div></section>
<section id="giai-phap" class="x321-section"><div class="x321-container"><header class="x321-head"><h2>{{ data_get($solutions,'data.title','Giai phap logistics hien dai') }}</h2><p>{{ data_get($solutions,'data.description','Giai phap linh hoat cho kho bai, don hang va chuoi cung ung.') }}</p></header><div class="x321-solution-grid">@forelse($items($solutions) as $index=>$item)<article><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1586528116493-da8b8d5a6c44?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item,'title') }}"><span>0{{ $index+1 }}</span><h3>{{ data_get($item,'title','Giai phap logistics') }}</h3><p>{{ $short(data_get($item,'summary',data_get($item,'description','')),120) }}</p><a href="{{ data_get($item,'url','#') }}">Xem chi tiet -></a></article>@empty <p>Dang cap nhat giai phap.</p>@endforelse</div></div></section>
<section id="quy-trinh" class="x321-process"><div class="x321-container"><header><p>{{ data_get($process,'data.subtitle','Quy trinh lam viec') }}</p><h2>{{ data_get($process,'data.title','Quy trinh van hanh logistics') }}</h2><span>{{ data_get($process,'data.description','') }}</span><a class="x321-button" href="#lien-he">{{ data_get($process,'data.button_label','Lien he ngay') }}</a></header><div>@foreach(data_get($process,'data.content.items',[]) as $index=>$item)<article><b>0{{ $index+1 }}</b><section><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></section></article>@endforeach</div></div></section>
<section id="san-pham" class="x321-section x321-products"><div class="x321-container"><header class="x321-head"><h2>{{ data_get($products,'data.title','San pham ho tro logistics') }}</h2><p>{{ data_get($products,'data.description','Vat tu dong goi, seal niem phong va thiet bi ho tro van chuyen.') }}</p></header><div class="x321-product-grid">@forelse($items($products) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=800&q=85') }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title','San pham dong goi') }}</h3><strong>{{ data_get($item,'price_formatted',data_get($item,'price','Lien he')) }}</strong></a></article>@empty <p>Dang cap nhat san pham.</p>@endforelse</div></div></section>
<section class="x321-testimonial"><div class="x321-container"><header class="x321-head"><h2>{{ data_get($testimonials,'data.title','Khach hang noi gi ve XD321 Cargo') }}</h2><p>{{ data_get($testimonials,'data.subtitle','Phan hoi tu doi tac') }}</p></header><div><img src="{{ data_get($testimonial,'image','https://images.unsplash.com/photo-1586528116493-da8b8d5a6c44?auto=format&fit=crop&w=900&q=85') }}" alt="Khach hang"><article><h3>{{ data_get($testimonial,'name',data_get($testimonial,'title','Doi tac logistics')) }}</h3><small>{{ data_get($testimonial,'role','Khach hang doanh nghiep') }}</small><blockquote>“{{ data_get($testimonial,'quote',data_get($testimonial,'summary','Dich vu chuyen nghiep, phan hoi nhanh va luon dam bao tien do cua tung lo hang.')) }}”</blockquote></article></div></div></section>
<section class="x321-partners"><div class="x321-container"><header class="x321-head"><h2>{{ data_get($partners,'data.title','Mang luoi doi tac toan cau') }}</h2></header><div>@forelse($items($partners) as $partner)<a href="{{ data_get($partner,'url','#') }}"><img src="{{ data_get($partner,'image','https://placehold.co/240x100/ffffff/173e78?text=Partner') }}" alt="{{ data_get($partner,'title','Partner') }}"></a>@empty <span>CATHAY</span><span>LUFTHANSA</span><span>CMA CGM</span><span>IATA</span>@endforelse</div></div></section>
<section id="tin-tuc" class="x321-section"><div class="x321-container"><header class="x321-head"><h2>{{ data_get($news,'data.title','Cap nhat tin tuc logistics') }}</h2><p>{{ data_get($news,'data.subtitle','Kien thuc va thi truong') }}</p></header><div class="x321-news">@forelse($items($news) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item,'title') }}"><div><small>{{ data_get($item,'published_at',data_get($item,'meta','XD321 Cargo')) }}</small><h3>{{ data_get($item,'title','Tin tuc logistics') }}</h3><p>{{ $short(data_get($item,'summary',data_get($item,'description','')),120) }}</p></div></a></article>@empty <p>Dang cap nhat tin tuc.</p>@endforelse</div></div></section>
</main>
@endsection
