@include('themes.common.catalog-shell-styles')
@php
    $summary = (array) data_get($themeShellData ?? [], 'cart_summary', []);
    $items = collect($summary['items'] ?? []);
    $formatPrice = fn ($value) => is_numeric($value) && (float) $value > 0 ? number_format((float) $value, 0, ',', '.').'đ' : 'Liên hệ';
@endphp



<style>
.catalog-cart-page{min-height:70vh;padding:145px 0 90px;background:#f6f1e8;color:#173d37}.catalog-cart-title span{color:#b47827;text-transform:uppercase;letter-spacing:2px;font-weight:700}.catalog-cart-title h1{font:700 clamp(38px,5vw,60px) 'Dancing Script',cursive;margin:8px 0}.catalog-cart-title p{color:#66756f}.catalog-cart-layout{display:grid;grid-template-columns:1fr 340px;gap:30px;margin-top:36px;align-items:start}.catalog-cart-list{display:grid;gap:16px}.catalog-cart-item{display:grid;grid-template-columns:130px 1fr auto;gap:20px;background:#fff;padding:17px;border-radius:12px;box-shadow:0 12px 35px rgba(42,34,19,.08)}.catalog-cart-item img{height:125px;border-radius:8px}.catalog-cart-item h2{font-size:19px;margin:8px 0}.catalog-cart-item small{color:#8a9792}.catalog-cart-actions{text-align:right}.catalog-cart-actions strong{display:block;color:#dc3f3f;font-size:20px;margin-bottom:12px}.catalog-cart-actions form{display:flex;justify-content:flex-end;gap:7px;margin-top:8px}.catalog-cart-actions input{width:65px;height:39px;border:1px solid #dbcdb8;border-radius:6px;text-align:center}.catalog-cart-actions button{border:0;border-radius:6px;padding:0 11px;background:var(--catalog-green);color:#fff;font-weight:700}.catalog-cart-actions .is-remove{height:39px;background:#fff0ee;color:#c33;border:1px solid #ffd1cb}.catalog-cart-summary{position:sticky;top:105px;background:var(--catalog-green);color:#fff;border-radius:14px;padding:27px}.catalog-cart-summary h2{margin-top:0}.catalog-cart-summary__row{display:flex;justify-content:space-between;gap:15px;padding:14px 0;border-top:1px solid rgba(255,255,255,.18)}.catalog-cart-summary__row strong{color:var(--catalog-gold);font-size:23px}.catalog-checkout{display:block;text-align:center;background:var(--catalog-gold);padding:14px;border-radius:8px;margin-top:18px;font-weight:700}.catalog-continue{display:block;text-align:center;margin-top:14px;color:#d9e4e1}.catalog-cart-empty{background:#fff;border-radius:14px;padding:70px 25px;text-align:center}.catalog-cart-empty h2{font:700 42px 'Dancing Script',cursive}.catalog-cart-empty p{margin-bottom:30px;color:#67756f}@media(max-width:850px){.catalog-cart-layout{grid-template-columns:1fr}.catalog-cart-summary{position:static}.catalog-cart-item{grid-template-columns:100px 1fr}.catalog-cart-item img{height:100px}.catalog-cart-actions{grid-column:1/-1;text-align:left}.catalog-cart-actions form{justify-content:flex-start}}@media(max-width:520px){.catalog-cart-page{padding-top:115px}.catalog-cart-item{grid-template-columns:80px 1fr;gap:12px}.catalog-cart-item img{height:80px}.catalog-cart-title h1{font-size:42px}}
</style>


<main class="catalog-cart-page"><div class="catalog-container"><header class="catalog-cart-title"><span></span><h1>Giỏ hàng của bạn</h1><p>Kiểm tra sản phẩm đã chọn trước khi tiếp tục đặt hàng.</p></header>
@if(session('cart_success'))<p>{{ session('cart_success') }}</p>@endif
@if($items->isNotEmpty())<div class="catalog-cart-layout"><section class="catalog-cart-list">@foreach($items as $item)@php($quantity=max(1,(int)data_get($item,'quantity',1)))<article class="catalog-cart-item"><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image') }}" alt="{{ data_get($item,'title') }}"></a><div><small>{{ data_get($item,'sku') ? 'SKU: '.data_get($item,'sku') : 'Món ngon Dola' }}</small><h2><a href="{{ data_get($item,'url','#') }}">{{ data_get($item,'title') }}</a></h2><span>Số lượng: {{ $quantity }}</span></div><div class="catalog-cart-actions"><strong>{{ $formatPrice((float)data_get($item,'price',0)*$quantity) }}</strong><form method="POST" action="{{ route('site.cart.update',['productId'=>data_get($item,'product_id')]) }}">@csrf @method('PATCH')<input type="number" name="quantity" min="1" max="{{ data_get($item,'stock',99) ?: 99 }}" value="{{ $quantity }}" aria-label="Số lượng"><button>Cập nhật</button></form><form method="POST" action="{{ route('site.cart.remove',['productId'=>data_get($item,'product_id')]) }}">@csrf @method('DELETE')<button class="is-remove">Xóa</button></form></div></article>@endforeach</section><aside class="catalog-cart-summary"><h2>Tóm tắt đơn hàng</h2><div class="catalog-cart-summary__row"><span>Số lượng</span><b>{{ (int)data_get($summary,'count',0) }} sản phẩm</b></div><div class="catalog-cart-summary__row"><span>Tạm tính</span><strong>{{ $formatPrice(data_get($summary,'subtotal',0)) }}</strong></div><a class="catalog-checkout" href="{{ route('site.checkout.index') }}">Tiến hành đặt hàng</a><a class="catalog-continue" href="{{ route('site.catalog.search') }}">← Tiếp tục chọn sản phẩm</a></aside></div>@else<div class="catalog-cart-empty"><h2>Giỏ hàng đang trống</h2><p>Khám phá sản phẩm và chọn những sản phẩm yêu thích cho bữa ăn của bạn.</p><a class="catalog-book" href="{{ route('site.catalog.search') }}">Xem sản phẩm</a></div>@endif
</div></main>

