<style>
.tna-article{--article-accent:#244b60;--article-tint:color-mix(in srgb,var(--article-accent) 8%,white);font-family:"Segoe UI","Noto Sans",Arial,sans-serif;line-height:1.6;text-align:left;width:100%}.tna-article *{box-sizing:border-box}.tna-article h1,.tna-article h2,.tna-article h3{font-family:inherit;text-transform:none;letter-spacing:normal}.tna-article img{float:none}.tna-article button{height:auto;width:auto}.tna-article figure{padding:0}

.tna-article{background:#f7f8f9;color:#183b2c;padding:28px 0 72px}.tna-article-wrap{width:min(1240px,calc(100% - 40px));margin:auto}.tna-article a{color:inherit;text-decoration:none}.tna-article a:hover{color:var(--article-accent)}.tna-article a:focus-visible,.tna-article button:focus-visible,.tna-article summary:focus-visible{outline:3px solid #e89520;outline-offset:4px}.tna-article-breadcrumb,.tna-article-meta{display:flex;gap:12px;flex-wrap:wrap;font-size:13px;color:#587365}.tna-article-heading{max-width:950px;padding:32px 0}.tna-article-kicker{font-size:12px;text-transform:uppercase;letter-spacing:2px;font-weight:700;color:var(--article-accent)}.tna-article-heading h1{font-size:clamp(28px,3.4vw,44px);line-height:1.25;margin:14px 0 18px;overflow-wrap:anywhere}.tna-article-heading>p{font-size:17px;line-height:1.8;margin:20px 0 0;color:#536b5f}.tna-article-layout{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:32px;align-items:start}.tna-article-layout>*,.tna-article-sidebar{min-width:0}.tna-article-paper{padding:28px;background:#fff;border:1px solid #dfebe3;border-radius:18px}.tna-article-cover{margin:-28px -28px 28px;overflow:hidden;border-radius:18px 18px 0 0}.tna-article-cover img{width:100%;max-height:480px;aspect-ratio:16/9;object-fit:cover;display:block}.tna-article-toc{background:var(--article-tint);border:1px solid #dceadf;padding:18px 22px;border-radius:12px;margin-bottom:26px}.tna-article [hidden]{display:none!important}.tna-article-toc summary{cursor:pointer;font-weight:700}.tna-article-toc ol{margin:12px 0 0;padding-left:20px}.tna-article-toc li{padding:5px 0;line-height:1.6}.tna-article-body{font-size:16px;line-height:1.95;color:#354d40;overflow-wrap:anywhere;overflow-x:auto}.tna-article-body h2,.tna-article-body h3{line-height:1.4;color:#173e2b;margin:30px 0 14px;scroll-margin-top:120px}.tna-article-body h2{font-size:24px}.tna-article-body h3{font-size:20px}.tna-article-body img,.tna-article-body video,.tna-article-body iframe{max-width:100%;height:auto}.tna-article-body a{color:var(--article-accent);border-bottom:1px solid #91b89f}.tna-article-body blockquote{border-left:3px solid var(--article-accent);margin:24px 0;padding:12px 22px;background:#f7f8f9}.tna-article-tags{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}.tna-article-tags a{background:var(--article-tint);padding:6px 12px;border-radius:20px}.tna-article-share{border-top:1px solid #e1ebe4;padding-top:24px;margin-top:28px;display:flex;gap:14px;flex-wrap:wrap;align-items:center;font-size:13px}.tna-article-share button{background:var(--article-accent);color:white;border:0;border-radius:24px;padding:12px 20px;font:inherit;cursor:pointer}.tna-article-share input{width:100%;min-width:0;padding:12px;border:1px solid #bacebf}.tna-article-sidebar>section{padding:24px;border-radius:16px;margin-bottom:24px}.tna-article-latest{background:white;border:1px solid #dfebe3}.tna-article-sidebar h2,.tna-article-related>h2{font-size:23px;line-height:1.4;margin:0 0 20px}.tna-article-latest-item{display:flex;gap:14px;align-items:flex-start;border-bottom:1px solid #e6eee8;padding:18px 0}.tna-article-latest-item img{width:76px;height:76px;object-fit:cover;border-radius:8px;flex-shrink:0}.tna-article-latest-item h3{font-size:14px;line-height:1.6;margin:0 0 7px;overflow-wrap:anywhere}.tna-article-latest-item time{font-size:12px;color:#6d8075}.tna-article-all{display:inline-block;margin-top:20px;font-weight:700;font-size:14px}.tna-article-promo{background:var(--article-tint)}.tna-article-promo p{font-size:15px;line-height:1.8}.tna-article-promo a{display:block;font-size:14px;font-weight:700;line-height:1.6}.tna-article-related{margin-top:38px}.tna-article-related-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.tna-article-card{border:1px solid #dfebe3;border-radius:14px;overflow:hidden;background:white}.tna-article-card>img{width:100%;aspect-ratio:3/2;object-fit:cover;display:block}.tna-article-card>div{padding:18px}.tna-article-card h3{font-size:16px;line-height:1.6;margin:0 0 16px;overflow-wrap:anywhere}.tna-article-card span{font-size:12px;font-weight:700;color:var(--article-accent)}
@media(max-width:1000px){.tna-article-layout{grid-template-columns:minmax(0,1fr) 280px;gap:22px}.tna-article-related-grid{grid-template-columns:1fr}.tna-article-card{display:flex}.tna-article-card>img{width:120px;object-fit:cover}.tna-article-sidebar>section{padding:18px}}
@media(max-width:760px){.tna-article-wrap{width:calc(100% - 32px)}.tna-article-layout{grid-template-columns:1fr}.tna-article-heading{padding:24px 0}.tna-article-paper{padding:20px}.tna-article-cover{margin:-20px -20px 22px}.tna-article-body{font-size:16px}.tna-article-body h2{font-size:22px}.tna-article-sidebar{margin-top:12px}.tna-article-card>img{width:100px}.tna-article-card>div{padding:14px}}
.tna-article[data-article-theme="AUTO850"]{--article-accent:var(--a850-red,#e10600)}
.tna-article[data-article-theme="AUTO851"]{--article-accent:var(--a851-navy,#1c3268)}
.tna-article[data-article-theme="AUTO852"]{--article-accent:var(--a852-orange,#ff5a00)}
.tna-article[data-article-theme="AUTO853"]{--article-accent:var(--a853-red,#ed2f3b)}
.tna-article[data-article-theme="BDS701"]{--article-accent:var(--bds-green,#84c441)}
.tna-article[data-article-theme="BOOK920"]{--article-accent:var(--book20-teal,#08728c)}
.tna-article[data-article-theme="BZ501"]{--article-accent:var(--bz-red,#ff3216)}
.tna-article[data-article-theme="CA0050"]{--article-accent:var(--ca-blue,#0887df)}
.tna-article[data-article-theme="DL750"]{--article-accent:var(--dl-olive,#3f5f2c)}
.tna-article[data-article-theme="DN202"]{--article-accent:var(--d202-blue,#3799ee)}
.tna-article[data-article-theme="DN302"]{--article-accent:var(--dn-navy,#465474)}
.tna-article[data-article-theme="DN350"]{--article-accent:var(--dn350-orange,#ff9d10)}
.tna-article[data-article-theme="DN351"]{--article-accent:var(--dn351-red,#c8212a)}
.tna-article[data-article-theme="E800"]{--article-accent:var(--e800-orange,#ff773d)}
.tna-article[data-article-theme="E801"]{--article-accent:var(--pink,#ed0060)}
.tna-article[data-article-theme="E802"]{--article-accent:var(--orange,#ffae25)}
.tna-article[data-article-theme="E803"]{--article-accent:var(--green,#72c800)}
.tna-article[data-article-theme="E804"]{--article-accent:var(--e804-red,#f02f49)}
.tna-article[data-article-theme="E805"]{--article-accent:var(--e805-red,#ef3e35)}
.tna-article[data-article-theme="E806"]{--article-accent:var(--e806-red,#df3035)}
.tna-article[data-article-theme="E807"]{--article-accent:var(--e807-orange,#f45b0b)}
.tna-article[data-article-theme="EC900"]{--article-accent:var(--ec9-blue,#177be6)}
.tna-article[data-article-theme="EC901"]{--article-accent:var(--ec91-red,#bd1015)}
.tna-article[data-article-theme="EC902"]{--article-accent:var(--ec92-blue,#071b9b)}
.tna-article[data-article-theme="EC903"]{--article-accent:var(--ec93-red,#ed1c24)}
.tna-article[data-article-theme="EC904"]{--article-accent:var(--ec94-red,#ef3c33)}
.tna-article[data-article-theme="EC905"]{--article-accent:var(--ec95-blue,#315d8c)}
.tna-article[data-article-theme="EC906"]{--article-accent:var(--ec96-green,#00763c)}
.tna-article[data-article-theme="EC907"]{--article-accent:var(--r,#f3182b)}
.tna-article[data-article-theme="EC908"]{--article-accent:var(--orange,#ff5037)}
.tna-article[data-article-theme="EC909"]{--article-accent:var(--ink,#080808)}
.tna-article[data-article-theme="EC910"]{--article-accent:var(--ec10-gold,#dba621)}
.tna-article[data-article-theme="EC911"]{--article-accent:var(--ec11-blue,#2f5be7)}
.tna-article[data-article-theme="EC912"]{--article-accent:var(--ec12-red,#c9142a)}
.tna-article[data-article-theme="EC913"]{--article-accent:var(--ec13-red,#c9142a)}
.tna-article[data-article-theme="EC914"]{--article-accent:var(--ec14-orange,#f47a26)}
.tna-article[data-article-theme="EC915"]{--article-accent:var(--ec15-copper,#b97c58)}
.tna-article[data-article-theme="EC916"]{--article-accent:var(--ec16-teal,#16b6a3)}
.tna-article[data-article-theme="EC917"]{--article-accent:var(--ec17-orange,#f57408)}
.tna-article[data-article-theme="FOOT401"]{--article-accent:var(--foot-gold,#d6a62d)}
.tna-article[data-article-theme="FOOT403"]{--article-accent:var(--dr-green,#0d3b35)}
.tna-article[data-article-theme="FOOT404"]{--article-accent:var(--f404-primary,#4c50b9)}
.tna-article[data-article-theme="FOOT405"]{--article-accent:var(--f405-green,#38ba82)}
.tna-article[data-article-theme="FOOT406"]{--article-accent:var(--f406-green,#9bc24b)}
.tna-article[data-article-theme="FOOT407"]{--article-accent:var(--f407-green,#164c3f)}
.tna-article[data-article-theme="FOOT408"]{--article-accent:var(--f408-red,#e90025)}
.tna-article[data-article-theme="FOOT409"]{--article-accent:var(--f409-red,#ed002b)}
.tna-article[data-article-theme="NEWS88"]{--article-accent:var(--n88-red,#e4002b)}
.tna-article[data-article-theme="NT501"]{--article-accent:var(--nt-gold,#dbae56)}
.tna-article[data-article-theme="NT502"]{--article-accent:var(--n502-orange,#ff9f16)}
.tna-article[data-article-theme="NT503"]{--article-accent:var(--n503-green,#064f38)}
.tna-article[data-article-theme="NT504"]{--article-accent:var(--n504-green,#174f40)}
.tna-article[data-article-theme="SER0101"]{--article-accent:var(--ser-primary,#0f766e)}
.tna-article[data-article-theme="SER102"]{--article-accent:var(--ser-orange,#ff5a00)}
.tna-article[data-article-theme="SER103"]{--article-accent:var(--ser103-accent,#ad8d89)}
.tna-article[data-article-theme="SHOP601"]{--article-accent:var(--s601-red,#ef3f24)}
.tna-article[data-article-theme="SHOP602"]{--article-accent:var(--s602-green,#174f3f)}
.tna-article[data-article-theme="SHOP603"]{--article-accent:var(--s603-green,#176044)}
.tna-article[data-article-theme="SHOP604"]{--article-accent:var(--s604-rose,#be5a5d)}
.tna-article[data-article-theme="SHOP605"]{--article-accent:var(--p,#ff6387)}
.tna-article[data-article-theme="SPA111"]{--article-accent:var(--sp11-teal,#176c6c)}
.tna-article[data-article-theme="SPA502"]{--article-accent:var(--spa-gold,#ffb400)}
.tna-article[data-article-theme="TH0050"]{--article-accent:var(--th5-green,#064638)}
.tna-article[data-article-theme="TOOL750"]{--article-accent:var(--t750-red,#e42838)}
.tna-article[data-article-theme="TOOL751"]{--article-accent:var(--t751-yellow,#ffbf00)}
.tna-article[data-article-theme="XD0301"]{--article-accent:var(--lime-dark,#9fb500)}
.tna-article[data-article-theme="XD0302"]{--article-accent:var(--xd2-red,#ef392a)}
.tna-article[data-article-theme="XD0303"]{--article-accent:var(--xd3-orange,#ef4c23)}
.tna-article[data-article-theme="XD0304"]{--article-accent:var(--xd4-green,#91bf3d)}
.tna-article[data-article-theme="XD0305"]{--article-accent:var(--gold,#f0a629)}
.tna-article[data-article-theme="XD0306"]{--article-accent:var(--gold,#e90025)}
.tna-article[data-article-theme="XD0307"]{--article-accent:var(--gold,#f0a629)}
.tna-article[data-article-theme="XD0308"]{--article-accent:var(--xd4-green,#91bf3d)}
.tna-article[data-article-theme="XD0309"]{--article-accent:var(--gold,#f0a629)}
.tna-article[data-article-theme="XD0310"]{--article-accent:var(--gold,#f0a629)}
.tna-article[data-article-theme="XD0311"]{--article-accent:var(--gold,#f0a629)}
.tna-article[data-article-theme="XD0312"]{--article-accent:var(--gold,#f0a629)}
.tna-article[data-article-theme="XD0313"]{--article-accent:var(--rx13-green,#7bd615)}
.tna-article[data-article-theme="XD0314"]{--article-accent:var(--bb14-navy,#07142c)}
.tna-article[data-article-theme="XD0315"]{--article-accent:var(--af15-orange,#f47c00)}
.tna-article[data-article-theme="XD0318"]{--article-accent:var(--fg18-orange,#f4512a)}
.tna-article[data-article-theme="XD0320"]{--article-accent:var(--xd20-red,#e32918)}
.tna-article[data-article-theme="XD0322"]{--article-accent:var(--o,#ff5b17)}
.tna-article[data-article-theme="XD0323"]{--article-accent:var(--xd323-green,#07823f)}
.tna-article[data-article-theme="XD0324"]{--article-accent:var(--wolf-gold,#c9a57d)}
.tna-article[data-article-theme="XD0325"]{--article-accent:var(--x325-orange,#ff5b0b)}
.tna-article[data-article-theme="XD321"]{--article-accent:var(--b,#153d78)}
body:has(.tna-article[data-article-theme="BDS701"]) .bds-header{position:relative;top:auto;background:#1f2d40}
body:has(.tna-article[data-article-theme="BDS702"]) .bds-header{position:relative;top:auto;background:#1f2d40}
body:has(.tna-article[data-article-theme="DN302"]) .dn-header{position:relative;top:auto;background:#fff}
body:has(.tna-article[data-article-theme="EC915"]) .ec15-header{position:relative;top:auto;background:#24201d}
body:has(.tna-article[data-article-theme="FOOT403"]) .dr-header{position:relative;top:auto;background:#173d37}
body:has(.tna-article[data-article-theme="FOOT408"]) .f408-mainbar{position:relative;top:auto;background:#fff}
body:has(.tna-article[data-article-theme="XD0304"]) .xd4-header{position:relative;top:auto;background:var(--xd4-ink,#202326)}
body:has(.tna-article[data-article-theme="XD0305"]) .xd5-header{position:relative;top:auto;background:#202326}
body:has(.tna-article[data-article-theme="XD0306"]) .xd5-header{position:relative;top:auto;background:#202326}
body:has(.tna-article[data-article-theme="XD0308"]) .xd4-header{position:relative;top:auto;background:var(--xd4-ink,#202326)}
body:has(.tna-article[data-article-theme="XD0309"]) .xd5-header{position:relative;top:auto;background:#202326}
body:has(.tna-article[data-article-theme="XD0310"]) .xd5-header{position:relative;top:auto;background:#202326}
body:has(.tna-article[data-article-theme="XD0312"]) .xd12-header{position:relative;top:auto;background:#fff}
body:has(.tna-article[data-article-theme="XD0315"]) .af15-site-header{position:relative;top:auto;background:#202326}
body:has(.tna-article[data-article-theme="XD0323"]) .xd323-header{position:relative;top:auto;background:#fff}
body:has(.tna-article[data-article-theme="XD0324"]) .xd324-header{position:relative;top:auto;background:#202326}
body:has(.tna-article[data-article-theme="XD0325"]) .x325-nav{position:relative;top:auto;background:#fff}
body:has(.tna-article) .f406-header__shell{margin-bottom:0}
body:has(.tna-article[data-article-theme="FOOT401"]) .foot-navigation-wrap{height:auto}
body:has(.tna-article[data-article-theme="FOOT401"]) .foot-navigation{position:relative;left:auto;transform:none;margin-inline:auto}
</style>
