@php
    $blocks = collect($landingBlocks ?? [])->filter(fn ($block) => (bool) data_get($block, 'is_visible', true));
    $byAnchor = fn (string $anchor) => (array) ($blocks->first(fn ($block) => data_get($block, 'anchor_id') === $anchor) ?? []);
    $hero=$byAnchor('top'); $about=$byAnchor('gioi-thieu'); $categoriesBlock=$byAnchor('danh-muc'); $menuBlock=$byAnchor('thuc-don'); $featuredBlock=$byAnchor('mon-noi-bat'); $statsBlock=$byAnchor('con-so'); $postsBlock=$byAnchor('tin-tuc'); $testimonialsBlock=$byAnchor('cam-nhan'); $contactBlock=$byAnchor('lien-he');
    $itemsFor = function(array $block) { $custom=collect(data_get($block,'data.content.items',[])); $dynamic=collect(data_get($block,'dynamic_items',[])); return data_get($block,'settings.source','custom')!=='custom' && $dynamic->isNotEmpty() ? $dynamic : $custom; };
    $slides=collect(data_get($hero,'dynamic_items',[])); if($slides->isEmpty()) $slides=collect(data_get($hero,'data.content.slides',[]));
    $categories=$itemsFor($categoriesBlock); $menu=$itemsFor($menuBlock); $featured=$itemsFor($featuredBlock); $posts=$itemsFor($postsBlock); $testimonials=collect(data_get($testimonialsBlock,'data.content.items',[]));
    $aboutImages=collect(data_get($about,'media.images',[])); $statsImages=collect(data_get($statsBlock,'data.content.images',[])); $stats=$itemsFor($statsBlock);
    $formatPrice=fn($price)=>is_numeric($price)&&$price>0?number_format((float)$price,0,',','.').'đ':'Liên hệ';
    $categoriesTabs=$menu->pluck('category')->filter()->unique()->values();
@endphp
@extends('theme-foot403::layout')
@section('title', data_get($landingPage ?? [], 'meta_title', data_get($siteProfile ?? [], 'site_name', 'Dola Restaurant')))
@section('content')
<section class="dr-hero" data-dr-hero data-autoplay="{{ data_get($hero,'settings.autoplay_ms',6500) }}">
@forelse($slides as $slide)<article class="dr-hero__slide {{ $loop->first?'is-active':'' }}" data-dr-slide><img src="{{ data_get($slide,'image') }}" alt="{{ data_get($slide,'title','Dola Restaurant') }}"><div class="dr-hero__shade"></div><div class="dr-hero__content"><p>{{ data_get($slide,'kicker',data_get($hero,'data.title','Dola Restaurant')) }}</p><h1>{{ data_get($slide,'title',data_get($hero,'data.subtitle')) }}</h1><small>{{ data_get($slide,'summary',data_get($hero,'data.description')) }}</small><a href="{{ data_get($slide,'link_url','#lien-he') }}">{{ data_get($slide,'button_label',data_get($hero,'data.button_label','Đặt bàn ngay')) }}</a></div></article>@empty<p class="dr-empty">Banner đang được cập nhật.</p>@endforelse
@if($slides->count()>1)<div class="dr-dots">@foreach($slides as $slide)<button class="{{ $loop->first?'is-active':'' }}" data-dr-hero-dot="{{ $loop->index }}" aria-label="Slide {{ $loop->iteration }}"></button>@endforeach</div>@endif</section>

<section class="dr-about dr-section" id="gioi-thieu"><div class="dr-container dr-about__grid"><div><span class="dr-kicker">{{ data_get($about,'data.subtitle','Về chúng tôi') }}</span><h2 class="dr-script">{{ data_get($about,'data.title','Dola Restaurant') }}</h2><p>{{ data_get($about,'data.description') }}</p><a class="dr-link" href="#danh-muc">{{ data_get($about,'data.button_label','Xem thêm') }} →</a></div><div class="dr-collage">@foreach($aboutImages->take(4) as $image)<img src="{{ $image }}" alt="Không gian Dola Restaurant">@endforeach</div></div></section>

<section class="dr-section" id="danh-muc"><div class="dr-container">@include('theme-foot403::components.heading',['title'=>data_get($categoriesBlock,'data.title','Danh mục nổi bật')])<div class="dr-category-grid">@foreach($categories as $item)<article><img src="{{ data_get($item,'image') }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></article>@endforeach</div></div></section>

<section class="dr-section dr-menu" id="thuc-don"><div class="dr-container">@include('theme-foot403::components.heading',['title'=>data_get($menuBlock,'data.title','Thực đơn của chúng tôi')])<div class="dr-tabs" data-dr-tabs><button class="is-active" data-dr-tab="all">Tất cả</button>@foreach($categoriesTabs as $tab)<button data-dr-tab="{{ $tab }}">{{ $tab }}</button>@endforeach</div><div class="dr-product-grid">@forelse($menu as $item)@include('theme-foot403::partials.product-card',['item'=>$item,'block'=>$menuBlock])@empty<p>Thực đơn đang được cập nhật.</p>@endforelse</div></div></section>

<section class="dr-section" id="mon-noi-bat"><div class="dr-container">@include('theme-foot403::components.heading',['title'=>data_get($featuredBlock,'data.title','Món ăn nổi bật')])<div class="dr-product-grid dr-product-grid--featured">@foreach($featured->take(5) as $item)@include('theme-foot403::partials.product-card',['item'=>$item,'block'=>$featuredBlock])@endforeach</div></div></section>

<section class="dr-section dr-numbers" id="con-so"><div class="dr-container"><div class="dr-image-strip">@foreach($statsImages->take(4) as $image)<img src="{{ $image }}" alt="Trải nghiệm tại nhà hàng">@endforeach</div><div class="dr-stats">@foreach($stats as $item)<article><span>{{ ['⌂','♨','♙','♨'][$loop->index] ?? '✦' }}</span><div><strong>{{ data_get($item,'title') }}</strong><small>{{ data_get($item,'summary') }}</small></div></article>@endforeach</div></div></section>

<section class="dr-section" id="tin-tuc"><div class="dr-container">@include('theme-foot403::components.heading',['title'=>data_get($postsBlock,'data.title','Tin tức')])<div class="dr-post-grid">@foreach($posts->take(3) as $post)<article><img src="{{ data_get($post,'image') }}" alt="{{ data_get($post,'title') }}"><div><time>{{ data_get($post,'published_at') }}</time><small>Đăng bởi: {{ data_get($post,'author','Admin Dola') }}</small><h3>{{ data_get($post,'title') }}</h3><p>{{ \Illuminate\Support\Str::limit(strip_tags((string)data_get($post,'summary')),120) }}</p><a href="{{ data_get($post,'url','#') }}">{{ data_get($postsBlock,'data.button_label','Xem thêm') }} →</a></div></article>@endforeach</div></div></section>

<section class="dr-testimonials" id="cam-nhan" style="--dr-testimonial-bg:url('{{ data_get($testimonialsBlock,'data.content.background') }}')"><div class="dr-container"><div class="dr-quote" data-dr-quotes>@foreach($testimonials as $item)<article class="{{ $loop->first?'is-active':'' }}" data-dr-quote><header><img src="{{ data_get($item,'image') }}" alt="{{ data_get($item,'name') }}"><div><h3>{{ data_get($item,'name') }}</h3><span>{{ data_get($item,'role') }}</span></div><b>”</b></header><p>{{ data_get($item,'quote') }}</p></article>@endforeach<div class="dr-dots dr-dots--static">@foreach($testimonials as $item)<button class="{{ $loop->first?'is-active':'' }}" data-dr-quote-dot="{{ $loop->index }}" aria-label="Cảm nhận {{ $loop->iteration }}"></button>@endforeach</div></div></div></section>

<section class="dr-section dr-contact" id="lien-he"><div class="dr-container dr-contact__grid"><div><span class="dr-kicker">{{ data_get($contactBlock,'data.subtitle','Liên hệ với Dola') }}</span><h2>{{ data_get($contactBlock,'data.title','Đặt bàn cho một bữa ăn đáng nhớ') }}</h2><p>{{ data_get($contactBlock,'data.description') }}</p><div class="dr-contact__info"><p><b>Địa chỉ</b>{{ data_get($contactBlock,'data.content.address') }}</p><p><b>Hotline</b>{{ data_get($contactBlock,'data.content.phone') }}</p><p><b>Giờ mở cửa</b>{{ data_get($contactBlock,'data.content.hours') }}</p></div></div><form method="POST" action="{{ route('site.contact.submit') }}">@csrf<input type="hidden" name="source" value="foot403-reservation"><div><label>Họ và tên<input name="name" required placeholder="Nguyễn Văn A"></label><label>Số điện thoại<input name="phone" required placeholder="0900 000 000"></label></div><div><label>Email<input type="email" name="email" required placeholder="email@example.com"></label><label>Số khách<input type="number" min="1" max="30" value="2"></label></div><label>Yêu cầu đặt bàn<textarea name="message" required placeholder="Ngày, giờ dự kiến và yêu cầu đặc biệt..."></textarea></label><button type="submit">{{ data_get($contactBlock,'data.button_label','Gửi yêu cầu đặt bàn') }}</button></form></div></section>
@endsection
