@php
$blocks=collect($landingBlocks??[])->values();
$items=function(array $b){$d=collect($b['dynamic_items']??[])->filter()->values();return $d->isNotEmpty()?$d:collect(data_get($b,'data.content.items',[]))->filter()->values();};
$img=fn($i,$f='')=>data_get($i,'image',data_get($i,'image_url',$f)); $assetImage=fn($n)=>asset('themes/AUTO851/images/'.$n.'.png');
$price=fn($i)=>(float)data_get($i,'price')>0?number_format((float)data_get($i,'price'),0,',','.').'đ':'Liên hệ';
$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null); $blockUpdateUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.update',['block'=>'__BLOCK_ID__']):''; $blockSourcePreviewUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.source-preview',['block'=>'__BLOCK_ID__']):''; $blockPayload=$canEditLanding?$blocks->filter(fn($b)=>filled($b['id']??null))->keyBy('id')->toArray():[]; $editorLocales=[];
@endphp
@extends('theme-auto851::layout')
@section('content')<main>
@foreach($blocks as $block) @php($type=data_get($block,'block_type'))
@if($type==='auto851_hero')
<section class="a851-hero xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}" style="background-image:url('{{ data_get($block,'media.image',$assetImage('hero-suv')) }}')"><div class="a851-wrap"><div class="a851-hero-copy"><span>{{ data_get($block,'data.subtitle') }}</span><h1>{{ data_get($block,'data.title') }}</h1><p>{{ data_get($block,'data.description') }}</p><a class="a851-btn" href="#mua-xe">{{ data_get($block,'data.button_label') }} <i class="fa-solid fa-arrow-right"></i></a></div></div>@include('theme-auto851::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto851_model_rail')
<section class="a851-models xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a851-model-track">@foreach($items($block)->take(5) as $item)<a href="{{ data_get($item,'url','#mua-xe') }}"><h3>{{ data_get($item,'title') }}</h3><small>{{ data_get($item,'summary','Premium') }}</small><img src="{{ $img($item,$assetImage('car-'.$loop->iteration)) }}" alt="{{ data_get($item,'title') }}"></a>@endforeach</div>@include('theme-auto851::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto851_buy_sell')
<section id="mua-xe" class="a851-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a851-wrap a851-market"><div class="a851-buy"><h2><i></i>{{ data_get($block,'data.title') }}</h2><form action="{{ route('site.catalog.search',['locale'=>app()->getLocale()]) }}"><input name="q" placeholder="Tìm kiếm bằng nhãn hiệu, mẫu xe hoặc từ khóa"><button>Tìm kiếm</button></form><b>Hãng xe</b><div class="a851-brandchips">@foreach(['LEXUS','AUDI','MG','VINFAST','BMW','PEUGEOT','MERCEDES','HYUNDAI','MAZDA','KIA'] as $brand)<span>{{ $brand }}</span>@endforeach</div><b>Dòng xe</b><div class="a851-bodytypes">@foreach(['CUV','SUV','MPV','Sedan','Hatchback','Pickup','Coupe'] as $body)<span><i class="fa-solid fa-car-side"></i>{{ $body }}</span>@endforeach</div><div class="a851-prices"><span>Dưới 300tr</span><span>Từ 500tr - 700tr</span><span>Từ 700tr - 1 tỷ</span><span>Trên 700tr</span></div></div><aside id="ban-xe"><h2><i></i>{{ data_get($block,'data.subtitle') }}</h2><input placeholder="Hãng xe. VD: Mercedes, BMW"><input placeholder="Tên xe. VD: C300, X8"><button>Gửi thông tin</button><p>Để tiếp tục, tôi đồng ý với Chính sách quyền riêng tư và Điều khoản sử dụng.</p><div><span><i class="fa-regular fa-clock"></i>1 phút hoàn thiện hồ sơ</span><span><i class="fa-regular fa-file-lines"></i>15 phút báo giá sơ bộ</span><span><i class="fa-solid fa-money-bill"></i>Nhận tiền cọc</span><span><i class="fa-regular fa-credit-card"></i>Ký kết &amp; thanh toán</span></div></aside></div>@include('theme-auto851::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto851_featured_cars')
<section id="xe-noi-bat" class="a851-section a851-soft xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a851-wrap"><div class="a851-title-row"><h2>{{ data_get($block,'data.title') }}</h2><div><span>✓ Kiểm định 160 bước</span><span>✓ Bảo hành đến 12 tháng</span><span>✓ 5 ngày hoàn tiền</span></div></div><div class="a851-car-grid">@foreach($items($block)->take(8) as $item)<article><h3>{{ data_get($item,'title') }}</h3><small>{{ data_get($item,'summary','SUV') }}</small><a href="{{ data_get($item,'url','#') }}"><img src="{{ $img($item,$assetImage('car-'.(($loop->index%8)+1))) }}" alt="{{ data_get($item,'title') }}"></a><p><span><i class="fa-solid fa-gas-pump"></i> Xăng</span><span><i class="fa-solid fa-gear"></i> Số tự động</span></p><div class="a851-card-footer"><strong>{{ $price($item) }}</strong><button>Đăng ký lái thử</button></div></article>@endforeach</div><div class="a851-center"><a class="a851-btn" href="#mua-xe">Khám phá xe nổi bật <i class="fa-solid fa-arrow-right"></i></a></div></div>@include('theme-auto851::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto851_accessories')
<section id="phu-kien" class="a851-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a851-wrap"><h2 class="a851-center-title">{{ data_get($block,'data.title') }}</h2><div class="a851-accessory-grid">@foreach($items($block)->take(5) as $item)<article><h3>{{ data_get($item,'title') }}</h3><small>{{ data_get($item,'summary','Cập nhật') }}</small><img src="{{ $img($item,$assetImage('accessory-'.$loop->iteration)) }}" alt="{{ data_get($item,'title') }}"><div class="a851-card-footer"><strong>{{ $price($item) }}</strong><button>Mua hàng</button></div></article>@endforeach</div></div>@include('theme-auto851::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto851_testimonials')
<section class="a851-section a851-soft xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a851-wrap"><h2 class="a851-center-title">{{ data_get($block,'data.title') }}</h2><p class="a851-lead">{{ data_get($block,'data.description') }}</p><div class="a851-testimonials">@foreach($items($block)->take(3) as $item)<article><span>{{ mb_substr((string)data_get($item,'title',data_get($item,'name','K')),0,1) }}</span><p>“{{ data_get($item,'summary',data_get($item,'quote')) }}”</p><b>{{ data_get($item,'title',data_get($item,'name')) }}</b><small>{{ data_get($item,'role') }}</small></article>@endforeach</div></div>@include('theme-auto851::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto851_faq')
<section id="faq" class="a851-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a851-wrap a851-faq"><div><h2>{{ data_get($block,'data.title') }}</h2>@foreach($items($block) as $item)<details><summary>{{ data_get($item,'title') }}<i class="fa-solid fa-caret-right"></i></summary><p>{{ data_get($item,'summary') }}</p></details>@endforeach<a class="a851-btn" href="#lien-he">Xem thêm câu hỏi</a></div><div class="a851-faq-cars"><img src="{{ $assetImage('car-sheet') }}" alt="Showroom ô tô"><img src="{{ $assetImage('car-3') }}" alt="Dòng xe nổi bật"></div></div>@include('theme-auto851::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto851_news')
<section id="tin-tuc" class="a851-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a851-wrap"><h2 class="a851-center-title">{{ data_get($block,'data.title') }}</h2><div class="a851-news">@foreach($items($block)->take(3) as $item)<article><img src="{{ $img($item,$assetImage('car-'.(($loop->index%8)+1))) }}" alt="{{ data_get($item,'title') }}"><small>{{ data_get($item,'date',now()->format('d/m/Y')) }}</small><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p><a href="{{ data_get($item,'url','#') }}">Đọc tiếp</a></article>@endforeach</div></div>@include('theme-auto851::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto851_newsletter')
<section class="a851-newsletter xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a851-wrap"><div><h2>{{ data_get($block,'data.title') }}</h2><p>{{ data_get($block,'data.description') }}</p></div><form method="POST" action="{{ route('site.contact.submit',['locale'=>app()->getLocale()]) }}">@csrf<input type="email" name="email" required placeholder="Nhập email của bạn"><input type="hidden" name="message" value="Đăng ký nhận bản tin AUTO851"><button>Gửi</button></form></div>@include('theme-auto851::partials.edit-button',['block'=>$block])</section>
@endif @endforeach
</main>@endsection
@if($canEditLanding)
    @push('scripts')
        @include('theme-xd0302::partials.scripts')
    @endpush
@endif
