@php
  $shell=$themeShellData??$themeHomeData??[];$branding=(array)data_get($shell,'branding',data_get($siteProfile??[],'branding',[]));
  $t=fn(string $key):string=>app(\App\Core\Themes\ThemeTranslationService::class)->bladeText('E802',app()->getLocale(),$key);
  $name=trim((string)($branding['company_name']??data_get($siteProfile??[],'site_name','')))?:$t('E802.brand.default');$logo=trim((string)($branding['logo_url']??''));
  $nav=collect(data_get($shell,'top_menu',data_get($menus??[],'primary-navigation',[])))->filter(fn($item)=>is_array($item)&&filled($item['label']??null))->values();
  if($nav->isEmpty())$nav=collect([['label'=>$t('E802.nav.home'),'url'=>route('site.home')],['label'=>$t('E802.nav.about'),'url'=>'#thuong-hieu'],['label'=>$t('E802.nav.products'),'url'=>'#san-pham'],['label'=>$t('E802.nav.news'),'url'=>'#tin-tuc'],['label'=>$t('E802.nav.contact'),'url'=>route('site.contact')],['label'=>$t('E802.nav.stores'),'url'=>'#footer'],['label'=>$t('E802.nav.faq'),'url'=>route('site.contact')]]);
@endphp
<header class="e802-header"><div class="e802-top"><div class="e802-container"><span><i class="fa-solid fa-location-dot"></i> {{ data_get($branding,'support_location','Hệ thống cửa hàng') }}</span><div>@guest('customer')<button data-xd-auth-open="login"><i class="fa-solid fa-right-to-bracket"></i> {{ $t('E802.auth.login') }}</button><button data-xd-auth-open="register"><i class="fa-solid fa-user-plus"></i> {{ $t('E802.auth.register') }}</button>@else<a href="{{ route('customer.account') }}">{{ $t('E802.auth.login') }}</a>@endguest<span class="e802-social"><i class="fa-brands fa-facebook"></i><i class="fa-brands fa-youtube"></i><i class="fa-brands fa-instagram"></i></span></div></div></div><div class="e802-main e802-container"><a class="e802-logo" href="{{ route('site.home') }}">@if($logo)<img src="{{ $logo }}" alt="{{ $name }}">@else<span><i class="fa-solid fa-motorcycle"></i> {{ $name }}</span>@endif</a><button class="e802-toggle" data-e802-toggle aria-label="Menu"><i class="fa-solid fa-bars"></i></button><nav data-e802-nav>@foreach($nav as $item)<a href="{{ $item['url']??'#' }}">{{ $item['label'] }}</a>@endforeach<div class="e802-mobile-auth">@guest('customer')<button data-xd-auth-open="login">{{ $t('E802.auth.login') }}</button><button data-xd-auth-open="register">{{ $t('E802.auth.register') }}</button>@endguest</div></nav><div class="e802-icons"><a href="{{ route('site.catalog.search') }}" aria-label="{{ $t('E802.search') }}"><i class="fa-solid fa-magnifying-glass"></i></a><a href="#san-pham" aria-label="Yêu thích"><i class="fa-regular fa-heart"></i><em>0</em></a><a href="{{ route('site.cart.index') }}" aria-label="{{ $t('E802.cart') }}"><i class="fa-solid fa-bag-shopping"></i><em>{{ (int)data_get($shell,'cart_count',0) }}</em></a></div></div></header>
@include('partials.storefront-language-switcher')
