@php
    $blocks = collect($landingBlocks ?? [])->filter(fn ($block) => (bool) data_get($block, 'is_visible', true))->values();
    $byAnchor = fn (string $anchor): array => (array) ($blocks->first(fn ($block) => data_get($block, 'anchor_id') === $anchor) ?? []);
    $items = function (array $block) { $dynamic = collect(data_get($block, 'dynamic_items', []))->filter()->values(); return $dynamic->isNotEmpty() ? $dynamic : collect(data_get($block, 'data.content.items', []))->filter()->values(); };
    $hero = $byAnchor('top'); $categories = $byAnchor('danh-muc'); $popular = $byAnchor('pho-bien'); $promos = $byAnchor('uu-dai-noi-bat'); $best = $byAnchor('ban-chay'); $deals = $byAnchor('khuyen-mai'); $columns = $byAnchor('bo-suu-tap'); $newsletter = $byAnchor('nhan-tin'); $benefits = $byAnchor('cam-ket');
    $slides = collect(data_get($hero, 'dynamic_items', []))->filter()->values(); if ($slides->isEmpty()) $slides = collect(data_get($hero, 'data.content.slides', []))->filter()->values();
    $categoryItems = $items($categories); $popularItems = $items($popular); $bestItems = $items($best); $dealItems = $items($deals); $columnItems = $items($columns);
    $groupTitles = ['Sản phẩm mới', 'Mua nhiều', 'Gợi ý cho bạn'];
    $canEditLanding = auth('admin')->check() && request('mod') === 'admin' && is_array($landingPage ?? null);
    $blockUpdateUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.update', ['block' => '__BLOCK_ID__']) : '';
    $blockSourcePreviewUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.source-preview', ['block' => '__BLOCK_ID__']) : '';
    $blockPayload = $canEditLanding ? $blocks->filter(fn ($block) => filled(data_get($block, 'id')))->keyBy('id')->toArray() : [];
@endphp
@extends('theme-foot405::layout')
@section('title', data_get($landingPage ?? [], 'meta_title', data_get($siteProfile ?? [], 'site_name', 'FOOT405')))
@section('content')
<main class="f405-main">
<section class="f405-hero xd-landing-block" data-landing-block-id="{{ data_get($hero, 'id') }}" data-block-type="hero_slider">@include('theme-foot405::partials.edit-button', ['block' => $hero])<div class="f405-container"><div class="f405-slider" data-f405-slider data-f405-reveal>@forelse($slides as $index => $slide)<article class="f405-slide {{ $index === 0 ? 'is-active' : '' }}" data-f405-slide style="--slide-image:url('{{ data_get($slide, 'image', '/theme-demo/ec916/hero-mega-sale.webp') }}')"><div><small>{{ data_get($slide, 'kicker', data_get($hero, 'data.subtitle')) }}</small><h1>{{ data_get($slide, 'title', data_get($hero, 'data.title')) }}</h1><p>{{ data_get($slide, 'summary', data_get($hero, 'data.description')) }}</p><a href="{{ data_get($slide, 'link_url', '#pho-bien') }}">{{ data_get($slide, 'button_label', data_get($hero, 'data.button_label', 'Khám phá sản phẩm')) }}</a></div></article>@empty<article class="f405-slide is-active" data-f405-slide style="--slide-image:url('/theme-demo/ec916/hero-mega-sale.webp')"><div><h1>{{ data_get($hero, 'data.title', 'Ưu đãi tươi mới mỗi ngày') }}</h1><p>{{ data_get($hero, 'data.description') }}</p><a href="#pho-bien">Khám phá sản phẩm</a></div></article>@endforelse
@if($slides->count() > 1)<button type="button" data-f405-prev aria-label="Banner trước"><i class="fa-solid fa-arrow-left"></i></button><button type="button" data-f405-next aria-label="Banner sau"><i class="fa-solid fa-arrow-right"></i></button><div class="f405-slider__dots">@foreach($slides as $index => $slide)<button type="button" class="{{ $index === 0 ? 'is-active' : '' }}" data-f405-dot="{{ $index }}" aria-label="Banner {{ $index + 1 }}"></button>@endforeach</div>@endif</div></div></section>

<section class="f405-section xd-landing-block" id="danh-muc" data-landing-block-id="{{ data_get($categories, 'id') }}" data-block-type="foot405_categories">@include('theme-foot405::partials.edit-button', ['block' => $categories])<div class="f405-container"><header class="f405-heading" data-f405-reveal><h2>{{ data_get($categories, 'data.title', 'Danh mục chính') }}</h2><a href="{{ route('site.catalog.search') }}">{{ data_get($categories, 'data.button_label', 'Tất cả sản phẩm') }} <i class="fa-solid fa-angle-right"></i></a></header><div class="f405-categories">@forelse($categoryItems as $item)<a href="{{ data_get($item, 'url', '#') }}" data-f405-reveal><span><img src="{{ data_get($item, 'image', '/theme-demo/ec916/product-grocery.webp') }}" alt="{{ data_get($item, 'alt', data_get($item, 'title')) }}"></span><strong>{{ data_get($item, 'title') }}</strong></a>@empty<p>Danh mục đang được cập nhật.</p>@endforelse</div></div></section>

<section class="f405-section xd-landing-block" id="pho-bien" data-landing-block-id="{{ data_get($popular, 'id') }}" data-block-type="foot405_popular_products">@include('theme-foot405::partials.edit-button', ['block' => $popular])<div class="f405-container"><header class="f405-heading f405-heading--tabs" data-f405-reveal><h2>{{ data_get($popular, 'data.title', 'Sản phẩm phổ biến') }}</h2><div>@foreach($categoryItems->take(5) as $index => $item)<a class="{{ $index === 0 ? 'is-active' : '' }}" href="{{ data_get($item, 'url', '#') }}">{{ data_get($item, 'title') }}</a>@endforeach</div></header><div class="f405-products f405-products--four">@foreach($popularItems as $item)@include('theme-foot405::partials.product-card', ['item' => $item])@endforeach</div></div></section>

<section class="f405-section xd-landing-block" id="uu-dai-noi-bat" data-landing-block-id="{{ data_get($promos, 'id') }}" data-block-type="foot405_promo_trio">@include('theme-foot405::partials.edit-button', ['block' => $promos])<div class="f405-container f405-promo-trio">@foreach($items($promos) as $item)<a href="{{ data_get($item, 'url', '#') }}" data-f405-reveal><img src="{{ data_get($item, 'image') }}" alt="{{ data_get($item, 'title') }}"><span><strong>{{ data_get($item, 'title') }}</strong><small>{{ data_get($item, 'summary') }}</small><b>Sản phẩm <i class="fa-solid fa-arrow-right"></i></b></span></a>@endforeach</div></section>

<section class="f405-section xd-landing-block" id="ban-chay" data-landing-block-id="{{ data_get($best, 'id') }}" data-block-type="foot405_best_sellers">@include('theme-foot405::partials.edit-button', ['block' => $best])<div class="f405-container"><header class="f405-heading" data-f405-reveal><h2>{{ data_get($best, 'data.title', 'Sản phẩm bán chạy') }}</h2><a href="{{ route('site.catalog.search') }}">{{ data_get($best, 'data.button_label', 'Xem tất cả') }} <i class="fa-solid fa-angle-right"></i></a></header><div class="f405-feature-products"><a class="f405-feature-products__banner" href="{{ route('site.catalog.search') }}" data-f405-reveal style="--feature-image:url('{{ data_get($best, 'settings.feature_image', '/theme-demo/ec916/product-grocery.webp') }}')"><span><small>Chọn lựa từ thiên nhiên</small><strong>{{ data_get($best, 'data.description', 'Sản phẩm tươi ngon cho gia đình') }}</strong><b>Khám phá <i class="fa-solid fa-arrow-right"></i></b></span></a><div class="f405-products f405-products--three">@foreach($bestItems as $item)@include('theme-foot405::partials.product-card', ['item' => $item])@endforeach</div></div></div></section>

<section class="f405-section f405-section--soft xd-landing-block" id="khuyen-mai" data-landing-block-id="{{ data_get($deals, 'id') }}" data-block-type="foot405_daily_deals">@include('theme-foot405::partials.edit-button', ['block' => $deals])<div class="f405-container"><header class="f405-heading" data-f405-reveal><h2>{{ data_get($deals, 'data.title', 'Khuyến mãi trong ngày') }}</h2><a href="{{ route('site.catalog.search') }}">{{ data_get($deals, 'data.button_label', 'Xem tất cả') }} <i class="fa-solid fa-angle-right"></i></a></header><div class="f405-products f405-products--three f405-products--deals">@foreach($dealItems as $item)@include('theme-foot405::partials.product-card', ['item' => $item])@endforeach</div></div></section>

<section class="f405-section xd-landing-block" id="bo-suu-tap" data-landing-block-id="{{ data_get($columns, 'id') }}" data-block-type="foot405_product_columns">@include('theme-foot405::partials.edit-button', ['block' => $columns])<div class="f405-container f405-columns">@foreach($columnItems->chunk(3)->take(3) as $groupIndex => $group)<div><h2>{{ $groupTitles[$groupIndex] ?? 'Sản phẩm nổi bật' }}</h2>@foreach($group as $item)<article class="f405-mini-product" data-f405-reveal><a href="{{ data_get($item, 'url', '#') }}"><img src="{{ data_get($item, 'image', '/theme-demo/ec916/product-grocery.webp') }}" alt="{{ data_get($item, 'title') }}"></a><div><h3><a href="{{ data_get($item, 'url', '#') }}">{{ data_get($item, 'title') }}</a></h3><span>★★★★★</span><strong>{{ (float) data_get($item, 'price') > 0 ? number_format((float) data_get($item, 'price'), 0, ',', '.').'đ' : 'Liên hệ' }}</strong></div><a class="f405-mini-product__cart" href="{{ data_get($item, 'url', '#') }}"><i class="fa-solid fa-basket-shopping"></i></a></article>@endforeach</div>@endforeach</div></section>

<section class="f405-section xd-landing-block" id="nhan-tin" data-landing-block-id="{{ data_get($newsletter, 'id') }}" data-block-type="foot405_newsletter">@include('theme-foot405::partials.edit-button', ['block' => $newsletter])<div class="f405-container"><div class="f405-newsletter" data-f405-reveal style="--newsletter-image:url('{{ data_get($newsletter, 'settings.background_image', '/theme-demo/ec906/hero-minimart.png') }}')"><div><small>{{ data_get($newsletter, 'data.subtitle') }}</small><h2>{{ data_get($newsletter, 'data.title', 'Mua sắm tại nhà thật dễ dàng') }}</h2><p>{{ data_get($newsletter, 'data.description') }}</p><form method="post" action="{{ route('site.newsletter.subscribe') }}">@csrf<input type="email" name="email" required placeholder="Nhập email của bạn"><button type="submit">{{ data_get($newsletter, 'data.button_label', 'Đăng ký') }}</button></form></div></div></div></section>

<section class="f405-section xd-landing-block" id="cam-ket" data-landing-block-id="{{ data_get($benefits, 'id') }}" data-block-type="foot405_benefits">@include('theme-foot405::partials.edit-button', ['block' => $benefits])<div class="f405-container f405-benefits">@foreach($items($benefits) as $item)<article data-f405-reveal><i class="fa-solid {{ data_get($item, 'icon', 'fa-circle-check') }}"></i><span><strong>{{ data_get($item, 'title') }}</strong><small>{{ data_get($item, 'summary') }}</small></span></article>@endforeach</div></section>
</main>
@endsection
