<style>
.dl-pdp{background:#fcfbf7;padding-bottom:72px}
.dl-pdp-breadcrumb{display:flex;flex-wrap:wrap;align-items:center;gap:10px;padding:26px 0;font-size:12px;color:#667166;line-height:1.6}.dl-pdp-breadcrumb a{color:inherit;text-decoration:none}.dl-pdp-breadcrumb [aria-current]{color:var(--dl-forest);overflow-wrap:anywhere}
.dl-pdp-overview{display:grid;grid-template-columns:minmax(0,1.08fr) minmax(0,1fr);gap:56px;align-items:start}.dl-pdp-gallery{min-width:0}
.dl-pdp-photo{position:relative;border:1px solid #e1e5db;border-radius:20px;background:#f0f1e9;overflow:hidden;aspect-ratio:1}.dl-pdp-photo>a{display:block;height:100%;padding:24px}.dl-pdp-photo img{display:block;width:100%;height:100%;object-fit:contain}
.dl-pdp-discount{position:absolute;left:20px;top:20px;background:var(--dl-forest);color:#fff;font-size:13px;font-weight:700;border-radius:30px;padding:9px 14px}.dl-pdp-no-image{height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:22px;color:#667166}.dl-pdp-no-image i{font-size:56px}
.dl-pdp-thumbnails{display:flex;gap:12px;overflow-x:auto;padding:16px 2px 4px}.dl-pdp-thumbnails button{flex:0 0 84px;padding:6px;border:1px solid #dce1d6;border-radius:10px;background:#fff;cursor:pointer}.dl-pdp-thumbnails button[aria-pressed=true]{border:2px solid var(--dl-olive);padding:5px}.dl-pdp-thumbnails img{width:100%;height:68px;object-fit:contain;display:block}
.dl-pdp-summary{padding:8px 0;min-width:0}.dl-pdp-eyebrow{font-size:11px;font-weight:700;letter-spacing:1.8px;text-transform:uppercase;color:var(--dl-olive);margin:0 0 18px}.dl-pdp-category{display:inline-block;padding:6px 12px;border-radius:30px;background:#e9eee3;color:var(--dl-olive);font-size:12px}
.dl-pdp-summary h1{font-size:clamp(28px,3.4vw,42px);line-height:1.2;letter-spacing:-1px;color:var(--dl-forest);margin:16px 0 12px;overflow-wrap:anywhere}.dl-pdp-sku{font-size:12px;color:#6a7368;margin:0 0 24px}.dl-pdp-sku strong{font-weight:500;color:var(--dl-forest)}
.dl-pdp-price{display:flex;align-items:center;flex-wrap:wrap;gap:16px;padding:20px 0;border-top:1px solid #dfe4d8;border-bottom:1px solid #dfe4d8}.dl-pdp-price strong{font-size:clamp(28px,3vw,36px);color:var(--dl-olive);letter-spacing:-1px}.dl-pdp-price del{font-size:16px;color:#788075}
.dl-pdp-intro{color:#566151;font-size:14px;margin:22px 0}.dl-pdp-highlights{list-style:none;padding:0;display:grid;gap:12px;font-size:14px;line-height:1.6}.dl-pdp-highlights li{display:flex;gap:12px}.dl-pdp-highlights i{color:var(--dl-olive);padding-top:5px}
.dl-pdp-purchase{margin:26px 0 16px}.dl-pdp-purchase>label{display:block;font-size:12px;font-weight:600;margin-bottom:10px}.dl-pdp-buy-row{display:flex;gap:12px}.dl-pdp-quantity{display:flex;border:1px solid #cbd3c2;border-radius:8px;background:#fff;overflow:hidden;flex-shrink:0}.dl-pdp-quantity button{width:38px;background:none;border:0;font:inherit;font-size:20px;cursor:pointer}.dl-pdp-quantity input{width:42px;min-width:0;border:0;background:none;text-align:center;font:inherit;appearance:textfield;-moz-appearance:textfield}.dl-pdp-quantity input::-webkit-inner-spin-button{appearance:none}.dl-pdp-buy-row .dl-primary{justify-content:center;flex:1;margin:0;padding:17px 15px;font-size:14px}
.dl-pdp-consult{display:flex;align-items:center;gap:12px;border:1px solid #cbd3c2;border-radius:8px;padding:16px;font-size:13px;font-weight:600;color:var(--dl-forest);text-decoration:none}.dl-pdp-consult>span{margin-left:auto}.dl-pdp-help{font-size:12px;color:#6a7368;line-height:1.8;margin:14px 0 0}
.dl-pdp-information{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:64px;border-top:1px solid #dfe4d8;margin-top:64px;padding-top:48px}.dl-pdp h2{font-size:26px;line-height:1.35;letter-spacing:-.5px;color:var(--dl-forest);margin:0 0 24px}.dl-pdp-description{min-width:0}.dl-pdp-description>.dl-prose{font-size:15px;color:#53604f}.dl-pdp-description .dl-prose h2,.dl-pdp-description .dl-prose h3{font-size:21px;margin:28px 0 14px}.dl-pdp-description .dl-prose>:first-child{margin-top:0}.dl-pdp-description table{display:block;overflow-x:auto}
.dl-pdp-advice{background:var(--dl-cream);border-radius:16px;padding:28px;align-self:start}.dl-pdp-advice>i{font-size:32px;color:var(--dl-olive);margin-bottom:22px}.dl-pdp-advice h2{font-size:23px}.dl-pdp-advice p,.dl-pdp-advice details{font-size:13px;line-height:1.8;color:#586451}.dl-pdp-advice>a{display:block;color:var(--dl-forest);font-size:13px;font-weight:700;margin-top:22px;text-underline-offset:5px}.dl-pdp-advice summary{cursor:pointer;font-weight:600;margin-top:24px}.dl-pdp-advice ul{padding-left:18px}
.dl-pdp-related{margin-top:64px;padding-top:40px;border-top:1px solid #dfe4d8}.dl-pdp-section-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:24px}.dl-pdp-section-head h2{margin:0}.dl-pdp-section-head>a{color:var(--dl-olive);font-size:13px;text-underline-offset:5px}.dl-pdp-related .dl-catalog-grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.dl-pdp-related .dl-product-card{background:#fff;padding:16px}.dl-pdp-related .dl-product-card>a{height:200px}
.dl-pdp-notice{padding:16px;border:1px solid var(--dl-olive);border-radius:8px;margin-bottom:24px;line-height:1.7}.dl-pdp-notice a{color:var(--dl-forest);font-weight:700}.dl-pdp :is(a,button,input,summary):focus-visible{outline:3px solid var(--dl-olive);outline-offset:4px}.dl-pdp button:hover,.dl-pdp-consult:hover{filter:brightness(.96)}
@media(max-width:980px){.dl-pdp-overview{gap:28px}.dl-pdp-information{grid-template-columns:minmax(0,1fr) 260px;gap:32px}.dl-pdp-related .dl-catalog-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.dl-pdp-buy-row{flex-wrap:wrap}.dl-pdp-buy-row .dl-primary{flex-basis:180px}.dl-pdp-quantity{min-height:50px}}
@media(max-width:700px){.dl-pdp{padding-bottom:40px}.dl-pdp-breadcrumb{padding:20px 0;font-size:11px}.dl-pdp-overview,.dl-pdp-information{grid-template-columns:minmax(0,1fr);gap:28px}.dl-pdp-photo{border-radius:14px;aspect-ratio:1.1}.dl-pdp-photo>a{padding:18px}.dl-pdp-summary h1{font-size:30px}.dl-pdp-information{margin-top:36px;padding-top:30px}.dl-pdp-section-head{align-items:start;flex-direction:column}.dl-pdp-related{margin-top:36px}.dl-pdp-related .dl-product-card>a{height:150px}.dl-pdp-related .dl-product-card{padding:12px}.dl-pdp-related .dl-cart{font-size:12px;padding:10px;gap:6px}.dl-pdp h2{font-size:23px}}
@media(max-width:380px){.dl-pdp-related .dl-catalog-grid{grid-template-columns:1fr}}
</style>
