@php
    $shell = $themeShellData ?? $themeHomeData ?? [];
    $branding = (array) data_get($shell, 'branding', data_get($siteProfile ?? [], 'branding', []));
    $hotline = $branding['support_hotline'] ?? '';
    $email = $branding['support_email'] ?? '';
    $location = $branding['support_location'] ?? '';
    $logo = trim((string) ($branding['logo_url'] ?? ''));
    $company = trim((string) ($branding['company_name'] ?? data_get($siteProfile ?? [], 'site_name', 'Bean Construction'))) ?: 'Bean Construction';
@endphp
<footer class="x325-footer"><div class="x325-container x325-footer-card" data-x325-reveal><section><a class="x325-logo x325-footer-logo" href="#top" aria-label="{{ $company }}">@if($logo !== '')<img src="{{ $logo }}" alt="{{ $company }}">@else<i class="fa-solid fa-city"></i><span>BEAN<small>CONSTRUCTION SERVICES</small></span>@endif</a><p>Đơn vị cung cấp <b>giải pháp xây dựng và thiết bị công trình</b> uy tín, cam kết chất lượng và an toàn cho mọi dự án.</p><p><i class="fa-solid fa-location-dot"></i> {{ $location }}</p><p><i class="fa-solid fa-phone"></i> {{ $hotline }}</p><p><i class="fa-regular fa-envelope"></i> {{ $email }}</p></section><section><h3>Chính sách</h3><a href="#gioi-thieu">Giới thiệu chung</a><a href="{{ route('site.contact') }}">Liên hệ chúng tôi</a><a href="#faq">Chính sách bảo hành</a><a href="#">Chính sách bảo mật</a></section><section><h3>Dịch vụ - Dự án</h3><a href="#dich-vu">Kiến trúc xây dựng</a><a href="#dich-vu">Lắp đặt sàn gỗ</a><a href="#du-an">Dự án nhà phố</a><a href="#du-an">Dự án biệt thự</a></section><section><h3>@themeT('XD0325.footer.newsletter','Đăng ký nhận tin')</h3><p>Đăng ký ngay để nhận ưu đãi và tin mới.</p><form method="POST" action="{{ route('site.newsletter.subscribe') }}">@csrf<input type="hidden" name="source" value="xd0325-footer"><input type="email" name="email" required placeholder="Nhập địa chỉ email"><button>Đăng ký</button></form></section><div class="x325-copy">© @themeT('XD0325.footer.copyright','Bản quyền thuộc về Bean Construction') <span>Trung tâm hỗ trợ　 Điều khoản & Điều kiện</span></div></div></footer>
