@extends('theme-ec908::layout')
@section('title', data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','Ego Fitness')))
@section('content')
@php
$blocks=collect($landingBlocks??[])->values();$get=fn(string $type):array=>(array)($blocks->firstWhere('block_type',$type)??[]);
$items=function(array $block){$dynamic=collect($block['dynamic_items']??[])->filter()->values();return $dynamic->isNotEmpty()?$dynamic:collect(data_get($block,'data.content.items',[]))->filter()->values();};
$hero=$get('hero_slider');$categories=$get('ec908_category_rail');$best=$get('ec908_best_sellers');$promos=$get('ec908_promo_pair');$accessories=$get('ec908_accessory_products');$health=$get('ec908_health_posts');$benefits=$get('ec908_benefits');$footerBlock=$get('ec908_footer');
$slides=collect($hero['dynamic_items']??[])->filter()->values();if($slides->isEmpty())$slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values();
@endphp
<main class="ec98-main">
<section class="ec98-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider"><div class="ec98-container" data-ec98-slider data-autoplay="{{ data_get($hero,'settings.autoplay_ms',5500) }}">
    @forelse($slides as $index=>$slide)<article class="{{ $index===0?'is-active':'' }}" data-ec98-slide style="--hero:url('{{ data_get($slide,'image',data_get($slide,'image_url','/theme-demo/ec908/hero-fitness.png')) }}')"><div><small>{{ data_get($slide,'badge','HOT DEAL') }}</small><h1>{{ data_get($slide,'title','Bùng nổ ưu đãi') }}</h1><p>{{ data_get($slide,'summary','Quà tặng thể thao cho mọi đơn hàng') }}</p><a href="{{ data_get($slide,'link_url','#san-pham-ban-chay') }}">{{ data_get($slide,'button_label','Mua ngay') }}</a></div></article>@empty<article class="is-active" data-ec98-slide style="--hero:url('/theme-demo/ec908/hero-fitness.png')"><div><small>HOT DEAL</small><h1>Bùng nổ ưu đãi</h1><p>Giảm đến 50% sản phẩm dinh dưỡng thể thao</p></div></article>@endforelse
</div></section>
<section class="ec98-categories xd-landing-block" data-landing-block-id="{{ data_get($categories,'id') }}" data-block-type="ec908_category_rail"><div class="ec98-container"><button aria-label="Danh mục trước"><i class="fa-solid fa-angle-left"></i></button><div>@foreach($items($categories) as $item)<a href="{{ data_get($item,'url','#') }}"><span><img src="{{ data_get($item,'image',data_get($item,'image_url','/theme-demo/ec908/whey-black.png')) }}" alt="{{ data_get($item,'title') }}"></span><b>{{ data_get($item,'title') }}</b></a>@endforeach</div><button aria-label="Danh mục sau"><i class="fa-solid fa-angle-right"></i></button></div></section>
<section id="san-pham-ban-chay" class="ec98-section ec98-products-block xd-landing-block" data-landing-block-id="{{ data_get($best,'id') }}" data-block-type="ec908_best_sellers"><div class="ec98-container"><header><h2>{{ data_get($best,'data.title','Sản phẩm bán chạy') }}</h2><nav><a href="{{ route('site.home') }}">Trang chủ</a><a href="{{ route('site.catalog.search') }}">Sản phẩm</a><a href="{{ route('site.catalog.search') }}">Sản phẩm yêu thích</a><a href="{{ route('site.blog.index') }}">Tin tức</a><a href="{{ route('site.contact') }}">Liên hệ</a></nav></header><div class="ec98-product-row">@foreach($items($best) as $item)@include('theme-ec908::partials.product-card',['item'=>$item])@endforeach</div></div></section>
<section class="ec98-promos xd-landing-block" data-landing-block-id="{{ data_get($promos,'id') }}" data-block-type="ec908_promo_pair"><div class="ec98-container">@foreach($items($promos) as $index=>$item)<a href="{{ data_get($item,'url','#') }}" style="--promo:url('{{ data_get($item,'image','/theme-demo/ec908/promo-red.png') }}')"><div><small>{{ data_get($item,'badge','CÓ GÌ HOT') }}</small><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p><span>{{ data_get($item,'button_label','XEM NGAY') }} <i class="fa-solid fa-arrow-right"></i></span></div></a>@endforeach</div></section>
<section class="ec98-section ec98-accessories xd-landing-block" data-landing-block-id="{{ data_get($accessories,'id') }}" data-block-type="ec908_accessory_products"><div class="ec98-container"><h2>{{ data_get($accessories,'data.title','Phụ kiện hot') }}</h2><div class="ec98-accessory-grid"><a class="ec98-accessory-banner" href="{{ data_get($accessories,'settings.banner_url','#') }}" style="--accessory:url('{{ data_get($accessories,'settings.banner_image','/theme-demo/ec908/accessory-banner.png') }}')"><div><small>ƯU ĐÃI SIÊU TO</small><strong>GIẢM NGAY<br>250.000₫</strong><span>SHOP NOW</span></div></a><div class="ec98-accessory-products">@foreach($items($accessories) as $item)@include('theme-ec908::partials.product-card',['item'=>$item])@endforeach</div></div></div></section>
<section id="goc-suc-khoe" class="ec98-section ec98-health xd-landing-block" data-landing-block-id="{{ data_get($health,'id') }}" data-block-type="ec908_health_posts"><div class="ec98-container"><h2>{{ data_get($health,'data.title','Góc sức khỏe') }}</h2>@php($posts=$items($health))<div class="ec98-health-grid">@if($feature=$posts->first())<article class="ec98-health-feature"><a href="{{ data_get($feature,'url','#') }}"><img src="{{ data_get($feature,'image',data_get($feature,'image_url','/theme-demo/ec908/health-main.png')) }}" alt="{{ data_get($feature,'title') }}"></a><h3>{{ data_get($feature,'title') }}</h3><time>{{ data_get($feature,'date','24/08/2023') }}</time><p>{{ data_get($feature,'summary',data_get($feature,'excerpt')) }}</p></article>@endif<div class="ec98-health-list">@foreach($posts->slice(1,3)->values() as $index=>$item)<article><a class="ec98-thumb ec98-thumb-{{ $index+1 }}" href="{{ data_get($item,'url','#') }}" style="--news:url('{{ data_get($item,'image',data_get($item,'image_url','/theme-demo/ec908/health-triptych.png')) }}')"></a><div><h3>{{ data_get($item,'title') }}</h3><time>{{ data_get($item,'date','24/08/2023') }}</time><p>{{ data_get($item,'summary',data_get($item,'excerpt')) }}</p></div></article>@endforeach</div></div></div></section>
<section class="ec98-benefits xd-landing-block" data-landing-block-id="{{ data_get($benefits,'id') }}" data-block-type="ec908_benefits"><div class="ec98-container">@foreach($items($benefits) as $item)<article><i class="fa-solid {{ data_get($item,'icon','fa-award') }}"></i><div><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></div></article>@endforeach</div></section>
<section hidden class="xd-landing-block" data-landing-block-id="{{ data_get($footerBlock,'id') }}" data-block-type="ec908_footer"></section>
</main>
@endsection
