@extends('theme-shop603::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','Alena')))
@section('content')
@php
$blocks=collect($landingBlocks??[])->values();
$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null);
$editorLocales=collect(\App\Support\FrontendLocalization::supportedLocales())->map(fn($locale)=>['code'=>$locale,'label'=>strtoupper($locale)])->all();
$get=fn(string $type):array=>(array)($blocks->firstWhere('block_type',$type)??[]);
$items=fn(array $block)=>collect($block['dynamic_items']??[])->filter()->values()->whenEmpty(fn($list)=>$list->push(...collect(data_get($block,'data.content.items',[]))->filter()->values()->all()));
$image=fn($item,string $fallback)=>data_get($item,'image',data_get($item,'image_url',$fallback));
$money=fn($value)=>(float)$value>0?number_format((float)$value,0,',','.').'đ':app(\App\Core\Themes\ThemeTranslationService::class)->bladeText('SHOP603',app()->getLocale(),'SHOP603.common.contact_price');
$hero=$get('hero_slider');$quality=$get('shop603_quality_slider');$hot=$get('shop603_hot_products');$new=$get('shop603_new_arrivals');$ad=$get('shop603_single_ad');$sale=$get('shop603_sale_slider');$newsletter=$get('shop603_newsletter');$news=$get('latest_posts');$partners=$get('partner_logos');
$slides=collect($hero['dynamic_items']??[])->filter()->values();if($slides->isEmpty())$slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values();
$newItems=$items($new);$leadProduct=$newItems->shift();
$newsFallbacks=['/theme-demo/shop603/product-women-knit.png','/theme-demo/shop603/product-women-rose.png','/theme-demo/shop603/product-men-green.png'];
@endphp
<main class="s603-main">
<section class="s603-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider" data-s603-slider data-autoplay="{{ data_get($hero,'settings.autoplay_ms',6000) }}">
    @foreach($slides as $index=>$slide)<article class="s603-slide {{ $index===0?'is-active':'' }}" data-s603-slide><img src="{{ $image($slide,'/theme-demo/shop603/hero-fashion.png') }}" alt="{{ data_get($slide,'title') }}"><div class="s603-slide-overlay"><p>{{ data_get($slide,'kicker',data_get($hero,'data.subtitle')) }}</p><h1>{!! data_get($slide,'title',data_get($hero,'data.title')) !!}</h1><span>{{ data_get($slide,'summary',data_get($hero,'data.description')) }}</span><a href="{{ data_get($slide,'link_url','#san-pham-hot') }}">{{ data_get($slide,'button_label',data_get($hero,'data.button_label')) }}</a></div></article>@endforeach
    <div class="s603-dots">@foreach($slides as $index=>$slide)<button class="{{ $index===0?'is-active':'' }}" data-s603-dot="{{ $index }}" aria-label="Slide {{ $index+1 }}"></button>@endforeach</div>
</section>

<section id="{{ data_get($quality,'anchor_id','cam-ket') }}" class="s603-benefits xd-landing-block" data-landing-block-id="{{ data_get($quality,'id') }}" data-block-type="shop603_quality_slider" data-s603-carousel data-autoplay="{{ data_get($quality,'settings.autoplay_ms',3400) }}"><div class="s603-container s603-carousel-viewport"><div class="s603-benefit-track" data-s603-track>@foreach($items($quality) as $item)<article><i class="fa-solid fa-{{ data_get($item,'icon','star') }}"></i><div><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></div></article>@endforeach</div></div></section>

<section id="{{ data_get($hot,'anchor_id','san-pham-hot') }}" class="s603-section s603-cream xd-landing-block" data-landing-block-id="{{ data_get($hot,'id') }}" data-block-type="shop603_hot_products"><div class="s603-container"><header class="s603-heading"><i></i><h2>{{ data_get($hot,'data.title','Sản phẩm hot') }}</h2></header><div class="s603-products">@foreach($items($hot) as $item)@include('theme-shop603::partials.product-card',['item'=>$item])@endforeach</div></div></section>

<section id="{{ data_get($new,'anchor_id','hang-moi-ve') }}" class="s603-section xd-landing-block" data-landing-block-id="{{ data_get($new,'id') }}" data-block-type="shop603_new_arrivals"><div class="s603-container"><header class="s603-heading s603-heading-tabs"><div><i></i><h2>{{ data_get($new,'data.title','Hàng mới về') }}</h2></div><div class="s603-tabs"><button><i class="fa-solid fa-arrow-left"></i></button><b>Quần áo</b><span>Phụ kiện</span><span>Giày dép</span><span>Bé gái</span><span>Bé trai</span><button><i class="fa-solid fa-arrow-right"></i></button></div></header><div class="s603-new-grid">
@if($leadProduct)<a class="s603-lead-product" href="{{ data_get($leadProduct,'url','#') }}"><img src="{{ $image($leadProduct,'/theme-demo/shop603/product-women-knit.png') }}" alt="{{ data_get($leadProduct,'title') }}"><div><h3>{{ data_get($leadProduct,'title') }}</h3><p>{{ $money(data_get($leadProduct,'price')) }} @if((float)data_get($leadProduct,'original_price')>(float)data_get($leadProduct,'price'))<del>{{ $money(data_get($leadProduct,'original_price')) }}</del>@endif</p></div></a>@endif
<div class="s603-new-products">@foreach($newItems as $item)@include('theme-shop603::partials.product-card',['item'=>$item])@endforeach</div></div></div></section>

<section id="{{ data_get($ad,'anchor_id','banner-quang-cao') }}" class="s603-ad-section xd-landing-block" data-landing-block-id="{{ data_get($ad,'id') }}" data-block-type="shop603_single_ad"><div class="s603-container">@foreach($items($ad)->take(1) as $item)<a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,'/theme-demo/shop603/ad-lac-quan.png') }}" alt="{{ data_get($item,'title') }}"><span>{{ data_get($item,'title') }}</span></a>@endforeach</div></section>

<section id="{{ data_get($sale,'anchor_id','sale-dong-gia') }}" class="s603-section s603-sale xd-landing-block" data-landing-block-id="{{ data_get($sale,'id') }}" data-block-type="shop603_sale_slider" data-s603-carousel data-autoplay="{{ data_get($sale,'settings.autoplay_ms',3600) }}"><div class="s603-container"><header class="s603-heading"><i></i><h2>{{ data_get($sale,'data.title','Sale đồng giá - Đừng lo về giá') }}</h2></header><div class="s603-carousel-viewport"><div class="s603-sale-track" data-s603-track>@foreach($items($sale) as $item)@include('theme-shop603::partials.product-card',['item'=>$item])@endforeach</div></div></div></section>

<section id="{{ data_get($newsletter,'anchor_id','dang-ky-email') }}" class="s603-newsletter xd-landing-block" data-landing-block-id="{{ data_get($newsletter,'id') }}" data-block-type="shop603_newsletter"><div class="s603-container"><h2>{{ data_get($newsletter,'data.title') }}</h2><form method="POST" action="{{ route('site.newsletter.subscribe') }}">@csrf<input type="hidden" name="source" value="shop603-newsletter"><input type="email" name="email" required placeholder="@themeT('SHOP603.newsletter.placeholder','Nhập email của bạn')"><button>{{ data_get($newsletter,'data.button_label','Gửi') }}</button></form></div></section>

<section id="{{ data_get($news,'anchor_id','tin-tuc') }}" class="s603-section s603-cream xd-landing-block" data-landing-block-id="{{ data_get($news,'id') }}" data-block-type="latest_posts"><div class="s603-container"><header class="s603-heading"><i></i><h2>{{ data_get($news,'data.title','Tin tức thời trang') }}</h2></header><div class="s603-news-grid">@foreach($items($news) as $newsIndex=>$item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,$newsFallbacks[$newsIndex%count($newsFallbacks)]) }}" alt="{{ data_get($item,'title') }}"></a><h3><a href="{{ data_get($item,'url','#') }}">{{ data_get($item,'title') }}</a></h3><p class="s603-meta"><i class="fa-regular fa-user"></i> Alena Team <span></span><i class="fa-regular fa-clock"></i> {{ data_get($item,'published_at',now()->format('d/m/Y')) }}</p><p>{{ \Illuminate\Support\Str::limit(strip_tags((string)data_get($item,'summary')),125) }}</p><a class="s603-more" href="{{ data_get($item,'url','#') }}">@themeT('SHOP603.common.read_more','Xem thêm') <i class="fa-solid fa-arrow-right-long"></i></a></article>@endforeach</div></div></section>

<section id="{{ data_get($partners,'anchor_id','doi-tac') }}" class="s603-partners xd-landing-block" data-landing-block-id="{{ data_get($partners,'id') }}" data-block-type="partner_logos"><div class="s603-container">@foreach($items($partners) as $item)<a href="{{ data_get($item,'url',data_get($item,'href','#')) }}">@if($image($item,''))<img src="{{ $image($item,'') }}" alt="{{ data_get($item,'title',data_get($item,'name')) }}">@else<b>{{ data_get($item,'title',data_get($item,'name')) }}</b>@endif</a>@endforeach</div></section>
</main>
@endsection
