@php
  $blocks=collect($landingBlocks??[])->values();$get=fn(string $type)=>(array)($blocks->firstWhere('block_type',$type)??[]);$items=fn(array $block)=>collect($block['dynamic_items']??[])->filter()->values()->whenEmpty(fn($list)=>$list->push(...collect(data_get($block,'data.content.items',[]))->filter()->values()->all()));$image=fn($item,$fallback)=>data_get($item,'image',data_get($item,'image_url',$fallback));
  $hero=$get('hero_market');$featured=$get('e806_featured_tabs');$electronics=$get('e806_electronics');$promos=$get('e806_promo_duo');$gifts=$get('e806_gifts');$brands=$get('e806_brands');$stores=$get('e806_stores');$heroImage=data_get($hero,'media.image_url',asset('themes/E806/images/hero-appliances.png'));
@endphp
@extends('theme-e806::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','E806 Market')))
@section('content')
<main class="e806-main">
<section id="gioi-thieu" class="e806-hero-shell xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_market"><div class="e806-container e806-hero-grid"><aside id="danh-muc" class="e806-mega"><h2><i class="fa-solid fa-bars"></i> Danh mục</h2>@foreach([['fa-mobile-screen','Điện thoại'],['fa-blender','Điện gia dụng'],['fa-snowflake','Điện lạnh'],['fa-camera','Kỹ thuật số'],['fa-laptop','Laptop'],['fa-tablet-screen-button','Tablet'],['fa-print','Thiết bị văn phòng'],['fa-headphones','Tai nghe'],['fa-computer-mouse','Phụ kiện']] as [$icon,$label])<a href="#san-pham"><i class="fa-solid {{ $icon }}"></i><span>{{ $label }}</span><b>›</b></a>@endforeach<a href="#san-pham"><i class="fa-solid fa-square-plus"></i><span>Xem thêm</span></a></aside><article class="e806-hero"><img src="{{ $heroImage }}" alt="Thiết bị gia dụng hiện đại"><div><small>{{ data_get($hero,'data.subtitle','BỘ SƯU TẬP GIA DỤNG MỚI') }}</small><h1>{{ data_get($hero,'data.title','Bếp đẹp, nhà vui') }}</h1><p>{{ data_get($hero,'data.description','Thiết kế tinh tế · tiện nghi mỗi ngày') }}</p><a href="#san-pham">Khám phá ngay</a></div></article><aside class="e806-benefits"><div><i class="fa-solid fa-cart-flatbed"></i><b>Sản phẩm đa dạng</b><span>Mẫu mã phong phú</span></div><div><i class="fa-solid fa-piggy-bank"></i><b>Giá cả hợp lý</b><span>Nhiều chính sách ưu đãi</span></div><div><i class="fa-regular fa-lightbulb"></i><b>Hệ thống rộng lớn</b><span>Hỗ trợ trên toàn quốc</span></div></aside></div></section>
<section id="san-pham" class="e806-section xd-landing-block" data-landing-block-id="{{ data_get($featured,'id') }}" data-block-type="e806_featured_tabs"><div class="e806-container"><div class="e806-tabs" data-e806-tabs><button class="is-active">Sản phẩm nổi bật</button><button>Sản phẩm mới</button><button>Sản phẩm bán chạy</button></div><div class="e806-products e806-featured">@foreach($items($featured)->take(4) as $item)@include('theme-e806::partials.product-card',['item'=>$item,'compact'=>true])@endforeach</div><a class="e806-more" href="#electronics">Xem tất cả <b>›</b></a></div></section>
<section id="electronics" class="e806-section e806-soft xd-landing-block" data-landing-block-id="{{ data_get($electronics,'id') }}" data-block-type="e806_electronics"><div class="e806-container"><h2 class="e806-title">ĐIỆN TỬ & GIA DỤNG</h2><div class="e806-catalog"><aside><img src="{{ asset('themes/E806/images/tech-campaign.png') }}" alt="Khuyến mại công nghệ"><div><small>SALE ĐẶC BIỆT</small><b>Thiết bị thông minh</b><span>Ưu đãi đến 35%</span></div></aside><div class="e806-products e806-grid3">@foreach($items($electronics)->take(6) as $item)@include('theme-e806::partials.product-card',['item'=>$item,'compact'=>true])@endforeach</div><div class="e806-mini-list">@foreach($items($electronics)->slice(6,4) as $item)<a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,asset('themes/E806/images/tech-campaign.png')) }}" alt="{{ data_get($item,'title') }}"><span><b>{{ data_get($item,'title') }}</b><strong>{{ number_format((float)data_get($item,'price'),0,',','.') }}đ</strong></span></a>@endforeach</div></div></div></section>
<section class="e806-section xd-landing-block" data-landing-block-id="{{ data_get($promos,'id') }}" data-block-type="e806_promo_duo"><div class="e806-container e806-promo-duo">@foreach([['CÔNG NGHỆ MỚI','Đồng hồ thông minh','Mua ngay'],['LAPTOP MỎNG NHẸ','Ưu đãi đến 30%','Xem ngay']] as $promo)<article><img src="{{ asset('themes/E806/images/tech-campaign.png') }}" alt="{{ $promo[1] }}"><div><small>{{ $promo[0] }}</small><b>{{ $promo[1] }}</b><a href="#san-pham">{{ $promo[2] }}</a></div></article>@endforeach</div></section>
<section class="e806-section e806-gift-bg xd-landing-block" data-landing-block-id="{{ data_get($gifts,'id') }}" data-block-type="e806_gifts"><div class="e806-container e806-gifts"><header><h2>QUÀ TẶNG & PHONG CÁCH</h2><span>Nước hoa · Mỹ phẩm · Quà tặng</span></header><div class="e806-gift-body"><aside><img src="{{ asset('themes/E806/images/hero-appliances.png') }}" alt="Quà tặng"><div><b>ƯU ĐÃI PHONG CÁCH</b><span>Giảm đến 30%</span></div></aside><div class="e806-products">@foreach($items($gifts)->take(4) as $item)@include('theme-e806::partials.product-card',['item'=>$item,'compact'=>true])@endforeach</div></div></div></section>
<section class="e806-section xd-landing-block" data-landing-block-id="{{ data_get($brands,'id') }}" data-block-type="e806_brands"><div class="e806-container e806-brands">@foreach($items($brands)->take(6) as $item)<span>{{ data_get($item,'title','E806 SELECT') }}</span>@endforeach</div></section>
<section class="e806-section e806-soft xd-landing-block" data-landing-block-id="{{ data_get($stores,'id') }}" data-block-type="e806_stores"><div class="e806-container"><h2 class="e806-store-title">HỆ THỐNG CỬA HÀNG CỦA CHÚNG TÔI</h2><div class="e806-stores">@foreach($items($stores)->take(8) as $item)<article><h3>{{ data_get($item,'title') }}</h3><p><i class="fa-solid fa-location-dot"></i>{{ data_get($item,'address') }}</p><p><i class="fa-solid fa-phone"></i>{{ data_get($item,'phone','1900 6750') }}</p></article>@endforeach</div></div></section>
</main>
@endsection

