@php
  $shell=$themeShellData??$themeHomeData??[];$branding=(array)data_get($shell,'branding',data_get($siteProfile??[],'branding',[]));
  $t=fn(string $key):string=>app(\App\Core\Themes\ThemeTranslationService::class)->bladeText('E801',app()->getLocale(),$key);
  $name=trim((string)($branding['company_name']??data_get($siteProfile??[],'site_name','')))?:$t('E801.brand.default');$logo=trim((string)($branding['logo_url']??''));
  $nav=collect(data_get($shell,'top_menu',data_get($menus??[],'primary-navigation',[])))->filter(fn($item)=>is_array($item)&&filled($item['label']??null))->values();
  if($nav->isEmpty())$nav=collect([['label'=>$t('E801.nav.home'),'url'=>route('site.home')],['label'=>$t('E801.nav.products'),'url'=>route('site.catalog.search')],['label'=>$t('E801.nav.about'),'url'=>'#kinh-nghiem'],['label'=>$t('E801.nav.news'),'url'=>route('site.blog.index')],['label'=>$t('E801.nav.warranty'),'url'=>route('site.contact')],['label'=>$t('E801.nav.contact'),'url'=>route('site.contact')],['label'=>$t('E801.nav.guide'),'url'=>'#kinh-nghiem']]);
@endphp
<header class="e801-header"><div class="e801-container e801-head-main"><a class="e801-logo" href="{{ route('site.home') }}">@if($logo)<img src="{{ $logo }}" alt="{{ $name }}">@else<span>{{ $name }}</span>@endif</a><form class="e801-search" action="{{ route('site.catalog.search') }}"><input name="q" type="search" placeholder="{{ $t('E801.search.placeholder') }}"><button aria-label="Tìm kiếm"><i class="fa-solid fa-magnifying-glass"></i></button></form><button class="e801-menu-toggle" data-e801-menu-toggle aria-label="Menu"><i class="fa-solid fa-bars"></i></button><div class="e801-actions">@guest('customer')<button data-xd-auth-open="login"><i class="fa-solid fa-user"></i><span>{{ $t('E801.header.account') }}</span></button>@else<a href="{{ route('customer.account') }}"><i class="fa-solid fa-user"></i><span>{{ $t('E801.header.account') }}</span></a>@endguest<a href="#footer"><i class="fa-solid fa-location-dot"></i><span>{{ $t('E801.header.store') }}</span></a><span class="e801-language"><i class="fa-solid fa-language"></i><span>{{ $t('E801.header.language') }}</span></span><a href="#san-pham"><i class="fa-solid fa-heart"></i><em>0</em><span>{{ $t('E801.header.favorite') }}</span></a><a href="{{ route('site.cart.index') }}"><i class="fa-solid fa-basket-shopping"></i><em>{{ (int)data_get($shell,'cart_count',0) }}</em><span>{{ $t('E801.header.cart') }}</span></a></div></div><div class="e801-navrow"><nav class="e801-container" data-e801-nav>@foreach($nav as $item)<a href="{{ $item['url']??'#' }}">{{ $item['label'] }}</a>@endforeach<div class="e801-mobile-links">@guest('customer')<button data-xd-auth-open="login"><i class="fa-solid fa-user"></i> {{ $t('E801.header.account') }}</button>@else<a href="{{ route('customer.account') }}"><i class="fa-solid fa-user"></i> {{ $t('E801.header.account') }}</a>@endguest<a href="{{ route('site.cart.index') }}"><i class="fa-solid fa-basket-shopping"></i> {{ $t('E801.header.cart') }} ({{ (int)data_get($shell,'cart_count',0) }})</a></div></nav></div></header>
@include('partials.storefront-language-switcher')
