@php
  $blocks=collect($landingBlocks??[])->values();$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null);$blockUpdateUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.update',['block'=>'__BLOCK_ID__']):'';$blockSourcePreviewUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.source-preview',['block'=>'__BLOCK_ID__']):'';$blockPayload=$canEditLanding?$blocks->keyBy('id')->toArray():[];$editorLocales=collect(\App\Support\FrontendLocalization::supportedLocales())->map(fn($locale)=>['code'=>$locale,'label'=>strtoupper($locale)])->all();
  $get=fn(string $type):array=>(array)($blocks->firstWhere('block_type',$type)??[]);$items=fn(array $block)=>collect($block['dynamic_items']??[])->filter()->values()->whenEmpty(fn($list)=>$list->push(...collect(data_get($block,'data.content.items',[]))->filter()->values()->all()));$image=fn($item,string $fallback)=>data_get($item,'image',data_get($item,'image_url',$fallback));$money=fn($value)=>(float)$value>0?number_format((float)$value,0,',','.').'đ':'Liên hệ';
  $hero=$get('hero_slider');$cats=$get('e803_categories');$deals=$get('e803_deals');$campaigns=$get('e803_campaigns');$mouseFeature=$get('e803_mouse_feature');$catalog=$get('e803_catalog');$gpu=$get('e803_gpu');$build=$get('e803_build');$peripherals=$get('e803_peripherals');$promotions=$get('e803_promotions');$news=$get('e803_news');$slides=collect($hero['dynamic_items']??data_get($hero,'data.content.slides',[]));
  $card=function($item)use($image,$money){@endphp<article class="e803-product"><a class="e803-product-image" href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,asset('themes/E803/images/campaign-tech.png')) }}" alt="{{ data_get($item,'title',data_get($item,'name')) }}">@if(data_get($item,'original_price'))<span>-{{ max(1,(int)round((1-(float)data_get($item,'price')/(float)data_get($item,'original_price'))*100)) }}%</span>@endif</a><h3>{{ data_get($item,'title',data_get($item,'name')) }}</h3><small>0.0 <i class="fa-solid fa-star"></i> (0 Đánh giá)</small><div><strong>{{ $money(data_get($item,'price')) }}</strong>@if(data_get($item,'original_price'))<del>{{ $money(data_get($item,'original_price')) }}</del>@endif</div><footer><a href="{{ data_get($item,'url','#') }}"><i class="fa-solid fa-cart-shopping"></i> Thêm vào giỏ</a><button aria-label="Yêu thích"><i class="fa-regular fa-heart"></i></button></footer></article>@php };
@endphp
@extends('theme-e803::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','E803')))
@section('content')
<main>
<section id="gioi-thieu" class="e803-hero-wrap xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider"><div class="e803-container e803-hero-grid"><aside class="e803-sidecats"><h3><i class="fa-solid fa-bars"></i> Danh mục sản phẩm</h3>@foreach($items($cats)->take(9) as $item)<a href="{{ data_get($item,'url','#san-pham') }}"><i class="{{ data_get($item,'icon','fa-solid fa-desktop') }}"></i><span>{{ data_get($item,'title') }}</span><b>›</b></a>@endforeach</aside><article class="e803-hero"><img src="{{ $image($slides->first(),asset('themes/E803/images/hero-gaming.png')) }}" alt="E803 PC Gaming"><div class="e803-hero-copy"><span>{{ data_get($hero,'data.eyebrow','BỨT PHÁ HIỆU NĂNG') }}</span><h1>{{ data_get($hero,'data.title','Cỗ máy cho') }} <b>{{ data_get($hero,'data.subtitle','mọi cuộc chơi') }}</b></h1><p>{{ data_get($hero,'data.description','Khám phá hệ sinh thái PC và gaming gear được tuyển chọn cho công việc lẫn giải trí.') }}</p><a href="#deals">Khám phá ngay</a></div></article><div class="e803-mini-promos"><article><img src="{{ asset('themes/E803/images/campaign-tech.png') }}" alt="Màn hình gaming"><b>MONITOR GAMING</b><span>Quà tặng cực chất</span></article><article><img src="{{ asset('themes/E803/images/hero-gaming.png') }}" alt="Nâng cấp PC"><b>NÂNG CẤP PC</b><span>Hiệu năng bứt phá</span></article></div></div></section>

<section class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($cats,'id') }}" data-block-type="e803_categories"><div class="e803-container e803-panel"><h2>Danh mục nổi bật</h2><div class="e803-categories">@foreach($items($cats)->take(15) as $item)<a href="{{ data_get($item,'url','#san-pham') }}"><span><i class="{{ data_get($item,'icon','fa-solid fa-computer') }}"></i></span><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></div></section>

<section id="deals" class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($deals,'id') }}" data-block-type="e803_deals"><div class="e803-container e803-deal"><header><h2>⚡ GIÁ TỐT MỖI NGÀY</h2><div class="e803-countdown" data-e803-countdown><b>00</b>:<b>12</b>:<b>39</b>:<b>26</b></div></header><div class="e803-deal-tabs"><button class="is-active">Mainboard</button><button>Chuột chơi game</button><button>CPU - Bộ vi xử lý</button></div><div class="e803-products">@foreach($items($deals)->take(5) as $item){{ $card($item) }}@endforeach</div><a class="e803-more" href="#san-pham">Xem tất cả</a></div></section>

<section class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($campaigns,'id') }}" data-block-type="e803_campaigns"><div class="e803-container e803-campaigns">@foreach($items($campaigns)->take(2) as $i=>$item)<article><img src="{{ $image($item,asset('themes/E803/images/campaign-tech.png')) }}" alt="{{ data_get($item,'title') }}"><div><small>{{ $i?'CÔNG NGHỆ ĐỈNH':'SẴN SÀNG HỌC TẬP' }}</small><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary',data_get($item,'subtitle')) }}</p></div></article>@endforeach</div></section>

<section class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($mouseFeature,'id') }}" data-block-type="e803_mouse_feature"><div class="e803-container e803-feature e803-feature-dark"><div><h2>CHUỘT GAMING BÁN CHẠY NHẤT</h2><div class="e803-products">@foreach($items($mouseFeature)->take(3) as $item){{ $card($item) }}@endforeach</div><a class="e803-more" href="#san-pham">Xem thêm</a></div><aside><img src="{{ asset('themes/E803/images/hero-gaming.png') }}" alt="Gaming mouse"><b>GEAR LAB</b><span>CHÍNH XÁC TRONG TỪNG CÚ CLICK</span></aside></div></section>

<section id="san-pham" class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($catalog,'id') }}" data-block-type="e803_catalog"><div class="e803-container e803-panel"><div class="e803-filter" data-e803-tabs><h2>Chọn danh mục</h2>@foreach(['Logitech','Razer','Corsair','Pulsar','Dare U'] as $i=>$label)<button class="{{ $i===0?'is-active':'' }}" data-e803-tab>{{ $label }}</button>@endforeach</div><div class="e803-products">@foreach($items($catalog)->take(5) as $item){{ $card($item) }}@endforeach</div><a class="e803-more e803-red" href="#">Xem thêm sản phẩm</a></div></section>

<section class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($gpu,'id') }}" data-block-type="e803_gpu"><div class="e803-container e803-feature e803-feature-red"><div><h2>CARD ĐỒ HỌA</h2><div class="e803-products">@foreach($items($gpu)->take(3) as $item){{ $card($item) }}@endforeach</div><a class="e803-more" href="#">Xem thêm</a></div><aside><img src="{{ asset('themes/E803/images/campaign-tech.png') }}" alt="Card đồ họa"><b>GRAPHICS POWER</b><span>HIỆU NĂNG CHO TƯƠNG LAI</span></aside></div></section>

<section id="build-pc" class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($build,'id') }}" data-block-type="e803_build"><div class="e803-container e803-build"><img src="{{ asset('themes/E803/images/campaign-tech.png') }}" alt="Build PC"><div><small>BUILD PC CÙNG E803</small><h2>{{ data_get($build,'data.title','Cấu hình chất, quà siêu khủng') }}</h2><p>{{ data_get($build,'data.description','Đội ngũ kỹ thuật đồng hành từ lựa chọn linh kiện đến tối ưu hiệu năng.') }}</p><a href="#san-pham">Xây dựng cấu hình</a></div></div></section>

<section class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($peripherals,'id') }}" data-block-type="e803_peripherals"><div class="e803-container e803-peripherals" data-e803-tabs><div class="e803-wide-tabs">@foreach(['Bàn phím','Màn hình','Mainboard','RAM'] as $i=>$label)<button class="{{ $i===0?'is-active':'' }}" data-e803-tab>{{ $label }}</button>@endforeach</div><div class="e803-peripheral-grid"><div class="e803-peripheral-banner"><img src="{{ asset('themes/E803/images/hero-gaming.png') }}" alt="Bàn phím gaming"><h2>GEAR CHUẨN<br>CHO GAME THỦ</h2></div><div class="e803-products">@foreach($items($peripherals)->take(4) as $item){{ $card($item) }}@endforeach</div></div><a class="e803-more e803-red" href="#">Xem thêm sản phẩm</a></div></section>

<section class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($promotions,'id') }}" data-block-type="e803_promotions"><div class="e803-container e803-panel"><h2>Chuyên trang khuyến mãi</h2><div class="e803-promo-list">@foreach($items($promotions)->take(4) as $item)<article><img src="{{ $image($item,asset('themes/E803/images/campaign-tech.png')) }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title') }}</h3></article>@endforeach</div></div></section>

<section id="tin-tuc" class="e803-section xd-landing-block" data-landing-block-id="{{ data_get($news,'id') }}" data-block-type="e803_news"><div class="e803-container e803-panel"><h2>Tin tức - Review</h2><div class="e803-news">@foreach($items($news)->take(8) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,asset('themes/E803/images/hero-gaming.png')) }}" alt="{{ data_get($item,'title') }}"></a><h3>{{ data_get($item,'title') }}</h3><p>{{ \Illuminate\Support\Str::limit(strip_tags((string)data_get($item,'summary')),110) }}</p></article>@endforeach</div><a class="e803-more e803-red" href="{{ route('site.blog.index') }}">Đọc thêm bài viết</a></div></section>
</main>
@endsection
