export const adminNavigation = [
    {
        key: 'dashboard',
        label: 'Platform Dashboard',
        description: 'Tổng quan base source và sức khỏe hệ thống',
        badge: 'Core',
        color: 'cyan',
        route: '/dashboard',
        permission: 'platform.dashboard.view',
    },
    {
        key: 'module-store',
        label: 'Module Store',
        description: 'Cài đặt, bật tắt và nâng cấp module nghiệp vụ',
        badge: 'Store',
        color: 'green',
        route: '/modules',
        permission: 'store.module.view',
    },
    {
        key: 'theme-manager',
        label: 'Theme Manager',
        description: 'Quản lý loại website, preview và switch theme an toàn',
        badge: 'Theme',
        color: 'gold',
        route: '/themes',
        permission: 'theme.view',
    },
    {
        key: 'setup-wizard',
        label: 'Setup Wizard',
        description: 'Theo dõi tiến độ khởi tạo website và các bước cần hoàn thành',
        badge: 'Setup',
        color: 'purple',
        route: '/setup',
        permission: 'setup.view',
    },
    {
        key: 'access-control',
        label: 'RBAC',
        description: 'Phân quyền theo module và scope dữ liệu',
        badge: 'Access',
        color: 'blue',
        route: '/access',
        permission: 'rbac.role.view',
    },
    {
        key: 'admin-accounts',
        label: 'Admin Accounts',
        description: 'Tạo admin, khóa mở khóa và gán scope dữ liệu',
        badge: 'Admin',
        color: 'red',
        route: '/admins',
        permission: 'admin.account.view',
    },
];
