@php
  $blocks=collect($landingBlocks??[])->values();$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null);$blockUpdateUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.update',['block'=>'__BLOCK_ID__']):'';$blockSourcePreviewUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.source-preview',['block'=>'__BLOCK_ID__']):'';$blockPayload=$canEditLanding?$blocks->keyBy('id')->toArray():[];$editorLocales=collect(\App\Support\FrontendLocalization::supportedLocales())->map(fn($locale)=>['code'=>$locale,'label'=>strtoupper($locale)])->all();
  $get=fn(string $type):array=>(array)($blocks->firstWhere('block_type',$type)??[]);$items=fn(array $block)=>collect($block['dynamic_items']??[])->filter()->values()->whenEmpty(fn($list)=>$list->push(...collect(data_get($block,'data.content.items',[]))->filter()->values()->all()));$image=fn($item,string $fallback)=>data_get($item,'image',data_get($item,'image_url',$fallback));$money=fn($value)=>(float)$value>0?number_format((float)$value,0,',','.').'đ':'Liên hệ';$discount=fn($item)=>((float)data_get($item,'original_price')>(float)data_get($item,'price')&&(float)data_get($item,'original_price')>0)?round((1-(float)data_get($item,'price')/(float)data_get($item,'original_price'))*100):0;
  $hero=$get('hero_slider');$categories=$get('e801_categories');$trends=$get('e801_trends');$street=$get('e801_street_bikes');$kids=$get('e801_kids_bikes');$road=$get('e801_road_banner');$guides=$get('e801_guides');$slides=collect($hero['dynamic_items']??[])->filter()->values();if($slides->isEmpty())$slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values();
  $productCard=function($item)use($image,$money,$discount){$off=$discount($item);@endphp
    <article class="e801-product"><a class="e801-product__image" href="{{ data_get($item,'url','#') }}">@if($off)<span class="e801-badge">GIẢM<br>{{ $off }}%</span>@endif<img src="{{ $image($item,asset('themes/E801/images/hero-summer.png')) }}" alt="{{ data_get($item,'title',data_get($item,'name')) }}"></a><h3><a href="{{ data_get($item,'url','#') }}">{{ data_get($item,'title',data_get($item,'name')) }}</a></h3><strong>{{ $money(data_get($item,'price')) }}</strong>@if(data_get($item,'original_price'))<del>{{ $money(data_get($item,'original_price')) }}</del>@endif</article>
  @php };
@endphp
@extends('theme-e801::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','E801')))
@section('content')
<main class="e801-main">
  <section class="e801-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider" data-e801-slider data-autoplay="{{ data_get($hero,'settings.autoplay_ms',6500) }}">@foreach($slides as $i=>$slide)<article class="e801-hero__slide {{ $i===0?'is-active':'' }}" data-e801-slide><img src="{{ $image($slide,asset('themes/E801/images/hero-summer.png')) }}" alt="{{ data_get($slide,'title') }}"><div class="e801-container e801-hero__copy"><h1>{{ data_get($slide,'title',data_get($hero,'data.title','Đón hè năng động – Rộn ràng ưu đãi')) }}</h1><p>{{ data_get($slide,'summary',data_get($hero,'data.description','Ưu đãi mùa hè dành cho mọi hành trình')) }}</p><div class="e801-hero-deals">@foreach(data_get($slide,'deals',data_get($hero,'data.content.deals',[])) as $deal)<span>{{ data_get($deal,'title') }}<b>{{ data_get($deal,'value') }}</b></span>@endforeach</div></div></article>@endforeach<button data-e801-prev aria-label="Trước"><i class="fa-solid fa-chevron-left"></i></button><button data-e801-next aria-label="Sau"><i class="fa-solid fa-chevron-right"></i></button></section>

  <section class="e801-section xd-landing-block" data-landing-block-id="{{ data_get($categories,'id') }}" data-block-type="e801_categories"><div class="e801-container e801-categories-wrap"><div class="e801-categories">@foreach($items($categories) as $item)<a class="e801-category" href="{{ data_get($item,'url','#san-pham') }}"><i class="{{ data_get($item,'icon','fa-solid fa-bicycle') }}"></i><span>{{ data_get($item,'title') }}</span></a>@endforeach</div></div></section>

  <section class="e801-section xd-landing-block" data-landing-block-id="{{ data_get($trends,'id') }}" data-block-type="e801_trends"><div class="e801-container"><h2 class="e801-heading">{{ data_get($trends,'data.title','Sản phẩm xu hướng') }}</h2><div class="e801-trends">@foreach($items($trends) as $item)<article class="e801-trend"><img src="{{ $image($item,asset('themes/E801/images/road-banner.png')) }}" alt="{{ data_get($item,'title') }}"><div><h3>{{ data_get($item,'title') }}</h3><strong>{{ data_get($item,'price_label') }}</strong><a href="{{ data_get($item,'url','#san-pham') }}">Mua ngay</a></div></article>@endforeach</div></div></section>

  @php $streetItems=$items($street); @endphp
  <section id="san-pham" class="e801-section xd-landing-block" data-landing-block-id="{{ data_get($street,'id') }}" data-block-type="e801_street_bikes"><div class="e801-container"><h2 class="e801-heading e801-heading--blue">{{ data_get($street,'data.title','Xe đạp đường phố') }}</h2><div class="e801-showcase"><aside class="e801-brand-panel"><div class="e801-brand-panel__content"><h3>{{ data_get($street,'data.subtitle','Cả tháng tư săn deal bự') }}</h3><div class="e801-brand-grid">@foreach(data_get($street,'data.content.brands',[]) as $brand)<span>{{ $brand }}</span>@endforeach</div></div></aside><div><div class="e801-products">@foreach($streetItems->take(6) as $item){{ $productCard($item) }}@endforeach</div><a class="e801-more" href="{{ route('site.catalog.search') }}">Xem thêm sản phẩm</a></div></div></div></section>

  @php $kidsItems=$items($kids); @endphp
  <section class="e801-section xd-landing-block" data-landing-block-id="{{ data_get($kids,'id') }}" data-block-type="e801_kids_bikes"><div class="e801-container"><h2 class="e801-heading">{{ data_get($kids,'data.title','Xe đạp trẻ em') }}</h2><div class="e801-showcase e801-showcase--reverse"><div><div class="e801-products">@foreach($kidsItems->take(6) as $item){{ $productCard($item) }}@endforeach</div><a class="e801-more" href="{{ route('site.catalog.search') }}">Xem thêm sản phẩm</a></div><aside class="e801-brand-panel"><div class="e801-brand-panel__content"><h3>{{ data_get($kids,'data.subtitle','Ưu đãi xe đạp trẻ em') }}</h3><div class="e801-brand-grid">@foreach(data_get($kids,'data.content.brands',[]) as $brand)<span>{{ $brand }}</span>@endforeach</div></div></aside></div></div></section>

  <section class="e801-section xd-landing-block" data-landing-block-id="{{ data_get($road,'id') }}" data-block-type="e801_road_banner"><div class="e801-container e801-road"><img src="{{ data_get($road,'media.image',asset('themes/E801/images/road-banner.png')) }}" alt="{{ data_get($road,'data.title') }}"><div class="e801-road__copy"><h2>{{ data_get($road,'data.subtitle','Xe đạp đua') }}<b>{{ data_get($road,'data.title','ROAD') }}</b></h2><aside><strong>{{ data_get($road,'data.description','Từ 2.900.000đ') }}</strong><a href="{{ data_get($road,'settings.cta_url','#san-pham') }}">{{ data_get($road,'data.button_label','Mua ngay') }}</a></aside></div></div></section>

  @php $guideItems=$items($guides);$lead=$guideItems->first(); @endphp
  <section id="kinh-nghiem" class="e801-section xd-landing-block" data-landing-block-id="{{ data_get($guides,'id') }}" data-block-type="e801_guides"><div class="e801-container"><h2 class="e801-heading">{{ data_get($guides,'data.title','Kinh nghiệm chọn mua xe') }}</h2><div class="e801-guides"><article class="e801-guide-main">@if($lead)<div><img src="{{ $image($lead,asset('themes/E801/images/road-banner.png')) }}" alt="{{ data_get($lead,'title') }}"><h3>{{ data_get($lead,'title') }}</h3><p>{{ data_get($lead,'summary') }}</p></div>@endif<div class="e801-guide-list">@foreach($guideItems->skip(1)->take(4) as $item)<a class="e801-guide-item" href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,asset('themes/E801/images/road-banner.png')) }}" alt="{{ data_get($item,'title') }}"><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></article><aside class="e801-guide-side"><h3>{{ data_get($guides,'data.subtitle','Khuyến mãi nổi bật') }}</h3><div class="e801-guide-list">@foreach($guideItems->take(5) as $item)<a class="e801-guide-item" href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,asset('themes/E801/images/road-banner.png')) }}" alt="{{ data_get($item,'title') }}"><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></aside></div></div></section>
</main>
@endsection
