@php
$blocks=collect($landingBlocks??[])->values();
$items=function(array $b){$d=collect($b['dynamic_items']??[])->filter()->values();return $d->isNotEmpty()?$d:collect(data_get($b,'data.content.items',[]))->filter()->values();};
$img=fn($i,$f='')=>data_get($i,'image',data_get($i,'image_url',$f)); $assetImage=fn($n)=>asset('themes/AUTO852/images/'.$n.'.png');
$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null); $blockUpdateUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.update',['block'=>'__BLOCK_ID__']):''; $blockSourcePreviewUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.source-preview',['block'=>'__BLOCK_ID__']):''; $blockPayload=$canEditLanding?$blocks->filter(fn($b)=>filled($b['id']??null))->keyBy('id')->toArray():[]; $editorLocales=[];
@endphp
@extends('theme-auto852::layout')
@section('content')<main>
@foreach($blocks as $block) @php($type=data_get($block,'block_type'))
@if($type==='auto852_hero')
<section class="a852-hero xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}" style="background-image:url('{{ data_get($block,'media.image',$assetImage('hero-detailing')) }}')"><div class="a852-wrap"><div class="a852-hero-copy"><span>{{ data_get($block,'data.subtitle') }}</span><h1>{{ data_get($block,'data.title') }}</h1><p>{{ data_get($block,'data.description') }}</p><a class="a852-btn" href="#san-pham">{{ data_get($block,'data.button_label') }} <i class="fa-solid fa-arrow-right-long"></i></a><div class="a852-hero-proof"><small><i class="fa-solid fa-shield-halved"></i> An toàn mọi bề mặt</small><small><i class="fa-solid fa-droplet"></i> Hiệu quả vượt trội</small><small><i class="fa-solid fa-gem"></i> Bảo vệ dài lâu</small></div></div></div>@include('theme-auto852::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto852_services')
<section id="dich-vu" class="a852-section a852-soft xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a852-wrap"><div class="a852-heading"><span>{{ data_get($block,'data.subtitle') }}</span><h2>{{ data_get($block,'data.title') }}</h2><p>{{ data_get($block,'data.description') }}</p></div><div class="a852-services">@foreach($items($block)->take(6) as $item)<article><img src="{{ $img($item,$assetImage('service-'.$loop->iteration)) }}" alt="{{ data_get($item,'title') }}"><div><em>{{ str_pad((string)$loop->iteration,2,'0',STR_PAD_LEFT) }}</em><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p><a href="{{ data_get($item,'url','#bang-gia') }}" aria-label="Xem {{ data_get($item,'title') }}"><i class="fa-solid fa-arrow-right"></i></a></div></article>@endforeach</div><div class="a852-center"><a class="a852-btn" href="#bang-gia">Xem tất cả dịch vụ <i class="fa-solid fa-arrow-right-long"></i></a></div></div>@include('theme-auto852::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto852_process')
<section id="quy-trinh" class="a852-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a852-wrap"><div class="a852-heading"><span>{{ data_get($block,'data.subtitle') }}</span><h2>{{ data_get($block,'data.title') }}</h2><p>{{ data_get($block,'data.description') }}</p></div><div class="a852-process">@foreach($items($block)->take(5) as $item) @php($icons=['clipboard-check','comments','car-on','shield-halved','key'])<article><div class="a852-process-icon"><i class="fa-solid fa-{{ $icons[$loop->index] ?? 'check' }}"></i></div><em>{{ str_pad((string)$loop->iteration,2,'0',STR_PAD_LEFT) }}</em><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></article>@endforeach</div></div>@include('theme-auto852::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto852_promotions')
<section class="a852-section a852-promo-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a852-wrap a852-promos">@foreach($items($block)->take(2) as $item)<article style="background-image:linear-gradient(90deg,rgba(5,5,5,.92),rgba(5,5,5,.18)),url('{{ $img($item,$assetImage('service-'.($loop->iteration+1))) }}')"><small>{{ data_get($item,'eyebrow','ƯU ĐÃI ĐẶC BIỆT') }}</small><h2>{{ data_get($item,'title') }}</h2><strong>{{ data_get($item,'summary') }}</strong><a href="#bang-gia">Đặt lịch ngay <i class="fa-solid fa-arrow-right"></i></a></article>@endforeach</div>@include('theme-auto852::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto852_pricing')
<section id="bang-gia" class="a852-section a852-pricing-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a852-wrap"><div class="a852-heading"><span>{{ data_get($block,'data.subtitle') }}</span><h2>{{ data_get($block,'data.title') }}</h2><p>{{ data_get($block,'data.description') }}</p></div><div class="a852-pricing">@foreach($items($block)->take(4) as $item)<article class="{{ data_get($item,'featured')?'is-featured':'' }}">@if(data_get($item,'featured'))<b class="a852-popular">Phổ biến nhất</b>@endif<div class="a852-price-icon"><i class="fa-solid fa-{{ data_get($item,'icon','car') }}"></i></div><h3>{{ data_get($item,'title') }}</h3><strong>{{ data_get($item,'price') }}</strong><ul>@foreach((array)data_get($item,'features',[]) as $feature)<li><i class="fa-regular fa-circle-check"></i>{{ $feature }}</li>@endforeach</ul><a href="#lien-he">Đặt lịch ngay <i class="fa-solid fa-arrow-right"></i></a></article>@endforeach</div></div>@include('theme-auto852::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto852_product_banner')
<section class="a852-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a852-wrap a852-product-banner" style="background-image:url('{{ data_get($block,'media.image',$assetImage('product-banner')) }}')"><div><span>{{ data_get($block,'data.subtitle') }}</span><h2>{{ data_get($block,'data.title') }}</h2><p>{{ data_get($block,'data.description') }}</p><ul><li><i class="fa-solid fa-shield"></i> Bảo vệ tối ưu</li><li><i class="fa-solid fa-star"></i> Hiệu quả vượt trội</li><li><i class="fa-solid fa-clock-rotate-left"></i> Kéo dài tuổi thọ</li></ul><a class="a852-btn" href="#san-pham">{{ data_get($block,'data.button_label') }} <i class="fa-solid fa-arrow-right-long"></i></a></div></div>@include('theme-auto852::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto852_products')
<section id="san-pham" class="a852-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a852-wrap"><div class="a852-heading"><span>{{ data_get($block,'data.subtitle') }}</span><h2>{{ data_get($block,'data.title') }}</h2><p>{{ data_get($block,'data.description') }}</p></div><div class="a852-category-rail">@foreach(['Ngoại thất','Nội thất','Khoang máy','Phụ kiện & dụng cụ','Lốp & mâm','Chăm sóc kính'] as $category)<span class="{{ $loop->first?'is-active':'' }}"><i class="fa-solid fa-{{ ['spray-can-sparkles','couch','gears','screwdriver-wrench','compact-disc','car-side'][$loop->index] }}"></i>{{ $category }}</span>@endforeach</div><div class="a852-products">@foreach($items($block)->take(10) as $item) @include('theme-auto852::partials.product-card',['item'=>$item]) @endforeach</div><div class="a852-center"><a class="a852-btn" href="{{ route('site.catalog.search',['locale'=>app()->getLocale()]) }}">Xem thêm sản phẩm <i class="fa-solid fa-arrow-right-long"></i></a></div></div>@include('theme-auto852::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto852_news')
<section id="tin-tuc" class="a852-section a852-soft xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a852-wrap"><div class="a852-heading"><span>{{ data_get($block,'data.subtitle') }}</span><h2>{{ data_get($block,'data.title') }}</h2><p>{{ data_get($block,'data.description') }}</p></div>@php($news=$items($block)->take(4))<div class="a852-news">@if($featured=$news->first())<article class="a852-news-featured" style="background-image:linear-gradient(0deg,rgba(0,0,0,.88),rgba(0,0,0,.05)),url('{{ $img($featured,$assetImage('service-2')) }}')"><div><h3>{{ data_get($featured,'title') }}</h3><p>{{ data_get($featured,'summary') }}</p><small><i class="fa-regular fa-calendar"></i> {{ data_get($featured,'date',now()->format('d/m/Y')) }}</small><a href="{{ data_get($featured,'url','#') }}">Đọc tiếp <i class="fa-solid fa-arrow-right"></i></a></div></article>@endif<div class="a852-news-list">@foreach($news->slice(1) as $item)<article><img src="{{ $img($item,$assetImage('service-'.($loop->iteration+2))) }}" alt="{{ data_get($item,'title') }}"><div><h3>{{ data_get($item,'title') }}</h3><small><i class="fa-regular fa-calendar"></i> {{ data_get($item,'date',now()->format('d/m/Y')) }}</small><a href="{{ data_get($item,'url','#') }}"><i class="fa-solid fa-arrow-right"></i></a></div></article>@endforeach</div></div><div class="a852-center"><a class="a852-btn" href="{{ route('site.blog.index',['locale'=>app()->getLocale()]) }}">Xem tất cả tin tức <i class="fa-solid fa-arrow-right-long"></i></a></div></div>@include('theme-auto852::partials.edit-button',['block'=>$block])</section>
@endif @endforeach
</main>@endsection
@if($canEditLanding)
    @push('scripts')
        @include('theme-xd0302::partials.scripts')
    @endpush
@endif
