<script>
document.addEventListener('DOMContentLoaded',()=>{
 const menu=document.querySelector('[data-s606-menu]'),nav=document.querySelector('[data-s606-nav]');menu?.addEventListener('click',()=>nav?.classList.toggle('is-open'));
 const searchForm=document.querySelector('[data-s606-search-form]');document.querySelector('[data-s606-search]')?.addEventListener('click',()=>{searchForm?.classList.toggle('is-open');searchForm?.querySelector('input')?.focus()});
 document.querySelectorAll('[data-s606-slider]').forEach(slider=>{const slides=[...slider.querySelectorAll('.s606-slide')];let index=0;if(slides.length<2)return;const show=next=>{slides[index].classList.remove('is-active');index=(next+slides.length)%slides.length;slides[index].classList.add('is-active')};slider.querySelector('[data-s606-prev]')?.addEventListener('click',()=>show(index-1));slider.querySelector('[data-s606-next]')?.addEventListener('click',()=>show(index+1));setInterval(()=>show(index+1),Number(slider.dataset.delay)||5600)});
 document.querySelectorAll('[data-s606-countdown]').forEach(clock=>{let remaining=Math.max(1,Number(clock.dataset.s606Countdown)||24)*3600;const paint=()=>{clock.querySelector('[data-hours]').textContent=String(Math.floor(remaining/3600)).padStart(2,'0');clock.querySelector('[data-minutes]').textContent=String(Math.floor((remaining%3600)/60)).padStart(2,'0');clock.querySelector('[data-seconds]').textContent=String(remaining%60).padStart(2,'0');remaining=remaining>0?remaining-1:0};paint();setInterval(paint,1000)});
 const reveal=[...document.querySelectorAll('.s606-section,.s606-benefits,.s606-campaign')];reveal.forEach((node,index)=>{node.dataset.s606Reveal='';node.style.transitionDelay=`${Math.min(index%3,2)*60}ms`});if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -35px'});reveal.forEach(node=>observer.observe(node))}else reveal.forEach(node=>node.classList.add('is-visible'));
});
</script>
