@php
  $shell=$themeShellData??$themeHomeData??[];$branding=(array)data_get($shell,'branding',data_get($siteProfile??[],'branding',[]));
  $t=fn(string $key):string=>app(\App\Core\Themes\ThemeTranslationService::class)->bladeText('AUTO853',app()->getLocale(),$key);
  $name=trim((string)($branding['company_name']??data_get($siteProfile??[],'site_name','')))?:$t('AUTO853.brand.default');$logo=trim((string)($branding['logo_url']??''));
  $nav=collect(data_get($shell,'top_menu',data_get($menus??[],'primary-navigation',[])))->filter(fn($item)=>is_array($item)&&filled($item['label']??null))->values();
  if($nav->isEmpty())$nav=collect([['label'=>$t('AUTO853.nav.home'),'url'=>route('site.home')],['label'=>$t('AUTO853.nav.bikes'),'url'=>'#danh-muc'],['label'=>$t('AUTO853.nav.parts'),'url'=>'#bikepacking'],['label'=>$t('AUTO853.nav.sale'),'url'=>'#flash-sale'],['label'=>$t('AUTO853.nav.rental'),'url'=>route('site.contact')],['label'=>$t('AUTO853.nav.guide'),'url'=>'#tin-tuc']]);
@endphp
<header class="a853-header"><div class="a853-wrap a853-navrow"><a class="a853-logo" href="{{ route('site.home') }}">@if($logo)<img src="{{ $logo }}" alt="{{ $name }}">@else<span class="a853-logo-mark"><i class="fa-solid fa-bicycle"></i></span><span><b>{{ $name }}</b><small>RIDE SINCE 1991</small></span>@endif</a><button class="a853-menu" data-a853-menu aria-label="Mở menu"><i class="fa-solid fa-bars"></i></button><nav data-a853-nav>@foreach($nav as $item)<a href="{{ $item['url']??'#' }}">{{ $item['label'] }}</a>@endforeach</nav><div class="a853-actions"><button class="a853-search-toggle" aria-label="Tìm kiếm"><i class="fa-solid fa-magnifying-glass"></i></button>@guest('customer')<button data-xd-auth-open="login" aria-label="{{ $t('AUTO853.header.account') }}"><i class="fa-regular fa-user"></i></button>@else<a href="{{ route('customer.account') }}" aria-label="{{ $t('AUTO853.header.account') }}"><i class="fa-regular fa-user"></i></a>@endguest<a href="{{ route('site.cart.index') }}" aria-label="{{ $t('AUTO853.header.cart') }}"><i class="fa-solid fa-cart-shopping"></i><em>{{ (int)data_get($shell,'cart_count',0) }}</em></a></div></div></header>
@include('partials.storefront-language-switcher')
