@php
    $blocks = collect($landingBlocks ?? [])->values();
    $items = function (array $block) { $dynamic = collect($block['dynamic_items'] ?? [])->filter()->values(); return $dynamic->isNotEmpty() ? $dynamic : collect(data_get($block, 'data.content.items', []))->filter()->values(); };
    $image = fn ($item, string $fallback = '') => data_get($item, 'image', data_get($item, 'image_url', $fallback));
    $assetImage = fn (string $name) => asset('themes/AUTO850/images/'.$name.'.png');
    $formatPrice = fn ($item) => (float) data_get($item, 'price') > 0 ? number_format((float) data_get($item, 'price'), 0, ',', '.').'đ' : app(\App\Core\Themes\ThemeTranslationService::class)->bladeText('AUTO850', app()->getLocale(), 'price.contact', 'Liên hệ');
    $canEditLanding = auth('admin')->check() && request('mod') === 'admin' && is_array($landingPage ?? null);
    $blockUpdateUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.update', ['block' => '__BLOCK_ID__']) : '';
    $blockSourcePreviewUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.source-preview', ['block' => '__BLOCK_ID__']) : '';
    $blockPayload = $canEditLanding ? $blocks->filter(fn (array $block): bool => filled($block['id'] ?? null))->keyBy('id')->toArray() : [];
    $editorLocales = $canEditLanding ? collect(\App\Support\FrontendLocalization::localeOptions())->filter(fn (array $locale): bool => (bool) ($locale['is_active'] ?? false))->map(fn (array $locale): array => ['code' => (string) $locale['code'], 'label' => (string) (($locale['native_name'] ?? null) ?: $locale['name'])])->values()->all() : [];
@endphp
@extends('theme-auto850::layout')
@section('content')<main>
@foreach($blocks as $block) @php($type = data_get($block, 'block_type'))
@if($type === 'auto850_hero')
<section class="a850-hero xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}" style="background-image:url('{{ data_get($block, 'media.image', $assetImage('hero-service')) }}')"><div class="a850-hero-shape"></div><div class="a850-wrap"><div class="a850-hero-copy a850-reveal"><span>{{ data_get($block, 'data.subtitle') }}</span><h1>{{ data_get($block, 'data.title') }}</h1><p>{{ data_get($block, 'data.description') }}</p><a class="a850-btn" href="#dat-lich">{{ data_get($block, 'data.button_label') }} <i class="fa-solid fa-arrow-right"></i></a></div></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif($type === 'auto850_brands')
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-brands xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-brand-title"><h2>{{ data_get($block, 'data.title') }}</h2><p>Những thương hiệu được khách hàng tin chọn</p></div><div class="a850-brand-list">@foreach($items($block)->take(6) as $item)<a href="{{ data_get($item, 'url', '#') }}">@if($image($item))<img src="{{ $image($item) }}" alt="{{ data_get($item, 'title') }}">@else<span>{{ data_get($item, 'title') }}</span>@endif</a>@endforeach</div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif($type === 'auto850_about')
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-wrap a850-about"><div class="a850-about-media"><img src="{{ data_get($block, 'media.image', $assetImage('service-strip')) }}" alt="{{ data_get($block, 'data.title') }}"></div><div class="a850-about-copy">@include('theme-auto850::partials.heading', ['block' => $block])<p>{{ data_get($block, 'data.description') }}</p><div class="a850-about-tabs">@foreach($items($block)->take(3) as $item)<article><i class="fa-solid fa-circle-check"></i><div><b>{{ data_get($item, 'title') }}</b><small>{{ data_get($item, 'summary') }}</small></div></article>@endforeach</div><a class="a850-btn" href="#dich-vu">{{ data_get($block, 'data.button_label') }} <i class="fa-solid fa-arrow-right"></i></a></div></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif($type === 'auto850_categories')
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-section a850-soft xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-wrap">@include('theme-auto850::partials.heading', ['block' => $block, 'center' => true])<div class="a850-category-grid">@foreach($items($block)->take(6) as $item)<a class="a850-category a850-reveal" href="{{ data_get($item, 'url', '#san-pham') }}"><div><img src="{{ $image($item, $assetImage('accessory-'.(($loop->index % 6)+1))) }}" alt="{{ data_get($item, 'title') }}"></div><span><h3>{{ data_get($item, 'title') }}</h3><p>{{ data_get($item, 'summary') }}</p><b>Xem tất cả <i class="fa-solid fa-arrow-right"></i></b></span></a>@endforeach</div></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif(in_array($type, ['auto850_deals','auto850_featured_products'], true))
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-section {{ $type === 'auto850_deals' ? 'a850-deals' : '' }} xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-wrap">@include('theme-auto850::partials.heading', ['block' => $block, 'center' => true])@if($type === 'auto850_deals')<div class="a850-countdown" data-a850-countdown="{{ (int) data_get($block, 'settings.countdown_hours', 48) }}"><span><b data-days>02</b>Ngày</span><i>:</i><span><b data-hours>00</b>Giờ</span><i>:</i><span><b data-minutes>00</b>Phút</span><i>:</i><span><b data-seconds>00</b>Giây</span></div>@endif<div class="a850-product-grid">@foreach($items($block)->take($type === 'auto850_deals' ? 5 : 6) as $item)@include('theme-auto850::partials.product-card', ['item' => $item])@endforeach</div><div class="a850-center"><a class="a850-btn" href="#san-pham">@themeT('view_all', 'Xem tất cả') <i class="fa-solid fa-arrow-right"></i></a></div></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif($type === 'auto850_services')
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-wrap">@include('theme-auto850::partials.heading', ['block' => $block, 'center' => true])<div class="a850-service-grid">@foreach($items($block)->take(4) as $item)<article class="a850-service a850-reveal"><span>{{ sprintf('%02d', $loop->iteration) }}</span><img src="{{ $image($item, $assetImage('service-'.$loop->iteration)) }}" alt="{{ data_get($item, 'title') }}"><div><i class="fa-solid {{ ['fa-screwdriver-wrench','fa-car-burst','fa-gears','fa-gauge-high'][$loop->index] ?? 'fa-wrench' }}"></i><h3>{{ data_get($item, 'title') }}</h3><p>{{ data_get($item, 'summary') }}</p><a href="{{ data_get($item, 'url', '#dat-lich') }}">Xem chi tiết <i class="fa-solid fa-arrow-right"></i></a></div></article>@endforeach</div></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif($type === 'auto850_process')
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-section a850-soft xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-wrap">@include('theme-auto850::partials.heading', ['block' => $block, 'center' => true])<div class="a850-process">@foreach($items($block)->take(4) as $item)<article><div><img src="{{ $image($item, $assetImage('service-'.$loop->iteration)) }}" alt="{{ data_get($item, 'title') }}"><b>{{ $loop->iteration }}</b></div><h3>{{ data_get($item, 'title') }}</h3><p>{{ data_get($item, 'summary') }}</p></article>@endforeach</div></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif($type === 'auto850_testimonials')
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-section a850-testimonials xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-wrap">@include('theme-auto850::partials.heading', ['block' => $block, 'center' => true])<div class="a850-testimonial-grid">@foreach($items($block)->take(3) as $item)<article><div class="a850-stars">★★★★★</div><p>“{{ data_get($item, 'summary', data_get($item, 'quote')) }}”</p><div><span>{{ mb_substr((string) data_get($item, 'title', data_get($item, 'name', 'K')), 0, 1) }}</span><b>{{ data_get($item, 'title', data_get($item, 'name')) }}<small>{{ data_get($item, 'role') }}</small></b></div></article>@endforeach</div></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif($type === 'auto850_news')
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-wrap">@include('theme-auto850::partials.heading', ['block' => $block, 'center' => true])<div class="a850-news-grid">@foreach($items($block)->take(4) as $item)<article><a href="{{ data_get($item, 'url', '#') }}"><img src="{{ $image($item, $assetImage('service-'.$loop->iteration)) }}" alt="{{ data_get($item, 'title') }}"></a><time>{{ data_get($item, 'date', now()->format('d.m.Y')) }}</time><h3>{{ data_get($item, 'title') }}</h3><p>{{ data_get($item, 'summary') }}</p><a href="{{ data_get($item, 'url', '#') }}">@themeT('read_more', 'Đọc tiếp') <i class="fa-solid fa-arrow-right"></i></a></article>@endforeach</div></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif($type === 'auto850_faq')
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-section a850-soft xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-wrap a850-faq-layout"><div>@include('theme-auto850::partials.heading', ['block' => $block])@foreach($items($block) as $item)<details class="a850-faq"><summary>{{ data_get($item, 'title') }}<i class="fa-solid fa-chevron-down"></i></summary><p>{{ data_get($item, 'summary') }}</p></details>@endforeach</div><img src="{{ data_get($block, 'media.image', $assetImage('hero-service')) }}" alt="{{ data_get($block, 'data.title') }}"></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@elseif($type === 'auto850_booking')
<section id="{{ data_get($block, 'anchor_id') }}" class="a850-section a850-booking xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block, 'id') }}"><div class="a850-wrap a850-booking-grid"><div class="a850-booking-media" style="background-image:url('{{ data_get($block, 'media.image', $assetImage('service-1')) }}')"></div><div>@include('theme-auto850::partials.heading', ['block' => $block])<p>{{ data_get($block, 'data.description') }}</p><form method="POST" action="{{ route('site.contact.submit', ['locale' => app()->getLocale()]) }}">@csrf<div><input name="name" required placeholder="Họ và tên"><input name="email" type="email" placeholder="Email"></div><div><input name="phone" required placeholder="Số điện thoại"><input name="subject" type="date"></div><textarea name="message" rows="3" placeholder="Dịch vụ quan tâm"></textarea><button class="a850-btn">{{ data_get($block, 'data.button_label') }} <i class="fa-solid fa-arrow-right"></i></button></form></div></div>@include('theme-auto850::partials.edit-button', ['block' => $block])</section>
@endif @endforeach
</main>@endsection
@if($canEditLanding)@push('scripts')@include('theme-xd0302::partials.scripts')@endpush @endif
