@extends('theme-ec907::layout')
@section('title', data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','EGA Gear')))
@section('content')
@php
$blocks=collect($landingBlocks??[])->values();$get=fn(string $type):array=>(array)($blocks->firstWhere('block_type',$type)??[]);
$items=function(array $block){$dynamic=collect($block['dynamic_items']??[])->filter()->values();return $dynamic->isNotEmpty()?$dynamic:collect(data_get($block,'data.content.items',[]))->filter()->values();};
$hero=$get('hero_slider');$benefits=$get('ec907_benefits');$categories=$get('ec907_category_grid');$best=$get('ec907_best_sellers');$campaigns=$get('ec907_campaign_cards');$audio=$get('ec907_audio_showcase');$gaming=$get('ec907_gaming_products');$brands=$get('ec907_brand_strip');$news=$get('ec907_tech_news');$newsletter=$get('ec907_newsletter');
$slides=collect($hero['dynamic_items']??[])->filter()->values();if($slides->isEmpty())$slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values();$promos=collect(data_get($hero,'data.content.promos',[]));
@endphp
<main class="ec97-main">
<section id="khuyen-mai" class="ec97-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider"><div class="ec97-container ec97-hero-grid">
    <div class="ec97-hero-main" data-ec97-slider data-autoplay="{{ data_get($hero,'settings.autoplay_ms',5200) }}">@forelse($slides as $index=>$slide)<article class="{{ $index===0?'is-active':'' }}" data-ec97-slide style="--bg:url('{{ data_get($slide,'image',data_get($slide,'image_url','/theme-demo/ec907/hero-gear.png')) }}')"><div><small>{{ data_get($slide,'badge','GEAR GIÁ SỐC') }}</small><h1>{{ data_get($slide,'title',data_get($hero,'data.title','Gear giá sốc')) }}</h1><p>{{ data_get($slide,'summary','Giao siêu tốc · Giảm đến 45%') }}</p><a href="{{ data_get($slide,'link_url','#san-pham-ban-chay') }}">{{ data_get($slide,'button_label','Xem ngay') }}</a></div></article>@empty<article class="is-active" data-ec97-slide style="--bg:url('/theme-demo/ec907/hero-gear.png')"><div><small>GEAR GIÁ SỐC</small><h1>Giao siêu tốc</h1><p>Giảm giá cực sốc đến 45%</p></div></article>@endforelse</div>
    <aside>@foreach($promos as $index=>$promo)<a class="ec97-mini-promo ec97-mini-{{ $index+1 }}" href="{{ data_get($promo,'url','#') }}"><div><h3>{{ data_get($promo,'title') }}</h3><p>{{ data_get($promo,'summary') }}</p><small>Giá chỉ từ</small><strong>{{ data_get($promo,'price') }}</strong><span>XEM NGAY</span></div><img src="{{ data_get($promo,'image','/theme-demo/ec907/laptop.webp') }}" alt="{{ data_get($promo,'title') }}"></a>@endforeach</aside>
</div></section>
<section id="dich-vu" class="ec97-benefits xd-landing-block" data-landing-block-id="{{ data_get($benefits,'id') }}" data-block-type="ec907_benefits"><div class="ec97-container">@foreach($items($benefits) as $item)<article><i class="fa-solid {{ data_get($item,'icon','fa-truck-fast') }}"></i><div><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></div></article>@endforeach</div></section>
<div class="ec97-soft">
<section class="ec97-section ec97-categories xd-landing-block" data-landing-block-id="{{ data_get($categories,'id') }}" data-block-type="ec907_category_grid"><div class="ec97-container">@foreach($items($categories) as $item)<a href="{{ data_get($item,'url','#') }}"><span><img src="{{ data_get($item,'image',data_get($item,'image_url','/theme-demo/ec907/keyboard-white.png')) }}" alt="{{ data_get($item,'title') }}"></span><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></section>
<section id="san-pham-ban-chay" class="ec97-section xd-landing-block" data-landing-block-id="{{ data_get($best,'id') }}" data-block-type="ec907_best_sellers"><div class="ec97-container"><header class="ec97-section-head"><h2>{{ data_get($best,'data.title','Sản phẩm bán chạy') }}</h2><nav>Bàn phím <i>•</i> Chuột + Lót chuột <i>•</i> Phụ kiện</nav><a href="{{ route('site.catalog.search') }}">Xem thêm <i class="fa-solid fa-angle-right"></i></a></header><div class="ec97-product-row">@foreach($items($best) as $item)@include('theme-ec907::partials.product-card',['item'=>$item])@endforeach</div></div></section>
<section class="ec97-section ec97-campaigns xd-landing-block" data-landing-block-id="{{ data_get($campaigns,'id') }}" data-block-type="ec907_campaign_cards"><div class="ec97-container">@foreach($items($campaigns) as $index=>$item)<a class="ec97-campaign ec97-campaign-{{ $index+1 }}" href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','/theme-demo/ec907/campaign-gaming.png') }}" alt="{{ data_get($item,'title') }}"><div><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p><span><i class="fa-solid fa-angle-right"></i></span></div></a>@endforeach</div></section>
<section class="ec97-section ec97-audio xd-landing-block" data-landing-block-id="{{ data_get($audio,'id') }}" data-block-type="ec907_audio_showcase"><div class="ec97-container">@php($audioItems=$items($audio))<div class="ec97-audio-grid"><div class="ec97-audio-side">@foreach($audioItems->take(4) as $item)@include('theme-ec907::partials.product-card',['item'=>$item])@endforeach</div>@if($feature=$audioItems->get(4))<article class="ec97-audio-feature"><img src="{{ data_get($feature,'image',data_get($feature,'image_url','/theme-demo/ec907/headset-black.png')) }}" alt="{{ data_get($feature,'title') }}"><h3>{{ data_get($feature,'title') }}</h3><strong>{{ number_format((int)data_get($feature,'price'),0,',','.') }}₫</strong><a href="{{ data_get($feature,'url','#') }}">Thêm vào giỏ</a></article>@endif<div class="ec97-audio-side">@foreach($audioItems->slice(5,4) as $item)@include('theme-ec907::partials.product-card',['item'=>$item])@endforeach</div></div></div></section>
<section class="ec97-section xd-landing-block" data-landing-block-id="{{ data_get($gaming,'id') }}" data-block-type="ec907_gaming_products"><div class="ec97-container"><header class="ec97-section-head"><h2>{{ data_get($gaming,'data.title','Phụ kiện chơi game') }}</h2><nav>Máy chơi game <i>•</i> Bàn phím <i>•</i> Chuột</nav><a href="{{ route('site.catalog.search') }}">Xem thêm <i class="fa-solid fa-angle-right"></i></a></header><div class="ec97-gaming-row">@foreach($items($gaming) as $item)@include('theme-ec907::partials.product-card',['item'=>$item])@endforeach</div></div></section>
<section class="ec97-brands xd-landing-block" data-landing-block-id="{{ data_get($brands,'id') }}" data-block-type="ec907_brand_strip"><div class="ec97-container">@foreach($items($brands) as $item)<b>{{ data_get($item,'title') }}</b>@endforeach</div></section>
<section id="tin-tuc" class="ec97-section ec97-news xd-landing-block" data-landing-block-id="{{ data_get($news,'id') }}" data-block-type="ec907_tech_news"><div class="ec97-container"><header class="ec97-section-head"><h2>{{ data_get($news,'data.title','Bản tin công nghệ') }}</h2><nav>24 Công nghệ</nav><a href="{{ route('site.blog.index') }}">Xem thêm <i class="fa-solid fa-angle-right"></i></a></header><div class="ec97-news-grid">@foreach($items($news) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image',data_get($item,'image_url','/theme-demo/ec907/news-tv.webp')) }}" alt="{{ data_get($item,'title') }}"></a><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary',data_get($item,'excerpt')) }}</p><footer><time><i class="fa-regular fa-calendar"></i> {{ data_get($item,'date','18/12/2023') }}</time><a href="{{ data_get($item,'url','#') }}">Xem chi tiết</a></footer></article>@endforeach</div></div></section>
<section hidden class="xd-landing-block" data-landing-block-id="{{ data_get($newsletter,'id') }}" data-block-type="ec907_newsletter"></section>
</div></main>
@endsection
