<?php

use App\Core\Modules\ModuleManager;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Modules\FnbPos\Domain\FnbContext;
use Modules\FnbPos\Services\FnbCompensationService;
use Modules\FnbPos\Services\FnbConfigurationService;
use Modules\FnbPos\Services\FnbReceiptService;
use Modules\FnbPos\Services\FnbRecipeService;
use Modules\FnbPos\Services\FnbService;

/** Isolated local MySQL gate. Only the database generated by this process is removed. */
require dirname(__DIR__, 2).'/vendor/autoload.php';
$application = require dirname(__DIR__, 2).'/bootstrap/app.php';
$application->make(Kernel::class)->bootstrap();

$originalConnection = config('database.default');
$originalConfig = config('database.connections.'.$originalConnection);
if (($originalConfig['driver'] ?? null) !== 'mysql') {
    throw new RuntimeException('This gate requires the configured local MySQL connection.');
}
$databaseName = 'aio_fnb_smoke_'.bin2hex(random_bytes(6));
$created = false;
$passed = false;
try {
    DB::connection($originalConnection)->statement('CREATE DATABASE `'.$databaseName.'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
    $created = true;
    config(['database.connections.fnb_smoke' => array_replace($originalConfig, ['database' => $databaseName, 'url' => null])]);
    DB::setDefaultConnection('fnb_smoke');
    // Preserve the existing-core deployment boundary without copying a single user row.
    // The legacy core fresh-MySQL path separately fails on the 2026-07-17 CMS ALTER.
    DB::statement('SET FOREIGN_KEY_CHECKS=0');
    foreach (['admins', 'roles', 'permissions', 'admin_role_assignments', 'permission_role', 'module_installations', 'sites', 'audit_logs', 'audit_log_chain_heads'] as $table) {
        $definition = (array) DB::connection($originalConnection)->selectOne('SHOW CREATE TABLE `'.$table.'`');
        DB::statement($definition['Create Table']);
    }
    DB::statement('SET FOREIGN_KEY_CHECKS=1');
    if (Artisan::call('migrate', ['--path' => 'database/migrations/2026_09_05_000001_create_module_lifecycle_security_tables.php', '--force' => true, '--no-interaction' => true]) !== 0) {
        throw new RuntimeException('Core lifecycle migration failed: '.Artisan::output());
    }
    if (Schema::hasTable('fnb_outlets')) {
        throw new RuntimeException('Core migrations incorrectly created F&B tables.');
    }
    $manager = app(ModuleManager::class);
    $manager->install('fnb-pos');
    $manager->enable('fnb-pos');
    $manager->disable('fnb-pos');
    $manager->enable('fnb-pos');
    $foreignKeys = DB::table('information_schema.table_constraints')->where('constraint_schema', $databaseName)->where('constraint_type', 'FOREIGN KEY')->where('table_name', 'like', 'fnb_%')->count();
    if (! Schema::hasTable('fnb_checks') || $foreignKeys !== 170) {
        throw new RuntimeException("F&B schema composite-FK count changed: expected 170, got {$foreignKeys}.");
    }
    if (DB::table('permissions')->where('module_key', 'fnb-pos')->where('is_active', true)->count() !== 53) {
        throw new RuntimeException('Unexpected installed security map.');
    }
    if (DB::table('module_lifecycle_operations')->where('module_key', 'fnb-pos')->whereNotNull('active_slot')->exists()) {
        throw new RuntimeException('Lifecycle left a nonterminal operation after success.');
    }

    $now = now();
    DB::table('admins')->insert([
        'id' => 1,
        'name' => 'F&B MySQL Smoke Owner',
        'username' => 'fnb.mysql.smoke',
        'email' => 'fnb-mysql-smoke@example.invalid',
        'password' => password_hash(bin2hex(random_bytes(24)), PASSWORD_BCRYPT),
        'is_active' => true,
        'status' => 'active',
        'is_system_owner' => true,
        'must_change_password' => false,
        'auth_version' => 1,
        'created_at' => $now,
        'updated_at' => $now,
    ]);
    DB::table('sites')->insert([
        'website_key' => 'fnb-smoke',
        'domain' => null,
        'name' => 'F&B MySQL Smoke',
        'status' => 'active',
        'settings' => null,
        'created_at' => $now,
        'updated_at' => $now,
    ]);

    $fnb = app(FnbService::class);
    $onboard = $fnb->onboard(new FnbContext('fnb-smoke', 0, 1), [
        'outlet' => ['code' => 'MYSQL', 'name' => 'MySQL Smoke Cafe', 'timezone' => 'Asia/Ho_Chi_Minh', 'currency' => 'VND'],
        'terminal' => ['code' => 'POS-1', 'name' => 'POS 1', 'type' => 'pos'],
        'station' => ['code' => 'BAR', 'name' => 'Bar'],
        'payment_methods' => [
            ['code' => 'CASH', 'name' => 'Cash', 'kind' => 'cash'],
            ['code' => 'TRANSFER', 'name' => 'Transfer', 'kind' => 'transfer'],
        ],
        'table_count' => 0,
    ], 'mysql-onboard');
    $outletId = (int) $onboard['resource']['outlet']['id'];
    $terminalId = (int) $onboard['resource']['terminal']['id'];
    $stationId = (int) $onboard['resource']['station']['id'];
    $ctx = new FnbContext('fnb-smoke', $outletId, 1, $terminalId);

    $item = $fnb->saveCatalogItem($ctx, [
        'code' => 'MYSQL-COFFEE',
        'name' => 'MySQL Coffee',
        'tax_rate_bps' => 0,
        'tax_inclusive' => true,
        'variants' => [[
            'code' => 'ONE', 'name' => 'One', 'base_price_minor' => 29_000,
            'is_default' => true, 'station_id' => $stationId,
        ]],
        'modifier_group_ids' => [],
    ], 'mysql-item')['resource'];
    $variantId = (int) $item['variants'][0]['id'];
    $ingredient = app(FnbConfigurationService::class)->save($ctx, 'ingredient', null, [
        'code' => 'MYSQL-BEAN', 'name' => 'MySQL Bean', 'base_unit' => 'g', 'status' => 'active',
    ], 'mysql-ingredient')['resource'];
    app(FnbRecipeService::class)->publish($ctx, [
        'code' => 'MYSQL-RECIPE',
        'name' => 'MySQL Recipe',
        'variant_id' => $variantId,
        'expected_recipe_version' => 0,
        'yield_quantity' => '1',
        'yield_unit' => 'cup',
        'lines' => [[
            'ingredient_id' => (int) $ingredient['id'],
            'quantity' => '15',
            'unit' => 'g',
            'loss_rate' => '0',
        ]],
    ], 'mysql-recipe');

    $day = $fnb->openBusinessDay($ctx, now()->toDateString(), 'mysql-day')['resource'];
    $shift = $fnb->openShift($ctx, (int) $day['id'], 100_000, 'mysql-shift')['resource'];
    $session = $fnb->openSession($ctx, [
        'business_day_id' => (int) $day['id'], 'service_type' => 'counter', 'guest_count' => 1,
    ], 'mysql-session')['resource'];
    $order = $fnb->createOrder($ctx, (int) $session['id'], (int) $shift['id'], [], 'mysql-order', (int) $session['version'])['resource'];
    foreach (['refund-line', 'compensation-line'] as $suffix) {
        $order = $fnb->addOrderLine($ctx, (int) $order['id'], [
            'variant_id' => $variantId, 'quantity' => '1', 'note' => $suffix,
        ], 'mysql-'.$suffix, (int) $order['version'])['resource'];
    }
    $order = $fnb->submitOrder($ctx, (int) $order['id'], 'mysql-submit', (int) $order['version'])['resource'];
    $orderLines = DB::table('fnb_order_lines')->where('order_id', $order['id'])->orderBy('id')->get();
    $ticket = DB::table('fnb_kitchen_tickets')->where('order_id', $order['id'])->firstOrFail();
    $kitchenLines = DB::table('fnb_kitchen_ticket_lines')->where('ticket_id', $ticket->id)->orderBy('id')->get();
    foreach (['preparing', 'ready', 'served'] as $status) {
        $ticketVersion = (int) DB::table('fnb_kitchen_tickets')->where('id', $ticket->id)->value('version');
        $fnb->transitionKitchenLine($ctx, (int) $kitchenLines[0]->id, $status, 'mysql-kds-refund-'.$status, $ticketVersion);
    }
    $ticketVersion = (int) DB::table('fnb_kitchen_tickets')->where('id', $ticket->id)->value('version');
    $fnb->transitionKitchenLine($ctx, (int) $kitchenLines[1]->id, 'preparing', 'mysql-kds-comp-preparing', $ticketVersion);

    $sessionVersion = (int) DB::table('fnb_service_sessions')->where('id', $session['id'])->value('version');
    $check = $fnb->createCheck($ctx, (int) $session['id'], [], 'mysql-check', $sessionVersion)['resource'];
    $check = $fnb->finalizeCheck($ctx, (int) $check['id'], 'mysql-check-finalize', (int) $check['version'])['resource'];
    $check = $fnb->setSettlementPlan($ctx, (int) $check['id'], 'mixed', 'mysql-check-plan', (int) $check['version'])['resource'];
    $cashId = (int) DB::table('fnb_payment_methods')->where('outlet_id', $outletId)->where('kind', 'cash')->value('id');
    $transferId = (int) DB::table('fnb_payment_methods')->where('outlet_id', $outletId)->where('kind', 'transfer')->value('id');
    $cashPayment = $fnb->collectPayment($ctx, (int) $check['id'], (int) $shift['id'], [
        'payment_method_id' => $cashId, 'amount_minor' => 40_000, 'tendered_minor' => 40_000,
    ], 'mysql-pay-cash', (int) $check['version']);
    $checkVersion = (int) $cashPayment['meta']['check_version'];
    $fnb->collectPayment($ctx, (int) $check['id'], (int) $shift['id'], [
        'payment_method_id' => $transferId, 'amount_minor' => 18_000, 'reference' => 'MYSQL-SMOKE-TX',
    ], 'mysql-pay-transfer', $checkVersion);

    $checkLines = DB::table('fnb_check_lines')->where('check_id', $check['id'])->orderBy('order_line_id')->get()->keyBy('order_line_id');
    $fnb->refundPayment($ctx, (int) $cashPayment['resource']['payment']['id'], (int) $shift['id'], [
        'amount_minor' => 29_000,
        'reason' => 'MySQL smoke refund',
        'allocations' => [[
            'check_line_id' => (int) $checkLines[(int) $orderLines[0]->id]->id,
            'quantity' => '1',
        ]],
    ], 'mysql-refund');
    $compensation = app(FnbCompensationService::class)->compensate($ctx, (int) $checkLines[(int) $orderLines[1]->id]->id, [
        'shift_id' => (int) $shift['id'],
        'quantity' => '1',
        'expected_version' => (int) DB::table('fnb_orders')->where('id', $order['id'])->value('version'),
        'reason' => 'MySQL smoke unfulfilled item',
    ], 'mysql-compensation');
    if ($compensation['resource']['status'] !== 'resolved' || count($compensation['resource']['refund_ids']) !== 2) {
        throw new RuntimeException('Multi-tender fulfillment compensation did not resolve exactly.');
    }

    $receipt = app(FnbReceiptService::class)->generate($ctx, (int) $check['id'], 'mysql-receipt');
    $receiptRead = app(FnbReceiptService::class)->read($ctx, (int) $receipt['resource']['id']);
    if ($receiptRead['snapshot']['check']['settlement_total_minor'] !== 58_000) {
        throw new RuntimeException('Receipt JSON normalization changed an integer money value.');
    }
    if ((int) DB::table('fnb_refunds')->where('check_id', $check['id'])->sum('amount_minor') !== 58_000
        || (int) DB::table('fnb_check_financial_projections')->where('check_id', $check['id'])->value('net_collected_total_minor') !== 0
        || (int) DB::table('fnb_shifts')->where('id', $shift['id'])->value('expected_cash_minor') !== 100_000) {
        throw new RuntimeException('MySQL money ledger totals diverged after refund and compensation.');
    }
    foreach (['sale' => 30, 'reversal' => 15, 'waste' => 15] as $kind => $expectedQuantity) {
        $quantity = DB::table('fnb_stock_consumption_lines as line')
            ->join('fnb_stock_consumptions as consumption', 'consumption.id', '=', 'line.consumption_id')
            ->where('consumption.kind', $kind)->sum('line.quantity');
        if (bccomp((string) $quantity, (string) $expectedQuantity, 6) !== 0) {
            throw new RuntimeException("MySQL {$kind} stock quantity diverged: expected {$expectedQuantity}, got {$quantity}.");
        }
    }

    echo 'PASS: MySQL existing-core isolation; install/enable/disable/re-enable; '.$foreignKeys.' FKs; exact permissions; mixed tender/refund/compensation/stock/receipt checksum.', PHP_EOL;
    $passed = true;
} catch (Throwable $exception) {
    fwrite(STDERR, get_class($exception).': '.$exception->getMessage().PHP_EOL);
} finally {
    DB::setDefaultConnection($originalConnection);
    DB::purge('fnb_smoke');
    if ($created && preg_match('/\Aaio_fnb_smoke_[a-f0-9]{12}\z/', $databaseName)) {
        DB::connection($originalConnection)->statement('DROP DATABASE `'.$databaseName.'`');
        echo 'Temporary F&B smoke database removed.', PHP_EOL;
    }
}
exit($passed ? 0 : 1);
