<?php

return [
    'supported_locales' => ['vi', 'en'],
    'default_locale' => 'vi',
    'fallback_locale' => 'vi',
    'source_locale' => 'vi',
    'preset_locales' => [
        'vi' => [
            'name' => 'Tiếng Việt',
            'native_name' => 'Tiếng Việt',
        ],
        'en' => [
            'name' => 'English',
            'native_name' => 'English',
        ],
        'ja' => [
            'name' => 'Japanese',
            'native_name' => '日本語',
        ],
        'ko' => [
            'name' => 'Korean',
            'native_name' => '한국어',
        ],
        'zh-CN' => [
            'name' => 'Chinese (Simplified)',
            'native_name' => '简体中文',
        ],
    ],
    'route_segments' => [
        'vi' => [
            'login' => 'dang-nhap',
            'register' => 'dang-ky',
            'account' => 'tai-khoan',
            'favorite' => 'yeu-thich',
            'newsletter' => 'ban-tin',
            'subscribe' => 'dang-ky',
            'preview' => 'preview',
            'pages' => 'trang',
            'posts' => 'bai-viet',
            'products' => 'san-pham',
            'services' => 'dich-vu',
            'blog' => 'tin-tuc',
            'contact' => 'lien-he',
            'cart' => 'gio-hang',
            'buy_now' => 'mua-ngay',
            'cart_update' => 'cap-nhat',
            'cart_remove' => 'xoa',
            'checkout' => 'thanh-toan',
            'checkout_success' => 'thanh-cong',
            'search' => 'tim-kiem',
            'suggestions' => 'goi-y',
            'category' => 'danh-muc',
            'product' => 'san-pham',
        ],
        'en' => [
            'login' => 'login',
            'register' => 'register',
            'account' => 'account',
            'favorite' => 'favorites',
            'newsletter' => 'newsletter',
            'subscribe' => 'subscribe',
            'preview' => 'preview',
            'pages' => 'pages',
            'posts' => 'posts',
            'products' => 'products',
            'services' => 'services',
            'blog' => 'blog',
            'contact' => 'contact',
            'cart' => 'cart',
            'buy_now' => 'buy-now',
            'cart_update' => 'update',
            'cart_remove' => 'remove',
            'checkout' => 'checkout',
            'checkout_success' => 'success',
            'search' => 'search',
            'suggestions' => 'suggestions',
            'category' => 'category',
            'product' => 'product',
        ],
    ],
];
