@php
    $blocks=collect($landingBlocks??[])->values(); $canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null); $blockUpdateUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.update',['block'=>'__BLOCK_ID__']):''; $blockSourcePreviewUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.source-preview',['block'=>'__BLOCK_ID__']):''; $blockPayload=$canEditLanding?$blocks->keyBy('id')->toArray():[]; $editorLocales=[];
    $block=fn($type)=>$blocks->firstWhere('block_type',$type)??[]; $items=function($item){$custom=collect(data_get($item,'data.content.items',[]))->filter()->values();$dynamic=collect($item['dynamic_items']??[])->filter()->values();return data_get($item,'settings.source')==='custom'||$dynamic->isEmpty()?$custom->all():$dynamic->all();};
    $hero=$block('hero_slider'); $quality=$block('featured_categories'); $about=$block('about_experience'); $services=$block('content_mosaic'); $products=$block('featured_products'); $team=$block('team_members'); $projects=$block('project_gallery'); $pricing=$block('process_steps'); $testimonials=$block('testimonials'); $news=$block('bizmax_latest_posts'); $partners=$block('partner_logos');
    $slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values(); if($slides->isEmpty())$slides=collect([['title'=>'Cung cấp giải pháp xây dựng tốt nhất','summary'=>'Thiết kế và thi công trọn gói, chất lượng và an toàn.','image'=>'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=2200&q=90','button_label'=>'Liên hệ báo giá','link_url'=>'#lien-he']]); $short=fn($text,$limit=120)=>\Illuminate\Support\Str::limit(strip_tags((string)$text),$limit);
@endphp
@extends('theme-xd0322::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','XD0322 Construction')))
@section('content')
<main class="c322-main">
<section class="c322-hero">@foreach($slides as $index=>$slide)<article class="c322-hero__slide {{ $index===0?'is-active':'' }}" data-c322-slide><img src="{{ data_get($slide,'image') }}" alt="{{ data_get($slide,'title') }}"><div></div><div class="c322-container"><p>{{ data_get($hero,'data.subtitle','Chất lượng - An toàn - Hiệu quả') }}</p><h1>{{ data_get($slide,'title') }}</h1><span>{{ data_get($slide,'summary') }}</span><a class="c322-button" href="{{ data_get($slide,'link_url','#lien-he') }}">{{ data_get($slide,'button_label','Liên hệ báo giá') }} <i class="fa-solid fa-arrow-right"></i></a></div></article>@endforeach</section>
<section class="c322-values"><div class="c322-container">@foreach($items($quality) as $item)<article><i class="{{ data_get($item,'icon','fa-solid fa-helmet-safety') }}"></i><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></article>@endforeach</div></section>
<section id="gioi-thieu" class="c322-section"><div class="c322-container c322-about"><div><p class="c322-eyebrow">{{ data_get($about,'data.subtitle','Về chúng tôi') }}</p><h2>{{ data_get($about,'data.title','Chúng tôi dẫn đầu trong lĩnh vực xây dựng') }}</h2><strong>Chất lượng - An toàn - Hiệu quả - Chuyên nghiệp</strong><p>{{ data_get($about,'data.description','') }}</p><a class="c322-button c322-button--dark" href="#dich-vu">{{ data_get($about,'data.button_label','Xem thêm') }}</a></div><div class="c322-about__images"><img src="{{ data_get($about,'media.image','https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1100&q=85') }}" alt="{{ data_get($about,'data.title') }}"><img src="https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=700&q=85" alt="Đội ngũ thi công"></div></div></section>
<section id="dich-vu" class="c322-section c322-services"><div class="c322-container"><header class="c322-head"><p>{{ data_get($services,'data.subtitle','Dịch vụ của chúng tôi') }}</p><h2>{{ data_get($services,'data.title','Dịch vụ tốt nhất cho bạn') }}</h2></header><div>@forelse($items($services) as $item)<article><i class="fa-solid fa-compass-drafting"></i><h3>{{ data_get($item,'title','Dịch vụ thi công') }}</h3><p>{{ $short(data_get($item,'summary',data_get($item,'description','')),155) }}</p></article>@empty <p>Đang cập nhật dịch vụ.</p>@endforelse</div></div></section>
<section id="san-pham" class="c322-products"><div class="c322-container"><header class="c322-head c322-head--light"><p>{{ data_get($products,'data.subtitle','Nội thất và vật liệu') }}</p><h2>{{ data_get($products,'data.title','Sản phẩm của chúng tôi') }}</h2></header><div>@forelse($items($products) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=85') }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title','Nội thất hoàn thiện') }}</h3><strong>{{ data_get($item,'price_formatted',data_get($item,'price','Liên hệ')) }}</strong></a></article>@empty <p>Đang cập nhật sản phẩm.</p>@endforelse</div></div></section>
<section id="doi-ngu" class="c322-section"><div class="c322-container"><header class="c322-head"><p>{{ data_get($team,'data.subtitle','Tận tâm, chuyên nghiệp') }}</p><h2>{{ data_get($team,'data.title','Đội ngũ của chúng tôi') }}</h2></header><div class="c322-team">@forelse($items($team) as $member)<article><img src="{{ data_get($member,'image','https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=700&q=85') }}" alt="{{ data_get($member,'name') }}"><h3>{{ data_get($member,'name',data_get($member,'title','Thành viên')) }}</h3><p>{{ data_get($member,'role','Chuyên gia thi công') }}</p></article>@empty <p>Đang cập nhật đội ngũ.</p>@endforelse</div></div></section>
<section id="du-an" class="c322-projects"><div class="c322-container"><header class="c322-head c322-head--light"><h2>{{ data_get($projects,'data.title','Dự án của chúng tôi') }}</h2><p>{{ data_get($projects,'data.description','') }}</p></header><div>@forelse($items($projects) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title','Công trình tiêu biểu') }}</h3></a></article>@empty <p>Đang cập nhật dự án.</p>@endforelse</div></div></section>
<section class="c322-section c322-achievements"><div class="c322-container"><div><p class="c322-eyebrow">Thành tựu</p><h2>Thành tựu của chúng tôi</h2><p>Hành trình hơn 18 năm kiến tạo công trình chất lượng và bền vững.</p><div class="c322-stats"><span><b>18.000</b>Khách hàng</span><span><b>3.800</b>Dự án</span><span><b>1.000</b>Nhân viên</span><span><b>16</b>Văn phòng</span></div></div><img src="https://images.unsplash.com/photo-1542621334-a254cf47733d?auto=format&fit=crop&w=1000&q=85" alt="Công trường xây dựng"></div></section>
<section class="c322-testimonials"><div class="c322-container"><header class="c322-head c322-head--light"><h2>{{ data_get($testimonials,'data.title','Nhận xét của khách hàng') }}</h2><p>{{ data_get($testimonials,'data.subtitle','Phản hồi sau thi công') }}</p></header><div>@forelse($items($testimonials) as $item)<article><blockquote>“{{ data_get($item,'quote',data_get($item,'summary','Dịch vụ thi công chuyên nghiệp và đúng tiến độ.')) }}”</blockquote><footer>{{ data_get($item,'name',data_get($item,'title','Khách hàng')) }}<small>{{ data_get($item,'role','Khách hàng') }}</small></footer></article>@empty <p>Đang cập nhật phản hồi.</p>@endforelse</div></div></section>
<section class="c322-section c322-pricing"><div class="c322-container"><header class="c322-head"><p>{{ data_get($pricing,'data.subtitle','Gói dịch vụ') }}</p><h2>{{ data_get($pricing,'data.title','Báo giá thi công') }}</h2><p>{{ data_get($pricing,'data.description','') }}</p></header><div>@foreach(data_get($pricing,'data.content.items',[]) as $item)<article><h3>{{ data_get($item,'title') }}</h3><strong>{{ data_get($item,'summary') }}</strong><ul><li>Tư vấn phong thủy</li><li>Bản vẽ chi tiết kiến trúc</li><li>Quản lý tiến độ thi công</li><li>Hỗ trợ sau bàn giao</li></ul><a class="c322-button c322-button--dark" href="#lien-he">Đăng ký ngay</a></article>@endforeach</div></div></section>
<section id="tin-tuc" class="c322-section"><div class="c322-container"><header class="c322-head"><p>{{ data_get($news,'data.subtitle','Tin tức và cập nhật') }}</p><h2>{{ data_get($news,'data.title','Bài viết mới nhất') }}</h2></header><div class="c322-news">@forelse($items($news) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item,'title') }}"><small>{{ data_get($item,'published_at','XD0322 Construction') }}</small><h3>{{ data_get($item,'title','Kiến thức xây dựng') }}</h3><p>{{ $short(data_get($item,'summary',data_get($item,'description','')),110) }}</p></a></article>@empty <p>Đang cập nhật bài viết.</p>@endforelse</div></div></section>
<section class="c322-partners"><div class="c322-container">@forelse($items($partners) as $item)<a href="{{ data_get($item,'url','#') }}">@if(filled(data_get($item,'image')))<img src="{{ data_get($item,'image') }}" alt="{{ data_get($item,'name',data_get($item,'title','Đối tác')) }}">@else<strong>{{ data_get($item,'name',data_get($item,'title','Đối tác')) }}</strong>@endif</a>@empty <span>VIETBUILD</span><span>AN CƯỜNG</span><span>HÒA PHÁT</span><span>DULUX</span><span>VIGLACERA</span>@endforelse</div></section>
</main>
@endsection
