@php
    $blocks=collect($landingBlocks??[])->values(); $canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null); $blockUpdateUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.update',['block'=>'__BLOCK_ID__']):''; $blockSourcePreviewUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.source-preview',['block'=>'__BLOCK_ID__']):''; $blockPayload=$canEditLanding?$blocks->keyBy('id')->toArray():[]; $editorLocales=[];
    $block=fn($type)=>$blocks->firstWhere('block_type',$type)??[]; $items=fn($item)=>collect($item['dynamic_items']??[])->filter()->isNotEmpty()?collect($item['dynamic_items'])->filter()->values()->all():collect(data_get($item,'data.content.items',[]))->filter()->values()->all();
    $hero=$block('hero_slider'); $quality=$block('featured_categories'); $about=$block('about_experience'); $services=$block('content_mosaic'); $products=$block('featured_products'); $team=$block('team_members'); $projects=$block('project_gallery'); $pricing=$block('process_steps'); $testimonials=$block('testimonials'); $news=$block('bizmax_latest_posts'); $partners=$block('partner_logos');
    $slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values(); if($slides->isEmpty())$slides=collect([['title'=>'Cung cap giai phap xay dung tot nhat','summary'=>'Thiet ke va thi cong tron goi, chat luong va an toan.','image'=>'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=2200&q=90','button_label'=>'Lien he bao gia','link_url'=>'#lien-he']]); $short=fn($text,$limit=120)=>\Illuminate\Support\Str::limit(strip_tags((string)$text),$limit);
@endphp
@extends('theme-xd0322::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','XD0322 Construction')))
@section('content')
<main class="c322-main">
<section class="c322-hero">@foreach($slides as $index=>$slide)<article class="c322-hero__slide {{ $index===0?'is-active':'' }}" data-c322-slide><img src="{{ data_get($slide,'image') }}" alt="{{ data_get($slide,'title') }}"><div></div><div class="c322-container"><p>{{ data_get($hero,'data.subtitle','Chat luong - An toan - Hieu qua') }}</p><h1>{{ data_get($slide,'title') }}</h1><span>{{ data_get($slide,'summary') }}</span><a class="c322-button" href="{{ data_get($slide,'link_url','#lien-he') }}">{{ data_get($slide,'button_label','Lien he bao gia') }} -></a></div></article>@endforeach</section>
<section class="c322-values"><div class="c322-container">@foreach($items($quality) as $item)<article><i class="{{ data_get($item,'icon','fa-solid fa-helmet-safety') }}"></i><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></article>@endforeach</div></section>
<section id="gioi-thieu" class="c322-section"><div class="c322-container c322-about"><div><p class="c322-eyebrow">{{ data_get($about,'data.subtitle','Ve chung toi') }}</p><h2>{{ data_get($about,'data.title','Chung toi dan dau trong linh vuc xay dung') }}</h2><strong>Chat luong - An toan - Hieu qua - Chuyen nghiep</strong><p>{{ data_get($about,'data.description','') }}</p><a class="c322-button c322-button--dark" href="#dich-vu">{{ data_get($about,'data.button_label','Xem them') }}</a></div><div class="c322-about__images"><img src="{{ data_get($about,'media.image','https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1100&q=85') }}" alt="{{ data_get($about,'data.title') }}"><img src="https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=700&q=85" alt="Construction team"></div></div></section>
<section id="dich-vu" class="c322-section c322-services"><div class="c322-container"><header class="c322-head"><p>{{ data_get($services,'data.subtitle','Dich vu cua chung toi') }}</p><h2>{{ data_get($services,'data.title','Dich vu tot nhat cho ban') }}</h2></header><div>@forelse($items($services) as $item)<article><i class="fa-solid fa-compass-drafting"></i><h3>{{ data_get($item,'title','Dich vu thi cong') }}</h3><p>{{ $short(data_get($item,'summary',data_get($item,'description','')),155) }}</p></article>@empty <p>Dang cap nhat dich vu.</p>@endforelse</div></div></section>
<section id="san-pham" class="c322-products"><div class="c322-container"><header class="c322-head c322-head--light"><p>{{ data_get($products,'data.subtitle','Noi that va vat lieu') }}</p><h2>{{ data_get($products,'data.title','San pham cua chung toi') }}</h2></header><div>@forelse($items($products) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=85') }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title','Noi that hoan thien') }}</h3><strong>{{ data_get($item,'price_formatted',data_get($item,'price','Lien he')) }}</strong></a></article>@empty <p>Dang cap nhat san pham.</p>@endforelse</div></div></section>
<section id="doi-ngu" class="c322-section"><div class="c322-container"><header class="c322-head"><p>{{ data_get($team,'data.subtitle','Tan tam, chuyen nghiep') }}</p><h2>{{ data_get($team,'data.title','Doi ngu cua chung toi') }}</h2></header><div class="c322-team">@forelse($items($team) as $member)<article><img src="{{ data_get($member,'image','https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=700&q=85') }}" alt="{{ data_get($member,'name') }}"><h3>{{ data_get($member,'name',data_get($member,'title','Thanh vien')) }}</h3><p>{{ data_get($member,'role','Chuyen gia thi cong') }}</p></article>@empty <p>Dang cap nhat doi ngu.</p>@endforelse</div></div></section>
<section id="du-an" class="c322-projects"><div class="c322-container"><header class="c322-head c322-head--light"><h2>{{ data_get($projects,'data.title','Du an cua chung toi') }}</h2><p>{{ data_get($projects,'data.description','') }}</p></header><div>@forelse($items($projects) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title','Cong trinh tieu bieu') }}</h3></a></article>@empty <p>Dang cap nhat du an.</p>@endforelse</div></div></section>
<section class="c322-section c322-achievements"><div class="c322-container"><div><p class="c322-eyebrow">Thanh tuu</p><h2>Thanh tuu cua chung toi</h2><p>Hanh trinh hon 18 nam kien tao cong trinh chat luong va ben vung.</p><div class="c322-stats"><span><b>18000</b>Khach hang</span><span><b>3800</b>Du an</span><span><b>1000</b>Nhan vien</span><span><b>16</b>Van phong</span></div></div><img src="https://images.unsplash.com/photo-1542621334-a254cf47733d?auto=format&fit=crop&w=1000&q=85" alt="Construction site"></div></section>
<section class="c322-testimonials"><div class="c322-container"><header class="c322-head c322-head--light"><h2>{{ data_get($testimonials,'data.title','Nhan xet cua khach hang') }}</h2><p>{{ data_get($testimonials,'data.subtitle','Phan hoi sau thi cong') }}</p></header><div>@forelse($items($testimonials) as $item)<article><blockquote>“{{ data_get($item,'quote',data_get($item,'summary','Dich vu thi cong chuyen nghiep va dung tien do.')) }}”</blockquote><footer>{{ data_get($item,'name',data_get($item,'title','Khach hang')) }}<small>{{ data_get($item,'role','Khach hang') }}</small></footer></article>@empty <p>Dang cap nhat phan hoi.</p>@endforelse</div></div></section>
<section class="c322-section c322-pricing"><div class="c322-container"><header class="c322-head"><p>{{ data_get($pricing,'data.subtitle','Goi dich vu') }}</p><h2>{{ data_get($pricing,'data.title','Bao gia thi cong') }}</h2><p>{{ data_get($pricing,'data.description','') }}</p></header><div>@foreach(data_get($pricing,'data.content.items',[]) as $item)<article><h3>{{ data_get($item,'title') }}</h3><strong>{{ data_get($item,'summary') }}</strong><ul><li>Tu van phong thuy</li><li>Ban ve chi tiet kien truc</li><li>Quan ly tien do thi cong</li><li>Ho tro sau ban giao</li></ul><a class="c322-button c322-button--dark" href="#lien-he">Dang ky ngay</a></article>@endforeach</div></div></section>
<section id="tin-tuc" class="c322-section"><div class="c322-container"><header class="c322-head"><p>{{ data_get($news,'data.subtitle','Tin tuc va cap nhat') }}</p><h2>{{ data_get($news,'data.title','Bai viet moi nhat') }}</h2></header><div class="c322-news">@forelse($items($news) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item,'title') }}"><small>{{ data_get($item,'published_at','XD0322 Construction') }}</small><h3>{{ data_get($item,'title','Kien thuc xay dung') }}</h3><p>{{ $short(data_get($item,'summary',data_get($item,'description','')),110) }}</p></a></article>@empty <p>Dang cap nhat bai viet.</p>@endforelse</div></div></section>
<section class="c322-partners"><div class="c322-container">@forelse($items($partners) as $item)<a href="{{ data_get($item,'url','#') }}"><img src="{{ data_get($item,'image','https://placehold.co/200x100/ffffff/071638?text=Partner') }}" alt="{{ data_get($item,'title','Partner') }}"></a>@empty <span>COMPANY</span><span>COMPANY</span><span>COMPANY</span><span>COMPANY</span><span>COMPANY</span>@endforelse</div></section>
</main>
@endsection
