@php
  $blocks=collect($landingBlocks??[])->values();$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null);$blockUpdateUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.update',['block'=>'__BLOCK_ID__']):'';$blockSourcePreviewUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.source-preview',['block'=>'__BLOCK_ID__']):'';$blockPayload=$canEditLanding?$blocks->keyBy('id')->toArray():[];$editorLocales=collect(\App\Support\FrontendLocalization::supportedLocales())->map(fn($locale)=>['code'=>$locale,'label'=>strtoupper($locale)])->all();
  $items=fn($block)=>collect($block['dynamic_items']??[])->filter()->values()->whenEmpty(fn($list)=>$list->push(...collect(data_get($block,'data.content.items',[]))->filter()->values()->all()));
  $img=fn($item,$fallback='')=>data_get($item,'image',data_get($item,'image_url',$fallback));$assetImage=fn($name)=>asset('themes/AUTO853/images/'.$name.'.png');$money=fn($value)=>(float)$value>0?number_format((float)$value,0,',','.').'đ':'Liên hệ';
  $productCard=function($item)use($img,$assetImage,$money){$title=data_get($item,'title',data_get($item,'name'));$price=(float)data_get($item,'price');$original=(float)data_get($item,'original_price');$off=$original>$price&&$price>0?round((1-$price/$original)*100):0;@endphp
    <article class="a853-product"><a class="a853-product-image" href="{{ data_get($item,'url','#san-pham') }}">@if($off)<span>-{{ $off }}%</span>@endif<img src="{{ $img($item,$assetImage('bike-1')) }}" alt="{{ $title }}"><i class="fa-regular fa-eye"></i></a><small>{{ data_get($item,'category','SUMMIT CYCLE') }}</small><h3><a href="{{ data_get($item,'url','#san-pham') }}">{{ $title }}</a></h3><div class="a853-stars">★★★★★</div><strong>{{ $money($price) }}</strong>@if($original>$price)<del>{{ $money($original) }}</del>@endif<div class="a853-stock"><span></span><small>Vừa mở bán</small></div></article>
  @php };
@endphp
@extends('theme-auto853::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','AUTO853')))
@section('content')
<main>
@foreach($blocks as $block) @php($type=data_get($block,'block_type'))
@if($type==='auto853_hero')
<section class="a853-hero xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}" data-a853-slider data-autoplay="6500"><article class="a853-hero-slide is-active" data-a853-slide style="background-image:linear-gradient(180deg,rgba(0,0,0,.08),rgba(0,0,0,.26)),url('{{ data_get($block,'media.image',$assetImage('hero-mountain')) }}')"><div class="a853-hero-copy"><small>{{ data_get($block,'data.subtitle') }}</small><h1>{{ data_get($block,'data.title') }}</h1><p>{{ data_get($block,'data.description') }}</p><a class="a853-btn a853-btn-dark" href="#san-pham">{{ data_get($block,'data.button_label') }} <i class="fa-solid fa-arrow-right"></i></a></div></article><button data-a853-prev aria-label="Trước"><i class="fa-solid fa-chevron-left"></i></button><button data-a853-next aria-label="Sau"><i class="fa-solid fa-chevron-right"></i></button>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto853_categories')
<section id="danh-muc" class="a853-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a853-wrap"><h2 class="a853-heading">{{ data_get($block,'data.title') }}</h2><div class="a853-categories">@foreach($items($block)->take(6) as $item)<a href="{{ data_get($item,'url','#san-pham') }}"><span><img src="{{ $img($item,$assetImage('bike-'.$loop->iteration)) }}" alt="{{ data_get($item,'title') }}"></span><b>{{ data_get($item,'title') }}</b><small>{{ data_get($item,'product_count',data_get($item,'summary','Khám phá ngay')) }}</small></a>@endforeach</div></div>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto853_flash_sale')
<section id="flash-sale" class="a853-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a853-wrap"><div class="a853-sale-head"><h2>{{ data_get($block,'data.title') }} 🔥</h2><div><span>Kết thúc sau</span><b>08<small>Giờ</small></b><b>54<small>Phút</small></b><b>12<small>Giây</small></b></div></div><div class="a853-products a853-products-four">@foreach($items($block)->take(4) as $item){{ $productCard($item) }}@endforeach</div><div class="a853-center"><a class="a853-outline" href="#san-pham">Xem tất cả <i class="fa-solid fa-chevron-right"></i></a></div></div>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto853_promotions')
<section class="a853-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a853-wrap a853-promo-grid">@foreach($items($block)->take(3) as $item)<article style="background-image:linear-gradient(90deg,rgba(0,0,0,.74),rgba(0,0,0,.06)),url('{{ $img($item,$assetImage(['promo-accessories','promo-light','promo-saddle'][$loop->index]??'promo-accessories')) }}')"><div><small>{{ data_get($item,'subtitle') }}</small><h2>{{ data_get($item,'title') }}</h2><p>{{ data_get($item,'summary') }}</p><a class="a853-outline a853-outline-light" href="#san-pham">Xem chi tiết</a></div></article>@endforeach</div>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto853_bikepacking')
<section id="bikepacking" class="a853-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a853-wrap"><h2 class="a853-heading">{{ data_get($block,'data.title') }}</h2><div class="a853-bikepacking">@foreach($items($block)->take(3) as $item)<article><div><img src="{{ $img($item,$assetImage('story-'.$loop->iteration)) }}" alt="{{ data_get($item,'title') }}"><button aria-label="Khám phá"><i class="fa-solid fa-plus"></i></button></div><h3>{{ data_get($item,'title') }}</h3><a class="a853-outline" href="#san-pham">Xem chi tiết</a></article>@endforeach</div></div>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto853_feature')
<section class="a853-section a853-feature xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a853-wrap"><img src="{{ data_get($block,'media.image',$assetImage('bike-10')) }}" alt="{{ data_get($block,'data.title') }}"><div><small>{{ data_get($block,'data.subtitle') }}</small><h2>{{ data_get($block,'data.title') }}</h2><p>{{ data_get($block,'data.description') }}</p><ul>@foreach((array)data_get($block,'data.content.features',[]) as $feature)<li>{{ $feature }}</li>@endforeach</ul><a class="a853-outline" href="#san-pham">{{ data_get($block,'data.button_label') }}</a></div></div>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto853_sale_banner')
<section class="a853-section a853-banner-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a853-wrap a853-sale-banner" style="background-image:linear-gradient(90deg,rgba(0,0,0,.78),rgba(0,0,0,.08)),url('{{ data_get($block,'media.image',$assetImage('promo-trail')) }}')"><div><small>{{ data_get($block,'data.subtitle') }}</small><h2>{{ data_get($block,'data.title') }}</h2><p>{{ data_get($block,'data.description') }}</p><a class="a853-outline a853-outline-light" href="#san-pham">{{ data_get($block,'data.button_label') }}</a></div></div>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto853_collection')
<section id="san-pham" class="a853-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a853-wrap"><h2 class="a853-heading">{{ data_get($block,'data.title') }}</h2><div class="a853-collection">@foreach($items($block)->take(3) as $item)<article><div><small>{{ data_get($item,'category','NĂNG LƯỢNG BỨT PHÁ') }}</small><h3>{{ data_get($item,'title') }}</h3><strong>{{ $money(data_get($item,'price')) }}</strong><a href="{{ data_get($item,'url','#') }}">Xem chi tiết</a></div><img src="{{ $img($item,$assetImage('bike-'.($loop->iteration+8))) }}" alt="{{ data_get($item,'title') }}"></article>@endforeach</div></div>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto853_videos')
<section class="a853-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a853-wrap"><h2 class="a853-heading">{{ data_get($block,'data.title') }}</h2><div class="a853-videos">@foreach($items($block)->take(4) as $item)<a href="{{ data_get($item,'url','#') }}"><img src="{{ $img($item,$assetImage('story-'.(($loop->iteration+1)%6+1))) }}" alt="{{ data_get($item,'title') }}"><span><i class="fa-solid fa-play"></i></span><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></div>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@elseif($type==='auto853_news')
<section id="tin-tuc" class="a853-section xd-landing-block" data-block-type="{{ $type }}" data-landing-block-id="{{ data_get($block,'id') }}"><div class="a853-wrap"><div class="a853-title-row"><h2>{{ data_get($block,'data.title') }}</h2><a class="a853-outline" href="{{ route('site.blog.index',['locale'=>app()->getLocale()]) }}">Xem tất cả</a></div><div class="a853-news">@foreach($items($block)->take(4) as $item)<article><img src="{{ $img($item,$assetImage('story-'.(($loop->iteration+3)%6+1))) }}" alt="{{ data_get($item,'title') }}"><h3><a href="{{ data_get($item,'url','#') }}">{{ data_get($item,'title') }}</a></h3><small><i class="fa-solid fa-calendar-days"></i> {{ data_get($item,'date',now()->format('d/m/Y')) }} · 5 phút đọc</small><p>{{ data_get($item,'summary') }}</p><a href="{{ data_get($item,'url','#') }}">Đọc tiếp</a></article>@endforeach</div></div>@include('theme-auto853::partials.edit-button',['block'=>$block])</section>
@endif
@endforeach
</main>
@endsection
