<div class="dr-order-modal" data-dr-order-modal aria-hidden="true">
    <button class="dr-order-modal__backdrop" type="button" data-dr-order-close aria-label="Đóng form đặt bàn"></button>
    <section class="dr-order-dialog" role="dialog" aria-modal="true" aria-labelledby="dr-order-title">
        <button class="dr-order-dialog__close" type="button" data-dr-order-close aria-label="Đóng">×</button>
        <div class="dr-order-dialog__intro"><span>Đặt bàn tại Dola</span><h2 id="dr-order-title">Chuẩn bị cho một bữa ăn đáng nhớ</h2><p>Chọn thời gian phù hợp và để lại yêu cầu. Nhà hàng sẽ liên hệ xác nhận trong thời gian sớm nhất.</p><ul><li>Không gian ấm cúng và riêng tư</li><li>Thực đơn linh hoạt theo khẩu vị</li><li>Phục vụ tận tâm mỗi ngày</li></ul><small>Hotline hỗ trợ</small><strong>1900 6750</strong></div>
        <form class="dr-order-form" method="POST" action="{{ route('site.contact.submit') }}" data-dr-order-form>
            @csrf<input type="hidden" name="source" value="quote_modal"><input type="hidden" name="subject" value="Nội dung Yêu cầu đặt bàn"><input type="hidden" name="route_summary" data-dr-order-summary><input type="hidden" name="message" data-dr-order-message>
            <div class="dr-order-form__head"><span>Thông tin đặt bàn</span><h3>Chúng tôi giữ chỗ cho bạn</h3></div>
            <div class="dr-order-form__grid"><label>Họ và tên *<input name="name" required autocomplete="name" placeholder="Nguyễn Văn A"></label><label>Số điện thoại *<input name="phone" required autocomplete="tel" placeholder="0900 000 000"></label><label>Email *<input name="email" type="email" required autocomplete="email" placeholder="email@example.com"></label><label>Số khách *<input type="number" min="1" max="30" value="2" required data-dr-order-guests></label><label>Ngày đến *<input type="date" required min="{{ now()->format('Y-m-d') }}" data-dr-order-date></label><label>Giờ đến *<input type="time" required value="18:30" data-dr-order-time></label></div>
            <label>Yêu cầu món hoặc ghi chú<textarea minlength="3" maxlength="1200" placeholder="Ví dụ: bàn gần cửa sổ, có trẻ nhỏ, món ít cay..." data-dr-order-note></textarea></label>
            <p class="dr-order-form__privacy">Thông tin chỉ được dùng để xác nhận và phục vụ lịch đặt bàn.</p><button type="submit">Xác nhận yêu cầu đặt bàn →</button>
        </form>
    </section>
</div>
<style>
body.dr-modal-open{overflow:hidden}.dr-book{border:0;cursor:pointer;font:700 14px 'Be Vietnam Pro',sans-serif}.dr-order-modal{position:fixed;z-index:1000;inset:0;display:grid;place-items:center;padding:24px;visibility:hidden;opacity:0;transition:.22s}.dr-order-modal.is-open{visibility:visible;opacity:1}.dr-order-modal__backdrop{position:absolute;inset:0;border:0;background:rgba(2,13,12,.82);backdrop-filter:blur(7px)}.dr-order-dialog{position:relative;display:grid;grid-template-columns:.82fr 1.18fr;width:min(980px,100%);max-height:min(90vh,760px);overflow:auto;background:#fff;color:#153d37;border-radius:18px;box-shadow:0 30px 90px rgba(0,0,0,.45)}.dr-order-dialog__close{position:absolute;z-index:2;right:16px;top:14px;width:39px;height:39px;border:0;border-radius:50%;background:#f4eee4;color:#193e39;font-size:26px;cursor:pointer}.dr-order-dialog__intro{padding:48px 40px;background:linear-gradient(160deg,rgba(8,45,41,.92),rgba(7,30,28,.98)),url('https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1000&q=85') center/cover;color:#fff}.dr-order-dialog__intro>span,.dr-order-form__head>span{color:var(--dr-gold);text-transform:uppercase;letter-spacing:2px;font-size:12px;font-weight:700}.dr-order-dialog__intro h2{font:700 43px/1.08 'Dancing Script',cursive;margin:12px 0 20px}.dr-order-dialog__intro p{color:#dce8e5;line-height:1.7}.dr-order-dialog__intro ul{padding:0;list-style:none;margin:28px 0}.dr-order-dialog__intro li{padding:11px 0;border-bottom:1px solid rgba(255,255,255,.15)}.dr-order-dialog__intro li:before{content:'✓';color:var(--dr-gold);margin-right:10px}.dr-order-dialog__intro small{display:block;color:#a8bcb7}.dr-order-dialog__intro strong{display:block;color:var(--dr-gold);font-size:25px;margin-top:5px}.dr-order-form{padding:44px 42px}.dr-order-form__head h3{font-size:29px;margin:8px 0 25px}.dr-order-form__grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.dr-order-form label{display:block;font-size:12px;font-weight:700;margin-bottom:15px}.dr-order-form input,.dr-order-form textarea{display:block;width:100%;margin-top:7px;border:1px solid #d8deda;border-radius:8px;padding:12px 13px;background:#fbfcfb;color:#173d37;font:inherit}.dr-order-form textarea{height:86px;resize:vertical}.dr-order-form input:focus,.dr-order-form textarea:focus{outline:2px solid rgba(221,161,73,.35);border-color:var(--dr-gold)}.dr-order-form__privacy{font-size:11px;color:#778680;margin:0 0 16px}.dr-order-form>button{width:100%;border:0;border-radius:8px;padding:14px;background:var(--dr-gold);color:#fff;font-weight:700;cursor:pointer}@media(max-width:760px){.dr-order-modal{padding:10px}.dr-order-dialog{grid-template-columns:1fr;max-height:95vh}.dr-order-dialog__intro{padding:34px 25px}.dr-order-dialog__intro h2{font-size:34px}.dr-order-dialog__intro ul{display:none}.dr-order-form{padding:30px 22px}.dr-order-form__grid{grid-template-columns:1fr}.dr-order-dialog__close{right:10px;top:10px}}
</style>
