<style>
:root{--xd8-purple:#42228f;--xd8-purple-dark:#281258;--xd8-orange:#ff7a24;--xd8-yellow:#ffd95a;--xd8-cream:#fff9ef;--xd8-blue:#2967e8;--xd8-ink:#211b35;--xd8-muted:#6f6980;--xd4-green:var(--xd8-orange);--xd4-ink:var(--xd8-ink);--xd4-muted:var(--xd8-muted);--xd4-container:min(1280px,calc(100% - 56px))}
html{scroll-behavior:smooth}body{background:var(--xd8-cream);color:var(--xd8-ink);font-family:"Segoe UI",Arial,sans-serif}.xd4-page{overflow:hidden}
.xd4-header{position:absolute;background:transparent;color:#fff}.xd4-header__inner{min-height:98px}.xd4-brand{font-size:0}.xd4-brand:after{content:"COMGO";font-size:28px;font-weight:900;letter-spacing:-.05em}.xd4-brand:before{display:grid;width:44px;height:44px;place-items:center;border-radius:14px;background:var(--xd8-orange);content:"✦";font-size:20px}.xd4-brand:has(img):before,.xd4-brand:has(img):after{display:none}.xd4-brand img{max-width:170px}.xd4-nav{gap:25px;font-size:13px;letter-spacing:.04em;text-transform:none}.xd4-nav a:hover{color:var(--xd8-yellow)}.xd4-search{display:none}.xd4-quote{border-radius:999px;background:#fff;color:var(--xd8-purple);padding:13px 20px}
.xd4-hero{min-height:780px;background:var(--xd8-purple-dark)}.xd4-hero__slide img{position:absolute;inset:0;filter:saturate(.9)}.xd4-hero__veil{background:linear-gradient(90deg,rgba(40,18,88,.94) 0 46%,rgba(66,34,143,.32) 78%)}.xd4-hero__content{min-height:780px;justify-content:flex-start;padding:150px max(32px,calc((100% - 1280px)/2)) 90px}.xd4-hero__copy{width:min(680px,60%);text-align:left}.xd4-eyebrow{color:var(--xd8-yellow);font-size:13px;font-weight:850;letter-spacing:.18em;text-transform:uppercase}.xd4-hero h1{font-size:clamp(48px,6vw,86px);font-weight:850;letter-spacing:-.06em;line-height:.94;text-transform:none}.xd4-hero p{max-width:590px;color:#e8defd}.xd4-actions{justify-content:flex-start}.xd4-button{min-height:58px;border-radius:999px;background:var(--xd8-orange);box-shadow:0 16px 35px rgba(255,122,36,.24)}.xd4-button--outline{background:transparent}.xd4-hero__arrow{width:50px;height:50px;border-radius:16px;font-size:30px}
.xd4-section{padding:110px 0;background:var(--xd8-cream)}.xd4-section:nth-of-type(even){background:#fff}.xd4-section-title{font-size:clamp(38px,4.5vw,62px);font-weight:850;letter-spacing:-.05em;line-height:1.02;text-transform:none}
.xd8-about__grid{display:grid;grid-template-columns:1fr .95fr;align-items:center;gap:90px}.xd8-about__media{position:relative;min-height:570px}.xd8-about__media img{width:82%;height:520px;border-radius:32px 120px 32px 32px;object-fit:cover}.xd8-about__badge{position:absolute;right:0;bottom:0;display:grid;width:210px;height:210px;place-items:center;padding:28px;border:14px solid var(--xd8-cream);border-radius:50%;background:var(--xd8-orange);color:#fff;text-align:center}.xd8-about__badge b{display:block;font-size:48px}.xd8-about__copy>p{color:var(--xd8-muted);font-size:17px}
.xd3-process{padding:110px 0;background:var(--xd8-purple);color:#fff}.xd3-container{width:var(--xd4-container);margin:auto}.xd3-process__title{display:flex;align-items:end;justify-content:space-between;gap:40px}.xd3-process__title h2{max-width:740px;margin:0;font-size:clamp(38px,4.5vw,62px);letter-spacing:-.05em;line-height:1}.xd3-process__title p{color:var(--xd8-yellow);font-weight:800;text-transform:uppercase;letter-spacing:.12em}.xd3-process__intro{max-width:650px;color:#d9cdf5}.xd3-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:55px}.xd3-step{min-height:230px;padding:30px;border:1px solid rgba(255,255,255,.14);border-radius:24px;background:rgba(255,255,255,.06);transition:.25s}.xd3-step:hover{background:var(--xd8-orange);transform:translateY(-8px)}.xd3-step__number{color:var(--xd8-yellow);font-size:38px;font-weight:900}.xd3-step h3{margin:34px 0 10px;font-size:20px}.xd3-step p{color:#ded5f2}
.xd2-section,.xd-section{padding:110px 0}.xd2-container,.xd-container{width:var(--xd4-container);margin:auto}.xd2-head,.xd-section-head,.xd-mosaic-head{text-align:center}.xd2-kicker,.xd-section-head p,.xd-mosaic-head p{color:var(--xd8-orange);font-size:13px;font-weight:850;letter-spacing:.15em;text-transform:uppercase}.xd2-title,.xd-mosaic-head h2{margin:10px auto 0;font-size:clamp(38px,4vw,58px);letter-spacing:-.05em;line-height:1.05}.xd2-service-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;margin-top:52px}.xd2-service-grid>article{overflow:hidden;border-radius:28px;background:#fff;box-shadow:0 20px 60px rgba(56,34,111,.11);transition:.25s}.xd2-service-grid>article:hover{transform:translateY(-9px)}.xd2-service-grid img{width:100%;height:230px;object-fit:cover}.xd2-service-grid>article>div{padding:28px}.xd2-service-grid h3{margin:0 0 12px}.xd2-service-grid p{color:var(--xd8-muted)}.xd2-service-grid a{color:var(--xd8-orange);font-weight:800}
.xd-content-mosaic{background:#fff}.xd-mosaic-head h2 em{color:var(--xd8-orange);font-style:normal}.xd-mosaic-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:18px;margin-top:55px}.xd-mosaic-card{grid-column:span 4;display:flex;min-height:270px;overflow:hidden;border-radius:26px}.xd-mosaic-card:nth-child(1),.xd-mosaic-card:nth-child(5){grid-column:span 8}.xd-mosaic-image img{width:100%;height:100%;object-fit:cover;transition:.4s}.xd-mosaic-copy{flex-direction:column;justify-content:flex-end;padding:32px;background:var(--xd8-purple);color:#fff}.xd-mosaic-copy:nth-child(3n){background:var(--xd8-orange)}.xd-mosaic-copy strong{font-size:25px}.xd-mosaic-copy span{margin-top:12px;color:#eee5ff}.xd-mosaic-image:hover img{transform:scale(1.05)}
.xd-testimonials{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;background:transparent}.xd-testimonial{display:grid;grid-template-columns:auto 1fr;gap:18px;min-width:0;padding:34px;border-radius:28px;background:#fff;box-shadow:0 18px 55px rgba(56,34,111,.08)}.xd-testimonial .xd-avatar{width:58px;height:58px;border-radius:50%;object-fit:cover}.xd-testimonial p{margin-top:0;color:var(--xd8-muted)}.xd-testimonial small{display:block;color:var(--xd8-orange)}.xd-testimonial .xd-quote{color:var(--xd8-orange);font-size:45px}.xd-row-nav,.xd-row-dots{display:none}
.xd2-contact{padding:110px 0;background:linear-gradient(135deg,var(--xd8-purple-dark),var(--xd8-purple));color:#fff}.xd2-contact__panel{display:grid;grid-template-columns:1fr 1fr;gap:70px;align-items:center}.xd2-contact__panel form{display:grid;gap:13px;padding:38px;border-radius:30px;background:#fff;color:var(--xd8-ink)}.xd2-contact__panel input,.xd2-contact__panel textarea{width:100%;padding:16px;border:1px solid #e7def4;border-radius:14px;background:#faf8ff}.xd2-contact__panel textarea{min-height:120px}.xd2-button{min-height:54px;border:0;border-radius:999px;background:var(--xd8-orange);color:#fff;font-weight:800}.xd2-contact__phone strong{color:var(--xd8-yellow)}
.xd4-footer{background:var(--xd8-purple-dark)}.xd4-footer h3{text-transform:none}.xd4-footer p,.xd4-footer li{color:#d9cdf0}.xd4-newsletter button{background:var(--xd8-orange)}
[data-xd-reveal]{opacity:0;transform:translateY(46px);transition:opacity .75s ease,transform .75s cubic-bezier(.2,.8,.2,1);transition-delay:var(--reveal-delay,0ms)}[data-xd-reveal].is-visible{opacity:1;transform:none}
@media(max-width:900px){.xd4-header{position:relative;background:var(--xd8-purple-dark)}.xd8-about__grid{grid-template-columns:1fr}.xd3-steps,.xd2-service-grid,.xd-testimonial-grid{grid-template-columns:1fr 1fr}.xd-mosaic-card,.xd-mosaic-card:nth-child(n){grid-column:span 6}}
@media(max-width:720px){:root{--xd4-container:min(100% - 30px,1280px)}.xd4-hero__copy{width:100%}.xd4-hero__veil{background:rgba(40,18,88,.78)}.xd4-hero h1{font-size:49px}.xd4-section,.xd3-process,.xd2-section,.xd-section,.xd2-contact{padding:76px 0}.xd8-about__media{min-height:430px}.xd8-about__media img{width:100%;height:410px}.xd8-about__badge{width:150px;height:150px;border-width:9px}.xd3-process__title{display:block}.xd3-steps,.xd2-service-grid,.xd-testimonial-grid{grid-template-columns:1fr}.xd-mosaic-card,.xd-mosaic-card:nth-child(n){grid-column:1/-1}.xd2-contact__panel{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}[data-xd-reveal]{opacity:1;transform:none;transition:none}}
</style>
