@php
  $blocks=collect($landingBlocks??[])->values();$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null);$blockUpdateUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.update',['block'=>'__BLOCK_ID__']):'';$blockSourcePreviewUrlTemplate=$canEditLanding?route('admin.api.landing.blocks.source-preview',['block'=>'__BLOCK_ID__']):'';$blockPayload=$canEditLanding?$blocks->keyBy('id')->toArray():[];$editorLocales=collect(\App\Support\FrontendLocalization::supportedLocales())->map(fn($locale)=>['code'=>$locale,'label'=>strtoupper($locale)])->all();
  $get=fn(string $type):array=>(array)($blocks->firstWhere('block_type',$type)??[]);$items=fn(array $block)=>collect($block['dynamic_items']??[])->filter()->values()->whenEmpty(fn($list)=>$list->push(...collect(data_get($block,'data.content.items',[]))->filter()->values()->all()));$image=fn($item,string $fallback)=>data_get($item,'image',data_get($item,'image_url',$fallback));$money=fn($value)=>(float)$value>0?number_format((float)$value,0,',','.').'đ':'Liên hệ';
  $hero=$get('hero_slider');$cats=$get('e802_categories');$deals=$get('e802_deals');$campaigns=$get('e802_campaigns');$featured=$get('e802_featured');$catalog=$get('e802_catalog');$best=$get('e802_best');$parts=$get('e802_parts');$brands=$get('e802_brands');$testimonials=$get('e802_testimonials');$news=$get('e802_news');$benefits=$get('e802_benefits');$slides=collect($hero['dynamic_items']??data_get($hero,'data.content.slides',[]));
  $card=function($item)use($image,$money){@endphp<article class="e802-product"><a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,asset('themes/E802/images/sport-banner.png')) }}" alt="{{ data_get($item,'title',data_get($item,'name')) }}"></a><i class="fa-regular fa-heart"></i><h3>{{ data_get($item,'title',data_get($item,'name')) }}</h3><strong class="e802-price">Giá: {{ $money(data_get($item,'price')) }}</strong>@if(data_get($item,'original_price'))<del>{{ $money(data_get($item,'original_price')) }}</del>@endif</article>@php };
@endphp
@extends('theme-e802::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','E802')))
@section('content')
<main>
<section class="e802-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider"><img src="{{ $image($slides->first(),asset('themes/E802/images/hero-moto.png')) }}" alt="E802 Moto"><div class="e802-container e802-hero-copy"><div><h1>{{ data_get($hero,'data.title','Một lựa chọn') }} <b>{{ data_get($hero,'data.subtitle','chuẩn phong cách') }}</b></h1><p>{{ data_get($hero,'data.description','Khám phá hành trình đô thị theo cách của bạn.') }}</p></div></div></section>

<section class="e802-section xd-landing-block" data-landing-block-id="{{ data_get($cats,'id') }}" data-block-type="e802_categories"><div class="e802-container"><h2 class="e802-title">Danh mục <b>nổi bật</b></h2><div class="e802-categories">@foreach($items($cats) as $item)<a class="e802-category" href="{{ data_get($item,'url','#san-pham') }}"><img src="{{ $image($item,asset('themes/E802/images/hero-moto.png')) }}" alt="{{ data_get($item,'title') }}"><div><i class="fa-solid fa-arrow-right"></i>{{ data_get($item,'title') }}</div></a>@endforeach</div></div></section>

<section class="e802-section xd-landing-block" data-landing-block-id="{{ data_get($deals,'id') }}" data-block-type="e802_deals"><div class="e802-container"><h2 class="e802-title">Deal <b>nổi bật</b> 🔥</h2><div class="e802-deal-box"><div class="e802-deal-status">{{ data_get($deals,'data.description','Ưu đãi giới hạn dành cho khách hàng đặt xe sớm!') }}</div><div class="e802-products">@foreach($items($deals)->take(5) as $item){{ $card($item) }}@endforeach</div><a class="e802-more" href="#san-pham">Xem tất cả</a></div></div></section>

<section class="e802-section xd-landing-block" data-landing-block-id="{{ data_get($campaigns,'id') }}" data-block-type="e802_campaigns"><div class="e802-container e802-campaigns">@foreach($items($campaigns)->take(2) as $item)<article class="e802-campaign"><img src="{{ $image($item,asset('themes/E802/images/sport-banner.png')) }}" alt="{{ data_get($item,'title') }}"><div><h3>{{ data_get($item,'title') }} <b>{{ data_get($item,'subtitle') }}</b></h3></div></article>@endforeach</div></section>

<section class="e802-section xd-landing-block" data-landing-block-id="{{ data_get($featured,'id') }}" data-block-type="e802_featured"><div class="e802-container"><h2 class="e802-title">Sản phẩm <b>nổi bật</b></h2><div class="e802-featured"><div class="e802-featured-banner"><img src="{{ asset('themes/E802/images/hero-moto.png') }}" alt="Hành trình nổi bật"><div><h2>Sống động từng hành trình</h2></div></div><div class="e802-featured-products"><div class="e802-products">@foreach($items($featured)->take(2) as $item){{ $card($item) }}@endforeach</div></div></div></div></section>

<section id="san-pham" class="e802-section xd-landing-block" data-landing-block-id="{{ data_get($catalog,'id') }}" data-block-type="e802_catalog"><div class="e802-container" data-e802-tabs><h2 class="e802-title">Tất cả <b>sản phẩm</b></h2><div class="e802-tabs"><button class="e802-tab is-active" data-e802-tab>Đô thị</button><button class="e802-tab" data-e802-tab>Thể thao</button><button class="e802-tab" data-e802-tab>Đường dài</button></div><div class="e802-catalog-layout"><div class="e802-catalog-banner"><img src="{{ asset('themes/E802/images/hero-moto.png') }}" alt="Bộ sưu tập xe máy"></div><div class="e802-products">@foreach($items($catalog)->take(9) as $item){{ $card($item) }}@endforeach</div></div></div></section>

<section class="e802-section xd-landing-block" data-landing-block-id="{{ data_get($best,'id') }}" data-block-type="e802_best"><div class="e802-container"><h2 class="e802-title">Sản phẩm <b>bán chạy</b></h2><div class="e802-products">@foreach($items($best)->take(5) as $item){{ $card($item) }}@endforeach</div></div></section>

<section class="e802-section xd-landing-block" data-landing-block-id="{{ data_get($parts,'id') }}" data-block-type="e802_parts"><div class="e802-container e802-parts">@foreach(data_get($parts,'data.content.groups',[]) as $group)<section><h2>Phụ tùng <b>{{ data_get($group,'title') }}</b></h2><div class="e802-part-list">@foreach(data_get($group,'items',[]) as $item)<article class="e802-part"><img src="{{ asset('themes/E802/images/sport-banner.png') }}" alt="{{ data_get($item,'title') }}"><div><h3>{{ data_get($item,'title') }}</h3><strong class="e802-price">Giá: {{ data_get($item,'price') }}</strong></div></article>@endforeach</div></section>@endforeach</div></section>

<section id="thuong-hieu" class="e802-section xd-landing-block" data-landing-block-id="{{ data_get($brands,'id') }}" data-block-type="e802_brands"><div class="e802-container"><h2 class="e802-title">Thương hiệu <b>nổi bật</b></h2><div class="e802-brands">@foreach($items($brands) as $item)<article class="e802-brand"><i class="fa-solid fa-motorcycle"></i><h3>{{ data_get($item,'title') }}</h3><span>{{ data_get($item,'title') }}</span></article>@endforeach</div></div></section>

@php $reviewItems=collect(data_get($testimonials,'data.content.items',[])); @endphp
<section class="e802-section e802-testimonials xd-landing-block" data-landing-block-id="{{ data_get($testimonials,'id') }}" data-block-type="e802_testimonials"><div class="e802-container"><h2 class="e802-title">Đánh giá khách hàng</h2><div class="e802-testimonials-grid">@foreach($reviewItems->take(2) as $item)<article class="e802-quote"><p>{{ data_get($item,'summary') }}</p><div class="e802-person"><i class="fa-solid fa-user"></i><div><h3>{{ data_get($item,'title') }}</h3><span>Khách hàng thành viên</span></div></div></article>@endforeach</div></div></section>

<section id="tin-tuc" class="e802-section xd-landing-block" data-landing-block-id="{{ data_get($news,'id') }}" data-block-type="e802_news"><div class="e802-container"><h2 class="e802-title" style="text-align:left">Tin tức <b>mới nhất</b></h2>@php $newsItems=$items($news); @endphp<div class="e802-news">@foreach($newsItems->take(2) as $item)<article class="e802-news-card"><img src="{{ $image($item,asset('themes/E802/images/hero-moto.png')) }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></article>@endforeach<div class="e802-news-list">@foreach($newsItems->skip(2)->take(4) as $item)<a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,asset('themes/E802/images/sport-banner.png')) }}" alt=""><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></div></div></section>

<section class="e802-benefits xd-landing-block" data-landing-block-id="{{ data_get($benefits,'id') }}" data-block-type="e802_benefits"><div class="e802-container e802-benefits-grid">@foreach($items($benefits) as $item)<article><i class="{{ data_get($item,'icon','fa-solid fa-gift') }}"></i><b>{{ data_get($item,'title') }}</b><span>{{ data_get($item,'summary') }}</span></article>@endforeach</div></section>
</main>
@endsection
