@php
    $blocks = collect($landingBlocks ?? [])->values();
    $canEditLanding = auth('admin')->check() && request('mod') === 'admin' && is_array($landingPage ?? null);
    $blockUpdateUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.update', ['block' => '__BLOCK_ID__']) : '';
    $blockSourcePreviewUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.source-preview', ['block' => '__BLOCK_ID__']) : '';
    $blockPayload = $canEditLanding ? $blocks->keyBy('id')->toArray() : [];
    $editorLocales = collect(\App\Support\FrontendLocalization::supportedLocales())->map(fn ($locale) => ['code' => $locale, 'label' => strtoupper($locale)])->all();
    $get = fn (string $type): array => (array) ($blocks->firstWhere('block_type', $type) ?? []);
    $items = fn (array $block) => collect($block['dynamic_items'] ?? [])->filter()->values()->whenEmpty(fn ($list) => $list->push(...collect(data_get($block, 'data.content.items', []))->filter()->values()->all()));
    $image = fn ($item, string $fallback) => data_get($item, 'image', data_get($item, 'image_url', $fallback));
    $money = fn ($value) => (float) $value > 0 ? number_format((float) $value, 0, ',', '.').'đ' : 'Liên hệ';
    $discount = fn ($item) => ((float) data_get($item, 'original_price') > (float) data_get($item, 'price') && (float) data_get($item, 'original_price') > 0) ? round((1 - (float) data_get($item, 'price') / (float) data_get($item, 'original_price')) * 100) : 0;
    $hero = $get('hero_slider'); $benefits = $get('shop601_benefits'); $collections = $get('shop601_collection_cards'); $flash = $get('shop601_flash_sale'); $ads = $get('shop601_ads'); $grid = $get('shop601_product_grid'); $feature = $get('shop601_feature_collection'); $popular = $get('shop601_product_carousel'); $reviews = $get('testimonials'); $tiktok = $get('shop601_tiktok'); $latest = $get('shop601_latest_content');
    $slides = collect($hero['dynamic_items'] ?? [])->filter()->values(); if ($slides->isEmpty()) $slides = collect(data_get($hero, 'data.content.slides', []))->filter()->values();
    $productCard = function ($item, string $class = '') use ($image, $money, $discount) { $off = $discount($item); @endphp
        <article class="s601-product {{ $class }}"><a class="s601-product__image" href="{{ data_get($item, 'url', '#') }}"><span class="s601-badge">{{ data_get($item, 'badge', 'Hàng mới') }}</span><img src="{{ $image($item, 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=800&q=85') }}" alt="{{ data_get($item, 'title') }}"></a><div class="s601-product__body"><small>{{ data_get($item, 'summary', 'BEAN STYLE') }}</small><h3><a href="{{ data_get($item, 'url', '#') }}">{{ data_get($item, 'title') }}</a></h3><strong>{{ $money(data_get($item, 'price')) }}</strong>@if($off)<em>-{{ $off }}%</em>@endif @if(data_get($item, 'original_price'))<del>{{ $money(data_get($item, 'original_price')) }}</del>@endif</div></article>
    @php };
@endphp
@extends('theme-shop601::layout')
@section('title', data_get($landingPage ?? [], 'meta_title', data_get($siteProfile ?? [], 'site_name', 'SHOP601')))
@section('content')
<main class="s601-main">
    <section class="s601-hero xd-landing-block" data-landing-block-id="{{ data_get($hero, 'id') }}" data-block-type="hero_slider" data-s601-slider data-autoplay="{{ data_get($hero, 'settings.autoplay_ms', 6000) }}">@foreach($slides as $i => $slide)<article class="s601-hero__slide {{ $i === 0 ? 'is-active' : '' }}" data-s601-slide><img src="{{ $image($slide, 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=2200&q=90') }}" alt="{{ data_get($slide, 'title') }}"><div class="s601-hero__shade"></div><div class="s601-container s601-hero__copy"><p>{{ data_get($slide, 'kicker', data_get($hero, 'data.subtitle')) }}</p><h1>{{ data_get($slide, 'title', data_get($hero, 'data.title')) }}</h1><span>{{ data_get($slide, 'summary', data_get($hero, 'data.description')) }}</span><a href="{{ data_get($slide, 'link_url', '#san-pham') }}">{{ data_get($slide, 'button_label', data_get($hero, 'data.button_label', 'Khám phá ngay')) }}</a></div></article>@endforeach<button data-s601-prev aria-label="Trước"><i class="fa-solid fa-chevron-left"></i></button><button data-s601-next aria-label="Sau"><i class="fa-solid fa-chevron-right"></i></button></section>

    <section id="{{ data_get($benefits, 'anchor_id', 'cam-ket') }}" class="s601-benefits xd-landing-block" data-landing-block-id="{{ data_get($benefits, 'id') }}" data-block-type="shop601_benefits"><div class="s601-container s601-benefits__grid">@foreach($items($benefits) as $item)<article><i class="{{ data_get($item, 'icon', 'fa-solid fa-check') }}"></i><div><h3>{{ data_get($item, 'title') }}</h3><p>{{ data_get($item, 'summary') }}</p></div></article>@endforeach</div></section>

    <section id="{{ data_get($collections, 'anchor_id', 'bo-suu-tap') }}" class="s601-section xd-landing-block" data-landing-block-id="{{ data_get($collections, 'id') }}" data-block-type="shop601_collection_cards"><div class="s601-container"><div class="s601-collection-grid">@foreach($items($collections) as $item)<a href="{{ data_get($item, 'url', '#') }}"><img src="{{ $image($item, 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item, 'title') }}"><span><b>{{ data_get($item, 'title') }}</b><u>{{ data_get($collections, 'data.button_label', 'Xem chi tiết') }}</u></span></a>@endforeach</div></div></section>

    <section id="{{ data_get($flash, 'anchor_id', 'flash-sale') }}" class="s601-section xd-landing-block" data-landing-block-id="{{ data_get($flash, 'id') }}" data-block-type="shop601_flash_sale"><div class="s601-container s601-flash"><header><h2>⚡ {{ data_get($flash, 'data.title', 'FLASH SALE') }}</h2><p>{{ data_get($flash, 'data.description') }}</p><time data-s601-countdown="{{ data_get($flash, 'settings.ends_at') }}">00 : 00 : 00</time></header><div class="s601-products s601-products--five">@foreach($items($flash) as $item){{ $productCard($item) }}@endforeach</div></div></section>

    <section id="{{ data_get($ads, 'anchor_id', 'khuyen-mai') }}" class="s601-section xd-landing-block" data-landing-block-id="{{ data_get($ads, 'id') }}" data-block-type="shop601_ads"><div class="s601-container s601-ads">@foreach($items($ads) as $item)<a href="{{ data_get($item, 'url', '#') }}"><img src="{{ $image($item, 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1400&q=85') }}" alt="{{ data_get($item, 'title') }}"><span>{{ data_get($item, 'title') }}</span></a>@endforeach</div></section>

    <section id="{{ data_get($grid, 'anchor_id', 'san-pham') }}" class="s601-section xd-landing-block" data-landing-block-id="{{ data_get($grid, 'id') }}" data-block-type="shop601_product_grid"><div class="s601-container"><header class="s601-heading"><h2>{{ data_get($grid, 'data.title') }}</h2><p>{{ data_get($grid, 'data.description') }}</p></header><div class="s601-products s601-products--five">@foreach($items($grid) as $item){{ $productCard($item) }}@endforeach</div><a class="s601-more" href="{{ route('site.catalog.search') }}">{{ data_get($grid, 'data.button_label', 'Xem tất cả') }}</a></div></section>

    @php $featureItems = $items($feature); $lead = $featureItems->first(); @endphp
    <section id="{{ data_get($feature, 'anchor_id', 'bo-suu-tap-noi-bat') }}" class="s601-section xd-landing-block" data-landing-block-id="{{ data_get($feature, 'id') }}" data-block-type="shop601_feature_collection"><div class="s601-container s601-feature">@if($lead)<a class="s601-feature__lead" href="{{ data_get($lead, 'url', '#') }}"><img src="{{ $image($lead, 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1100&q=90') }}" alt="{{ data_get($lead, 'title') }}"><span>{{ data_get($lead, 'title') }}</span></a>@endif<div class="s601-feature__body"><p>{{ data_get($feature, 'data.subtitle') }}</p><h2>{{ data_get($feature, 'data.title') }}</h2><a class="s601-more" href="{{ data_get($feature, 'settings.cta_url', '#san-pham') }}">{{ data_get($feature, 'data.button_label') }}</a><div class="s601-feature__products">@foreach($featureItems->skip(1) as $item){{ $productCard($item, 'is-small') }}@endforeach</div></div></div></section>

    <section id="{{ data_get($popular, 'anchor_id', 'pho-bien') }}" class="s601-section xd-landing-block" data-landing-block-id="{{ data_get($popular, 'id') }}" data-block-type="shop601_product_carousel"><div class="s601-container"><header class="s601-heading"><h2>{{ data_get($popular, 'data.title') }}</h2><p>{{ data_get($popular, 'data.description') }}</p></header><div class="s601-products s601-products--five">@foreach($items($popular) as $item){{ $productCard($item) }}@endforeach</div></div></section>

    <section id="{{ data_get($reviews, 'anchor_id', 'danh-gia') }}" class="s601-section s601-reviews xd-landing-block" data-landing-block-id="{{ data_get($reviews, 'id') }}" data-block-type="testimonials"><div class="s601-container"><header class="s601-heading"><h2>{{ data_get($reviews, 'data.title') }}</h2><p>{{ data_get($reviews, 'data.description') }}</p></header><div class="s601-review-grid">@foreach($items($reviews) as $item)<article><b>”</b><p>{{ data_get($item, 'quote', data_get($item, 'summary')) }}</p><div><img src="{{ $image($item, 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=85') }}" alt="{{ data_get($item, 'name') }}"><span><strong>{{ data_get($item, 'name', data_get($item, 'title')) }}</strong><small>{{ data_get($item, 'role', data_get($item, 'company')) }}</small><em>★★★★★</em></span></div></article>@endforeach</div></div></section>

    <section id="{{ data_get($tiktok, 'anchor_id', 'tiktok') }}" class="s601-section s601-tiktok xd-landing-block" data-landing-block-id="{{ data_get($tiktok, 'id') }}" data-block-type="shop601_tiktok"><div class="s601-container s601-tiktok__grid"><div class="s601-tiktok__embed">{!! data_get($tiktok, 'data.content.embed_html', '<div class="s601-tiktok-placeholder"><i class="fa-brands fa-tiktok"></i><b>TikTok</b></div>') !!}</div><div><p>{{ data_get($tiktok, 'data.subtitle') }}</p><h2>{{ data_get($tiktok, 'data.title') }}</h2><span>{{ data_get($tiktok, 'data.description') }}</span><a class="s601-more" href="{{ data_get($tiktok, 'settings.cta_url', 'https://www.tiktok.com/') }}" target="_blank" rel="noopener">{{ data_get($tiktok, 'data.button_label') }}</a></div></div></section>

    <section id="{{ data_get($latest, 'anchor_id', 'tin-tuc') }}" class="s601-section xd-landing-block" data-landing-block-id="{{ data_get($latest, 'id') }}" data-block-type="shop601_latest_content"><div class="s601-container"><header class="s601-heading"><h2>{{ data_get($latest, 'data.title') }}</h2><p>{{ data_get($latest, 'data.description') }}</p></header><div class="s601-news-grid">@foreach($items($latest) as $item)<article><a href="{{ data_get($item, 'url', '#') }}"><img src="{{ $image($item, 'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item, 'title') }}"></a><time>{{ data_get($item, 'published_at', now()->format('d/m/Y')) }}</time><h3><a href="{{ data_get($item, 'url', '#') }}">{{ data_get($item, 'title') }}</a></h3><p>{{ \Illuminate\Support\Str::limit(strip_tags((string) data_get($item, 'summary')), 115) }}</p><a href="{{ data_get($item, 'url', '#') }}">Đọc tiếp &gt;&gt;</a></article>@endforeach</div><a class="s601-more" href="{{ data_get($latest, 'settings.source') === 'cms_services' ? route('site.services.index') : route('site.blog.index') }}">{{ data_get($latest, 'data.button_label', 'Xem tất cả') }}</a></div></section>
</main>
@endsection
