<style>
:root{--dn-navy:#465474;--dn-navy-deep:#2f3b58;--dn-champagne:#e7cc98;--dn-cream:#f7f4ee;--dn-ink:#36425f;--dn-white:#fff;--dn-muted:#748098;--dn-shadow:0 24px 70px rgba(41,50,74,.13);--dn-display:'Chakra Petch','Arial Narrow',sans-serif;--dn-body:'Manrope','Segoe UI',sans-serif}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--dn-ink);background:#fff;font-family:var(--dn-body);line-height:1.65}.dn302-page{overflow:hidden}img{display:block;max-width:100%}a{color:inherit;text-decoration:none}button,input,textarea{font:inherit}.dn-container{width:min(1680px,calc(100% - 64px));margin-inline:auto}.dn-display,h1,h2,h3{font-family:var(--dn-display);font-weight:600;line-height:1.13}.dn-section{position:relative;padding:110px 0}.dn-eyebrow{margin:0 0 18px;color:var(--dn-champagne);font-family:var(--dn-display);font-weight:600;letter-spacing:.22em;text-transform:uppercase}.dn-title{margin:0;font-size:clamp(40px,4vw,68px);color:var(--dn-ink)}.dn-heading{margin-bottom:56px}.dn-heading.center{text-align:center}.dn-heading p:last-child{max-width:900px;margin:20px auto 0;color:var(--dn-muted);font-size:17px}.dn-btn{display:inline-flex;align-items:center;justify-content:center;gap:16px;min-height:72px;padding:0 42px;border:0;background:var(--dn-champagne);color:var(--dn-ink);font-family:var(--dn-display);font-weight:600;text-transform:uppercase;letter-spacing:.03em;cursor:pointer;transition:.25s ease}.dn-btn:hover{background:#f1dbae;transform:translateY(-3px)}

/* DN Square: custom display treatment built from a Vietnamese-complete geometric face. */
.dn-title,.dn-hero h1,.dn-card h3,.dn-stat strong{font-feature-settings:'ss01' 1,'kern' 1;letter-spacing:-.035em}

.dn-header{position:absolute;z-index:20;top:0;left:0;width:100%;padding-top:4px}.dn-header-inner{display:grid;grid-template-columns:325px 1fr;background:#fff;box-shadow:0 12px 38px rgba(21,30,51,.08)}.dn-logo{display:flex;align-items:center;justify-content:center;gap:14px;min-height:176px;background:#fff}.dn-logo img{max-width:230px;max-height:115px}.dn-logo i{font-size:70px;color:var(--dn-champagne)}.dn-logo span{font-size:42px;font-weight:700;line-height:.88;color:var(--dn-navy);letter-spacing:.02em}.dn-logo small{display:block;margin-top:12px;font-size:14px;letter-spacing:.02em}.dn-head-main{min-width:0}.dn-topbar{height:68px;display:flex;align-items:center;gap:22px;padding:0 28px;background:var(--dn-navy);color:#fff;font-size:14px;font-weight:600}.dn-topbar>a{margin-left:auto}.dn-topbar i{margin-right:7px}.dn-socials{display:flex;gap:15px}.dn-auth-actions{display:flex;align-items:center;gap:7px;white-space:nowrap}.dn-auth-actions a,.dn-auth-actions button{border:0;background:transparent;padding:4px 0;color:#fff;font:inherit;font-weight:700;cursor:pointer}.dn-auth-actions a:hover,.dn-auth-actions button:hover{color:var(--dn-champagne)}.dn-auth-mobile{display:none}.dn-navbar{height:108px;display:flex;align-items:stretch;background:var(--dn-champagne)}.dn-navbar nav{display:flex;align-items:stretch;flex:1}.dn-navbar nav a{display:flex;align-items:center;padding:0 26px;font-size:17px;font-weight:600;transition:.2s}.dn-navbar nav a:hover{background:rgba(255,255,255,.32)}.dn-consult{display:flex;align-items:center;padding:0 35px;background:rgba(70,84,116,.08);font-family:var(--dn-display);font-size:18px;font-weight:600;text-transform:uppercase}.dn-menu-toggle{display:none}

.dn-hero{min-height:1000px;padding-top:270px;background:var(--dn-navy);color:#fff}.dn-hero::before,.dn-hero::after{content:'';position:absolute;pointer-events:none}.dn-hero::before{width:320px;height:190px;right:5%;top:245px;background:repeating-linear-gradient(135deg,transparent 0 24px,rgba(255,255,255,.68) 25px 28px,transparent 29px 52px)}.dn-hero::after{width:360px;height:105px;right:9%;bottom:48px;background:repeating-linear-gradient(135deg,var(--dn-champagne) 0 28px,var(--dn-navy) 29px 33px,var(--dn-champagne) 34px 62px)}.dn-hero-stage{position:relative;display:grid;grid-template-columns:47% 53%;align-items:center;min-height:650px}.dn-hero-copy{position:relative;z-index:3;padding-right:65px}.dn-hero-copy .dn-eyebrow{font-size:16px}.dn-hero h1{margin:0 0 36px;font-size:clamp(54px,5.1vw,92px);color:#fff}.dn-hero-copy>p:not(.dn-eyebrow){max-width:760px;margin:0 0 46px;padding-top:34px;border-top:1px solid rgba(255,255,255,.3);font-size:18px;color:#edf0f6}.dn-hero-media{position:relative;z-index:2;height:650px}.dn-hero-media::before{content:'';position:absolute;z-index:-1;inset:-26px 14% auto 14%;height:70px;background:var(--dn-champagne)}.dn-hero-media::after{content:'';position:absolute;left:-30px;bottom:-35px;width:165px;height:335px;border-left:8px solid #fff;border-bottom:8px solid #fff}.dn-hero-slide{position:absolute;inset:0;opacity:0;transform:scale(1.04);transition:opacity .7s ease,transform 1.2s ease}.dn-hero-slide.is-active{opacity:1;transform:scale(1)}.dn-hero-slide img{width:100%;height:100%;object-fit:cover}.dn-hero-dots{position:absolute;z-index:4;bottom:-82px;left:50%;display:flex;gap:12px;transform:translateX(-50%)}.dn-hero-dots button{width:13px;height:13px;padding:0;border:0;background:#65708c}.dn-hero-dots button.is-active{background:var(--dn-champagne)}

.dn-about-grid{display:grid;grid-template-columns:52% 48%;align-items:center}.dn-about-media{position:relative;padding:65px 0 0 70px}.dn-about-media::before{content:'';position:absolute;z-index:-1;top:0;left:0;width:52%;height:52%;background:var(--dn-champagne)}.dn-about-media::after{content:'';position:absolute;left:30px;bottom:-45px;width:58%;height:45%;border-left:3px solid var(--dn-navy);border-bottom:3px solid var(--dn-navy)}.dn-about-media img{width:100%;height:680px;object-fit:cover}.dn-about-copy{padding-left:85px}.dn-about-copy .dn-title{max-width:770px}.dn-about-copy>p:not(.dn-eyebrow){font-size:17px;color:var(--dn-muted);margin:35px 0}.dn-values{display:grid;grid-template-columns:1fr 1fr;gap:26px}.dn-value{display:flex;align-items:center;gap:18px;min-height:80px;padding:18px 24px;background:#f8f8f8;text-transform:uppercase;font-weight:600}.dn-value i{display:grid;place-items:center;width:52px;height:52px;border-radius:50%;background:var(--dn-champagne);color:var(--dn-navy)}

.dn-services{background:var(--dn-navy);color:#fff}.dn-services-head{display:grid;grid-template-columns:42% 58%;gap:60px;align-items:start}.dn-services .dn-title{color:#fff}.dn-services-head>p{margin:8px 0 0;font-size:18px;line-height:2;color:#e2e7f0}.dn-service-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:40px;margin-top:58px}.dn-card{background:#fff;color:var(--dn-ink);box-shadow:var(--dn-shadow)}.dn-service-image{height:420px;overflow:hidden}.dn-service-image img{width:100%;height:100%;object-fit:cover;transition:transform .6s ease}.dn-card:hover .dn-service-image img{transform:scale(1.055)}.dn-service-body{position:relative;min-height:280px;padding:56px 40px 45px;text-align:center}.dn-service-body h3{position:absolute;top:-38px;left:8%;width:84%;margin:0;padding:22px 16px;background:#fff;font-size:23px;text-transform:uppercase}.dn-service-body p{color:var(--dn-muted);font-size:16px}.dn-round-link{position:absolute;left:50%;bottom:-31px;display:grid;place-items:center;width:62px;height:62px;border-radius:50%;background:var(--dn-champagne);transform:translateX(-50%);transition:.25s}.dn-round-link:hover{transform:translateX(-50%) rotate(-35deg);background:#fff}

.dn-glass-grid{display:grid;grid-template-columns:48% 52%;align-items:start}.dn-glass-image{height:830px;object-fit:cover}.dn-glass-copy{padding:22px 0 0 95px}.dn-glass-copy>p:last-of-type{margin:35px 0 55px;color:var(--dn-muted);font-size:18px}.dn-feature-table{display:grid;grid-template-columns:repeat(3,1fr);margin-left:-210px;background:#fff;box-shadow:var(--dn-shadow)}.dn-feature{display:grid;place-items:center;min-height:195px;padding:28px;border-right:1px solid #ddd;border-bottom:1px solid #ddd;text-align:center;font-family:var(--dn-display);font-size:22px}.dn-feature:nth-child(3n){border-right:0}.dn-feature:nth-last-child(-n+3){border-bottom:0}.dn-feature i{font-size:46px;color:var(--dn-navy)}

.dn-projects .dn-heading{text-align:center}.dn-project-tabs{display:flex;justify-content:center;gap:18px;margin:0 0 42px}.dn-project-tabs button{padding:18px 42px;border:0;background:transparent;color:var(--dn-navy);font-family:var(--dn-display);font-size:18px;font-weight:600;cursor:pointer}.dn-project-tabs button.is-active{background:var(--dn-champagne)}.dn-project-grid{display:grid;grid-template-columns:1.2fr 1.2fr 1fr;grid-template-rows:290px 290px;gap:24px}.dn-project{position:relative;overflow:hidden}.dn-project:first-child{grid-row:1/2}.dn-project:nth-child(2){grid-row:1/3}.dn-project:nth-child(3){grid-row:1/3}.dn-project:nth-child(4){grid-column:1;grid-row:2}.dn-project img{width:100%;height:100%;object-fit:cover;transition:transform .65s}.dn-project::after{content:attr(data-title);position:absolute;inset:auto 0 0;padding:50px 24px 22px;background:linear-gradient(transparent,rgba(29,37,57,.82));color:#fff;font-family:var(--dn-display);font-size:21px;opacity:0;transition:.3s}.dn-project:hover img{transform:scale(1.06)}.dn-project:hover::after{opacity:1}

.dn-styles-grid{display:grid;grid-template-columns:1fr 1.65fr;gap:60px;align-items:center}.dn-style-cards{display:grid;grid-template-columns:1fr 1fr;gap:28px}.dn-style-card{display:grid;place-items:center;min-height:270px;padding:25px;background:#fff;box-shadow:var(--dn-shadow);text-align:center;transition:.28s}.dn-style-card:hover{transform:translateY(-9px);background:var(--dn-cream)}.dn-style-card i{font-size:65px;color:var(--dn-navy)}.dn-style-card h3{margin:24px 0 0;font-size:22px;text-transform:uppercase}.dn-styles-image{position:relative}.dn-styles-image img{width:100%;height:620px;object-fit:cover}.dn-styles-image .dn-btn{position:absolute;right:0;bottom:0}

.dn-newsletter-wrap{padding:75px 0;background:linear-gradient(#fff 50%,var(--dn-navy) 50%)}.dn-newsletter{display:grid;grid-template-columns:1fr 1.1fr;align-items:center;gap:70px;padding:60px 68px;background:var(--dn-champagne)}.dn-newsletter .dn-title{font-size:42px}.dn-newsletter form{display:flex;height:92px;background:#fff}.dn-newsletter input{flex:1;min-width:0;border:0;padding:0 28px;outline:0}.dn-newsletter button{min-width:230px;border:14px solid #fff;background:var(--dn-champagne);font-family:var(--dn-display);font-size:19px;font-weight:700;text-transform:uppercase;cursor:pointer}

.dn-testimonials{background:var(--dn-navy);color:#fff}.dn-testimonial-head{display:grid;grid-template-columns:40% 60%;align-items:start;gap:70px}.dn-testimonials .dn-title{color:#fff}.dn-testimonial-head>p{font-size:17px;color:#e0e5ef}.dn-testimonial-layout{display:grid;grid-template-columns:390px 1fr;gap:80px;margin-top:55px}.dn-stats{display:grid;gap:18px}.dn-stat{display:grid;grid-template-columns:125px 1fr;align-items:center;gap:25px}.dn-stat i{display:grid;place-items:center;height:125px;background:#596684;color:var(--dn-champagne);font-size:38px}.dn-stat strong{display:block;font-size:45px}.dn-stat span{font-weight:600}.dn-quotes{display:grid;grid-template-columns:1fr 1fr;gap:36px}.dn-quote{min-height:330px;padding:50px;background:#fff;color:var(--dn-ink);border-radius:4px}.dn-quote-top{display:flex;align-items:center;gap:22px;margin-bottom:40px}.dn-quote img{width:90px;height:90px;border-radius:50%;object-fit:cover}.dn-quote h3{margin:0;font-size:20px}.dn-quote p{font-size:17px;color:var(--dn-muted)}

.dn-news-head{display:flex;align-items:flex-end;justify-content:space-between}.dn-news-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:52px}.dn-news-card{position:relative;background:#fff;box-shadow:var(--dn-shadow)}.dn-news-card>a>img{width:100%;height:380px;object-fit:cover}.dn-news-body{min-height:270px;padding:65px 42px 35px;text-align:center}.dn-news-date{position:absolute;top:350px;left:50%;padding:14px 28px;background:var(--dn-champagne);transform:translateX(-50%)}.dn-news-body h3{font-size:23px}.dn-news-body a{display:inline-flex;gap:10px;align-items:center;margin-top:18px;font-family:var(--dn-display);font-weight:600;text-transform:uppercase}

.dn-contact .dn-heading{text-align:center}.dn-contact-grid{display:grid;grid-template-columns:42% 58%;align-items:stretch}.dn-contact-info{position:relative;min-height:720px}.dn-contact-info>img{width:100%;height:100%;object-fit:cover}.dn-contact-panel{position:absolute;left:7%;right:7%;bottom:30px;padding:32px 38px;background:rgba(255,255,255,.92)}.dn-contact-panel p{display:flex;gap:22px;align-items:center;font-weight:600}.dn-contact-panel i{font-size:30px}.dn-contact-form{padding:70px;background:var(--dn-champagne)}.dn-contact-form form{display:grid;grid-template-columns:1fr 1fr;gap:24px}.dn-contact-form input,.dn-contact-form textarea{width:100%;border:0;background:#fff;padding:22px 24px;outline:0}.dn-contact-form textarea{grid-column:1/-1;min-height:190px;resize:vertical}.dn-contact-form .dn-btn{grid-column:1/-1;background:var(--dn-navy);color:#fff}

.dn-partners{padding:80px 0;background:#fafafa}.dn-partner-track{display:grid;grid-template-columns:repeat(5,1fr);gap:25px;align-items:center}.dn-partner{display:flex;align-items:center;justify-content:center;min-height:130px;padding:25px;background:#fff;color:var(--dn-navy);font-family:var(--dn-display);font-size:24px;font-weight:700;text-align:center}.dn-partner img{max-height:70px;filter:grayscale(1)}

.dn-footer{position:relative;padding:70px 0 0;background:var(--dn-navy);color:#fff}.dn-footer-row{display:grid;grid-template-columns:1fr 1fr 1fr;align-items:center;gap:50px}.dn-social-list{display:flex;gap:16px}.dn-social-list a{display:grid;place-items:center;width:52px;height:52px;border-radius:50%;background:#596684}.dn-logo-footer{min-height:auto;background:transparent;color:#fff}.dn-logo-footer img{max-width:210px;max-height:90px;padding:8px 12px;border-radius:10px;background:#fff}.dn-logo-footer i{font-size:58px}.dn-logo-footer span{color:#fff;font-size:34px}.dn-footer-row>p{text-align:center;font-size:17px}.dn-footer-copy{margin-top:55px;padding:22px;text-align:center;background:rgba(0,0,0,.12)}.dn-to-top{position:absolute;right:32px;bottom:18px;display:grid;place-items:center;width:58px;height:58px;background:var(--dn-navy-deep)}

.dn-inner-hero{padding:270px 0 100px;background:var(--dn-navy);color:#fff}.dn-inner-hero h1{margin:0;font-size:64px}.dn-list-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:35px}.dn-list-card{background:#fff;box-shadow:var(--dn-shadow)}.dn-list-card img{width:100%;height:320px;object-fit:cover}.dn-list-card div{padding:28px}.dn-content-card{max-width:1000px;margin:auto;background:#fff;box-shadow:var(--dn-shadow);padding:70px}.dn-content-cover{width:100%;max-height:620px;object-fit:cover;margin:35px 0}.dn-richtext{font-size:17px;color:#58637a}.dn-richtext img{height:auto}.dn-cart-table{width:100%;border-collapse:collapse}.dn-cart-table td,.dn-cart-table th{padding:18px;border-bottom:1px solid #ddd;text-align:left}

/* Scroll choreography. Content is hidden only after JS is ready. */
.dn-motion-ready [data-dn-reveal]{opacity:0;transform:translate3d(0,56px,0);transition:opacity .75s cubic-bezier(.2,.7,.25,1),transform .85s cubic-bezier(.2,.7,.25,1);transition-delay:var(--dn-delay,0ms)}.dn-motion-ready [data-dn-reveal="left"]{transform:translate3d(-70px,0,0)}.dn-motion-ready [data-dn-reveal="right"]{transform:translate3d(70px,0,0)}.dn-motion-ready [data-dn-reveal="scale"]{transform:scale(.93)}.dn-motion-ready [data-dn-reveal].is-visible{opacity:1;transform:none}.dn-header.is-compact{position:fixed;padding:0;animation:dnDrop .4s ease}.dn-header.is-compact .dn-logo{min-height:82px}.dn-header.is-compact .dn-logo i{font-size:45px}.dn-header.is-compact .dn-logo span{font-size:29px}.dn-header.is-compact .dn-topbar{display:none}.dn-header.is-compact .dn-navbar{height:82px}@keyframes dnDrop{from{transform:translateY(-100%)}to{transform:none}}

@media(max-width:1200px){.dn-container{width:min(100% - 40px,1120px)}.dn-header-inner{grid-template-columns:240px 1fr}.dn-topbar{gap:20px;padding:0 25px}.dn-topbar span:first-child{display:none}.dn-navbar nav a{padding:0 13px;font-size:15px}.dn-consult{padding:0 18px;font-size:15px}.dn-hero{min-height:850px}.dn-hero-stage{grid-template-columns:45% 55%;min-height:560px}.dn-hero-media{height:560px}.dn-about-copy{padding-left:55px}.dn-service-image{height:320px}.dn-feature-table{margin-left:-90px}.dn-contact-form{padding:45px}}
@media(max-width:900px){.dn-container{width:min(100% - 30px,760px)}.dn-section{padding:75px 0}.dn-header{position:relative;background:#fff}.dn-header-inner{width:100%;grid-template-columns:1fr;box-shadow:none}.dn-logo{justify-content:flex-start;min-height:85px;padding:0 18px}.dn-logo i{font-size:43px}.dn-logo span{font-size:29px}.dn-head-main{position:relative}.dn-topbar{display:none}.dn-navbar{height:auto;min-height:64px;align-items:center;justify-content:space-between;padding:0 18px}.dn-menu-toggle{display:flex;align-items:center;gap:10px;border:0;background:transparent;color:var(--dn-navy);font-weight:700}.dn-navbar nav{position:absolute;top:64px;left:0;right:0;z-index:30;display:none;flex-direction:column;background:#fff;box-shadow:var(--dn-shadow)}.dn-navbar nav.is-open{display:flex}.dn-navbar nav a{padding:15px 22px}.dn-auth-mobile{display:flex;gap:10px;padding:14px 22px;border-top:1px solid rgba(70,84,116,.12)}.dn-auth-mobile button{flex:1;min-height:42px;border:1px solid var(--dn-navy);background:#fff;color:var(--dn-navy);font:inherit;font-weight:700;cursor:pointer}.dn-auth-mobile button:last-child{background:var(--dn-navy);color:#fff}.dn-consult{min-height:64px}.dn-hero{min-height:auto;padding:80px 0}.dn-hero-stage{display:flex;flex-direction:column;min-height:0}.dn-hero-copy{padding:0 0 50px}.dn-hero h1{font-size:52px}.dn-hero-media{width:100%;height:480px}.dn-hero::before,.dn-hero::after{display:none}.dn-about-grid,.dn-glass-grid,.dn-styles-grid,.dn-contact-grid{grid-template-columns:1fr}.dn-about-copy{padding:80px 0 0}.dn-about-media{padding-left:35px}.dn-about-media img{height:520px}.dn-services-head,.dn-testimonial-head{grid-template-columns:1fr}.dn-service-grid{grid-template-columns:1fr 1fr}.dn-glass-copy{padding:65px 0 0}.dn-feature-table{margin:45px 0 0}.dn-project-grid{grid-template-columns:1fr 1fr;grid-template-rows:300px 300px}.dn-project:nth-child(n){grid-column:auto;grid-row:auto}.dn-newsletter{grid-template-columns:1fr}.dn-testimonial-layout{grid-template-columns:1fr}.dn-stats{grid-template-columns:repeat(3,1fr)}.dn-stat{display:block;text-align:center}.dn-stat i{height:90px}.dn-quotes,.dn-news-grid{grid-template-columns:1fr 1fr}.dn-contact-info{min-height:560px}.dn-partner-track{grid-template-columns:repeat(3,1fr)}.dn-footer-row{grid-template-columns:1fr;text-align:center}.dn-social-list{justify-content:center}.dn-footer-row>p{text-align:center}.dn-list-grid{grid-template-columns:1fr 1fr}.dn-header.is-compact{position:fixed}.dn-header.is-compact .dn-logo{display:none}}
@media(max-width:600px){.dn-container{width:calc(100% - 28px)}.dn-section{padding:60px 0}.dn-title{font-size:38px}.dn-logo{min-height:76px}.dn-consult{font-size:12px;padding:0 12px}.dn-hero{padding:55px 0 85px}.dn-hero h1{font-size:43px}.dn-hero-media{height:350px}.dn-hero-media::after{height:160px}.dn-values,.dn-service-grid,.dn-style-cards,.dn-quotes,.dn-news-grid,.dn-contact-form form,.dn-list-grid{grid-template-columns:1fr}.dn-about-media img,.dn-glass-image{height:430px}.dn-service-grid{gap:60px}.dn-feature-table{grid-template-columns:1fr 1fr}.dn-feature:nth-child(n){border-right:1px solid #ddd;border-bottom:1px solid #ddd}.dn-feature:nth-child(2n){border-right:0}.dn-project-tabs{overflow:auto;justify-content:flex-start}.dn-project-tabs button{white-space:nowrap}.dn-project-grid{display:grid;grid-template-columns:1fr;grid-template-rows:repeat(4,260px)}.dn-styles-image img{height:430px}.dn-newsletter{padding:38px 24px}.dn-newsletter form{height:auto;display:grid}.dn-newsletter input{min-height:70px}.dn-newsletter button{min-height:70px}.dn-testimonial-layout{gap:45px}.dn-stats{grid-template-columns:1fr}.dn-stat{display:grid;text-align:left}.dn-news-head{display:block}.dn-news-head .dn-btn{margin-top:25px}.dn-news-card>a>img{height:280px}.dn-news-date{top:250px}.dn-contact-info{min-height:470px}.dn-contact-form{padding:32px 22px}.dn-contact-form textarea,.dn-contact-form .dn-btn{grid-column:auto}.dn-partner-track{grid-template-columns:1fr 1fr}.dn-inner-hero{padding:130px 0 70px}.dn-inner-hero h1{font-size:42px}.dn-content-card{padding:30px 22px}.dn-footer{padding-top:55px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}.dn-motion-ready [data-dn-reveal]{opacity:1;transform:none}}
</style>
