<?php

namespace App\Core\Themes\Demo;

use App\Models\CatalogCategory;use App\Models\CatalogProduct;use App\Models\CmsCategory;use App\Models\CmsMenu;use App\Models\CmsPost;use App\Models\LandingPage;use App\Models\LandingPageBlock;use App\Models\LandingPageBlockData;use App\Models\LandingPageData;use App\Models\SiteBanner;use App\Models\SiteProfile;use App\Models\ThemeDemoRecord;use App\Support\LandingPages\LandingPageBuilder;use App\Support\SiteContext;use Illuminate\Database\Eloquent\Model;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use InvalidArgumentException;

class E801DemoContentProvider implements ThemeDemoContentProvider
{
    private const THEME_KEY='E801';private const PRESET_KEY='e801-velo-ride';
    public function __construct(private readonly LandingPageBuilder $landingPageBuilder,private readonly SiteContext $siteContext){}
    public function themeKey():string{return self::THEME_KEY;}public function defaultPreset():string{return self::PRESET_KEY;}public function preset():array{return ['key'=>self::PRESET_KEY,'label'=>'E801 Velo Ride','description'=>'Cửa hàng xe đạp với dòng xe đường phố, trẻ em, banner xu hướng và cẩm nang chọn mua.'];}
    public function generate(string $presetKey):array
    {
        if($presetKey!==self::PRESET_KEY)throw new InvalidArgumentException('Preset demo không hợp lệ cho E801.');
        return DB::transaction(function():array{
            $purged=$this->delete();$websiteKey=$this->siteContext->websiteKey();$images=['https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1502744688674-c619d1586c9e?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1529422643029-d4585747aaf2?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=1000&q=85'];
            $street=CatalogCategory::query()->create(['name'=>'Xe đạp đường phố','slug'=>'e801-xe-dap-duong-pho','description'=>'Xe đạp city, touring và di chuyển hằng ngày.','image_url'=>$images[0],'sort_order'=>0,'is_active'=>true]);$this->record($street);$kids=CatalogCategory::query()->create(['name'=>'Xe đạp trẻ em','slug'=>'e801-xe-dap-tre-em','description'=>'Xe an toàn, dễ điều khiển dành cho trẻ em.','image_url'=>$images[1],'sort_order'=>1,'is_active'=>true]);$this->record($kids);
            $names=['Velo City GN 26','Velo Urban Pro 26','Velo Touring Flow','Velo City Basket 24','Velo Pacific Ravella','Velo Motion 29','Velo Kids Flying Fish 16','Velo Kids Batman 12','Velo Kids Basket Bird 16','Velo Kids Locke 12','Velo Royal Baby 16','Velo Happy Fish 18'];
            foreach($names as $i=>$name){$product=CatalogProduct::query()->create(['catalog_category_id'=>$i<6?$street->id:$kids->id,'name'=>$name,'slug'=>Str::slug('e801-'.$name),'sku'=>'E801-'.str_pad((string)($i+1),2,'0',STR_PAD_LEFT),'price'=>1390000+$i*170000,'original_price'=>2990000+$i*210000,'stock'=>30,'short_description'=>$i<6?'E801 URBAN':'E801 KIDS','detail_content'=>'<p>Khung bền nhẹ, truyền động ổn định và phụ kiện an toàn cho từng hành trình.</p>','image_url'=>$images[$i%6],'is_featured'=>$i<8,'is_highlight'=>$i<8,'sort_order'=>$i,'is_active'=>true]);$this->record($product);}
            $banner=SiteBanner::query()->create(['theme_key'=>self::THEME_KEY,'placement'=>'e801-hero-slider','title'=>'Đón hè năng động – Rộn ràng ưu đãi','subtitle'=>'Ưu đãi mùa hè dành cho mọi hành trình.','image_url'=>'/themes/E801/images/hero-summer.png','link_url'=>'#san-pham','badge'=>'E801 Velo','metadata'=>['summary'=>'Ưu đãi mùa hè dành cho mọi hành trình.','button_label'=>'Mua ngay'],'sort_order'=>0,'is_active'=>true]);$this->record($banner);
            $postCategory=CmsCategory::query()->create(['name'=>'Kinh nghiệm xe đạp','slug'=>'e801-kinh-nghiem-xe-dap','description'=>'Hướng dẫn chọn mua, sử dụng và bảo dưỡng xe đạp.']);$this->record($postCategory);foreach(['Hướng dẫn chọn mua và cách lắp chắn bùn xe đạp chi tiết','Cách đọc thông số lốp xe đạp đúng chuẩn','Đồng hồ đo tốc độ xe đạp là gì?','Khung xe đạp làm bằng gì?','Nguyên nhân khiến phanh xe đạp bị kêu'] as $i=>$title){$post=CmsPost::query()->create(['category_id'=>$postCategory->id,'title'=>$title,'slug'=>Str::slug('e801-'.$title),'status'=>'published','excerpt'=>'Kinh nghiệm thực tế giúp bạn lựa chọn và sử dụng xe đạp an toàn, hiệu quả.','body'=>'<p>Những lưu ý quan trọng được tổng hợp từ quá trình tư vấn và bảo dưỡng xe đạp thực tế.</p>','publish_at'=>now()->subDays($i+1),'is_highlight'=>true]);$this->record($post);}
            $home=route('site.home');$menu=CmsMenu::query()->create(['name'=>'E801 Main Menu','location'=>'primary-navigation','items'=>[['label'=>'Trang chủ','url'=>$home],['label'=>'Sản phẩm','url'=>$home.'#san-pham'],['label'=>'Giới thiệu','url'=>$home.'#kinh-nghiem'],['label'=>'Tin tức','url'=>route('site.blog.index')],['label'=>'Bảo hành','url'=>route('site.contact')],['label'=>'Liên hệ','url'=>route('site.contact')]]]);$this->record($menu);
            $profile=SiteProfile::query()->firstOrNew();$profile->forceFill(['site_name'=>'E801 Velo','website_type'=>'ecommerce','active_theme_key'=>self::THEME_KEY,'branding'=>array_merge((array)$profile->branding,['company_name'=>'E801 Velo','company_description'=>'Xe đạp chất lượng cho thể thao, gia đình và hành trình hằng ngày.','support_hotline'=>'1900 6750','support_email'=>'support@htvietnam.vn','support_location'=>'70 Lữ Gia, Quận 11, TP.HCM'])])->save();
            $existing=LandingPage::query()->where('website_key',$websiteKey)->where('theme_key',self::THEME_KEY)->where('is_home',true)->first();$page=$this->landingPageBuilder->resolveHome($websiteKey,self::THEME_KEY,true);if($page&&$existing===null)$this->record($page);
            return ['preset'=>$this->preset(),'counts'=>['categories'=>2,'products'=>12,'banners'=>1,'post_categories'=>1,'posts'=>5,'menus'=>1,'landing_pages'=>$existing===null&&$page?1:0],'purged'=>$purged];
        });
    }
    public function delete():array{$records=ThemeDemoRecord::query()->where('theme_key',self::THEME_KEY)->where('preset_key',self::PRESET_KEY)->get();$ids=fn(string $type):array=>$records->where('model_type',$type)->pluck('model_id')->all();$counts=['categories'=>0,'products'=>0,'banners'=>0,'post_categories'=>0,'posts'=>0,'menus'=>0,'landing_pages'=>0];if($pageIds=$ids(LandingPage::class)){$blockIds=LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->pluck('id');LandingPageBlockData::query()->whereIn('landing_page_block_id',$blockIds)->delete();LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->delete();LandingPageData::query()->whereIn('landing_page_id',$pageIds)->delete();$counts['landing_pages']=LandingPage::query()->whereKey($pageIds)->delete();}foreach([[CmsPost::class,'posts'],[CmsCategory::class,'post_categories'],[CatalogProduct::class,'products'],[CatalogCategory::class,'categories'],[CmsMenu::class,'menus'],[SiteBanner::class,'banners']] as [$model,$key])if($modelIds=$ids($model))$counts[$key]=$model::query()->whereKey($modelIds)->delete();ThemeDemoRecord::query()->whereKey($records->pluck('id'))->delete();return $counts;}
    private function record(Model $model):void{ThemeDemoRecord::query()->create(['theme_key'=>self::THEME_KEY,'preset_key'=>self::PRESET_KEY,'model_type'=>$model::class,'model_id'=>$model->getKey()]);}
}
