<?php

namespace App\Core\Themes\Demo;

use App\Models\CatalogCategory;use App\Models\CatalogProduct;use App\Models\CmsCategory;use App\Models\CmsMenu;use App\Models\CmsPost;use App\Models\LandingPage;use App\Models\LandingPageBlock;use App\Models\LandingPageBlockData;use App\Models\LandingPageData;use App\Models\SiteBanner;use App\Models\SiteProfile;use App\Models\ThemeDemoRecord;use App\Support\LandingPages\LandingPageBuilder;use App\Support\SiteContext;use Illuminate\Database\Eloquent\Model;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use InvalidArgumentException;

class E802DemoContentProvider implements ThemeDemoContentProvider
{
    private const THEME_KEY='E802';private const PRESET_KEY='e802-moto-red';
    public function __construct(private readonly LandingPageBuilder $landingPageBuilder,private readonly SiteContext $siteContext){}
    public function themeKey():string{return self::THEME_KEY;}public function defaultPreset():string{return self::PRESET_KEY;}public function preset():array{return ['key'=>self::PRESET_KEY,'label'=>'E802 Moto Red','description'=>'Showroom xe máy với sản phẩm, phụ tùng, ưu đãi, đánh giá và tin tức.'];}
    public function generate(string $presetKey):array
    {
        if($presetKey!==self::PRESET_KEY)throw new InvalidArgumentException('Preset demo không hợp lệ cho E802.');
        return DB::transaction(function():array{
            $purged=$this->delete();$websiteKey=$this->siteContext->websiteKey();$hero='/themes/E802/images/hero-moto.png';$sport='/themes/E802/images/sport-banner.png';
            $categories=[];foreach([['Xe đô thị','e802-xe-do-thi'],['Xe thể thao','e802-xe-the-thao'],['Xe đường dài','e802-xe-duong-dai']] as $i=>[$name,$slug]){$cat=CatalogCategory::query()->create(['name'=>$name,'slug'=>$slug,'description'=>'Dòng xe chất lượng dành cho hành trình hiện đại.','image_url'=>$i%2?$sport:$hero,'sort_order'=>$i,'is_active'=>true]);$this->record($cat);$categories[]=$cat;}
            $names=['Galaxy Urban 50','Angela Classic 50','Nova Galaxy 125','Jupiter City FI','MT Sport 15','Exciter VVA 155','Future City 125','Wave Alpha 110','Winner Street X','Vario Urban 160','Janus Elegance','Passing Mini 50'];foreach($names as $i=>$name){$p=CatalogProduct::query()->create(['catalog_category_id'=>$categories[$i%3]->id,'name'=>$name,'slug'=>Str::slug('e802-'.$name),'sku'=>'E802-'.str_pad((string)($i+1),2,'0',STR_PAD_LEFT),'price'=>18480000+$i*4250000,'original_price'=>$i%3===0?20480000+$i*4250000:null,'stock'=>20,'short_description'=>'E802 MOTO','detail_content'=>'<p>Thiết kế linh hoạt, vận hành ổn định và hỗ trợ hậu mãi xuyên suốt hành trình.</p>','image_url'=>$i%2?$hero:$sport,'is_featured'=>$i<8,'is_highlight'=>$i<8,'sort_order'=>$i,'is_active'=>true]);$this->record($p);}
            $banner=SiteBanner::query()->create(['theme_key'=>self::THEME_KEY,'placement'=>'e802-hero-slider','title'=>'Một lựa chọn chuẩn phong cách','subtitle'=>'Khám phá hành trình đô thị theo cách của bạn.','image_url'=>$hero,'link_url'=>'#san-pham','badge'=>'E802 Moto','metadata'=>['summary'=>'Khám phá hành trình đô thị theo cách của bạn.'],'sort_order'=>0,'is_active'=>true]);$this->record($banner);
            $postCategory=CmsCategory::query()->create(['name'=>'Tin xe và hành trình','slug'=>'e802-tin-xe','description'=>'Tin tức, kinh nghiệm và sự kiện dành cho người yêu xe.']);$this->record($postCategory);foreach(['Kinh nghiệm chọn xe đô thị phù hợp','Khám phá xe thể thao thế hệ mới','Bí quyết bảo dưỡng xe bền đẹp','Lịch lái thử cuối tuần','Phụ kiện an toàn cho mọi hành trình','Ưu đãi thành viên tháng này'] as $i=>$title){$post=CmsPost::query()->create(['category_id'=>$postCategory->id,'title'=>$title,'slug'=>Str::slug('e802-'.$title),'status'=>'published','excerpt'=>'Thông tin mới nhất dành cho người yêu xe và hành trình đô thị hiện đại.','body'=>'<p>Những thông tin hữu ích được tổng hợp từ kinh nghiệm tư vấn và chăm sóc xe thực tế.</p>','publish_at'=>now()->subDays($i+1),'is_highlight'=>true]);$this->record($post);}
            $home=route('site.home');$menu=CmsMenu::query()->create(['name'=>'E802 Main Menu','location'=>'primary-navigation','items'=>[['label'=>'Trang chủ','url'=>$home],['label'=>'Giới thiệu','url'=>$home.'#thuong-hieu'],['label'=>'Sản phẩm','url'=>$home.'#san-pham'],['label'=>'Tin tức','url'=>$home.'#tin-tuc'],['label'=>'Liên hệ','url'=>route('site.contact')],['label'=>'Hệ thống cửa hàng','url'=>$home.'#footer']]]);$this->record($menu);
            $profile=SiteProfile::query()->firstOrNew();$profile->forceFill(['site_name'=>'E802 Moto','website_type'=>'ecommerce','active_theme_key'=>self::THEME_KEY,'branding'=>array_merge((array)$profile->branding,['company_name'=>'E802 Moto','company_description'=>'Showroom xe máy và phụ tùng chất lượng, đồng hành cùng mọi hành trình.','support_hotline'=>'1900 6750','support_email'=>'support@htvietnam.vn','support_location'=>'70 Lữ Gia, Quận 11, TP.HCM'])])->save();
            $existing=LandingPage::query()->where('website_key',$websiteKey)->where('theme_key',self::THEME_KEY)->where('is_home',true)->first();$page=$this->landingPageBuilder->resolveHome($websiteKey,self::THEME_KEY,true);if($page&&$existing===null)$this->record($page);
            return ['preset'=>$this->preset(),'counts'=>['categories'=>3,'products'=>12,'banners'=>1,'post_categories'=>1,'posts'=>6,'menus'=>1,'landing_pages'=>$existing===null&&$page?1:0],'purged'=>$purged];
        });
    }
    public function delete():array{$records=ThemeDemoRecord::query()->where('theme_key',self::THEME_KEY)->where('preset_key',self::PRESET_KEY)->get();$ids=fn(string $type):array=>$records->where('model_type',$type)->pluck('model_id')->all();$counts=['categories'=>0,'products'=>0,'banners'=>0,'post_categories'=>0,'posts'=>0,'menus'=>0,'landing_pages'=>0];if($pageIds=$ids(LandingPage::class)){$blockIds=LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->pluck('id');LandingPageBlockData::query()->whereIn('landing_page_block_id',$blockIds)->delete();LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->delete();LandingPageData::query()->whereIn('landing_page_id',$pageIds)->delete();$counts['landing_pages']=LandingPage::query()->whereKey($pageIds)->delete();}foreach([[CmsPost::class,'posts'],[CmsCategory::class,'post_categories'],[CatalogProduct::class,'products'],[CatalogCategory::class,'categories'],[CmsMenu::class,'menus'],[SiteBanner::class,'banners']] as [$model,$key])if($modelIds=$ids($model))$counts[$key]=$model::query()->whereKey($modelIds)->delete();ThemeDemoRecord::query()->whereKey($records->pluck('id'))->delete();return $counts;}
    private function record(Model $model):void{ThemeDemoRecord::query()->create(['theme_key'=>self::THEME_KEY,'preset_key'=>self::PRESET_KEY,'model_type'=>$model::class,'model_id'=>$model->getKey()]);}
}
