<?php

namespace App\Core\Themes\Demo;

use App\Models\CatalogCategory;use App\Models\CatalogProduct;use App\Models\CmsCategory;use App\Models\CmsMenu;use App\Models\CmsPost;use App\Models\LandingPage;use App\Models\LandingPageBlock;use App\Models\LandingPageBlockData;use App\Models\LandingPageData;use App\Models\SiteBanner;use App\Models\SiteProfile;use App\Models\ThemeDemoRecord;use App\Support\LandingPages\LandingPageBuilder;use App\Support\SiteContext;use Illuminate\Database\Eloquent\Model;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use InvalidArgumentException;

class E803DemoContentProvider implements ThemeDemoContentProvider
{
    private const THEME_KEY='E803';private const PRESET_KEY='e803-wolf-pc';
    public function __construct(private readonly LandingPageBuilder $landingPageBuilder,private readonly SiteContext $siteContext){}
    public function themeKey():string{return self::THEME_KEY;}public function defaultPreset():string{return self::PRESET_KEY;}public function preset():array{return ['key'=>self::PRESET_KEY,'label'=>'E803 Wolf PC','description'=>'Cửa hàng PC, linh kiện và gaming gear với deal, chiến dịch và review công nghệ.'];}
    public function generate(string $presetKey):array
    {
        if($presetKey!==self::PRESET_KEY)throw new InvalidArgumentException('Preset demo không hợp lệ cho E803.');
        return DB::transaction(function():array{
            $purged=$this->delete();$websiteKey=$this->siteContext->websiteKey();$hero='/themes/E803/images/hero-gaming.png';$campaign='/themes/E803/images/campaign-tech.png';
            $categories=[];foreach([['PC và máy tính','e803-pc-may-tinh'],['Linh kiện','e803-linh-kien'],['Gaming Gear','e803-gaming-gear'],['Laptop và thiết bị','e803-laptop-thiet-bi']] as $i=>[$name,$slug]){$cat=CatalogCategory::query()->create(['name'=>$name,'slug'=>$slug,'description'=>'Thiết bị công nghệ tuyển chọn, nguồn gốc rõ ràng và bảo hành chính hãng.','image_url'=>$i%2?$campaign:$hero,'sort_order'=>$i,'is_active'=>true]);$this->record($cat);$categories[]=$cat;}
            $names=['Mainboard E803 B860M Gaming WiFi','Mainboard E803 Pro Z790 DDR5','CPU Nova Core 7 Creator','Chuột Gaming Pulse X1','Chuột Gaming Nova Air Pro','Bàn phím cơ Horizon 75','Màn hình Vision 27 QHD','Card đồ họa E803 RTX Studio','Card đồ họa E803 Creator 16G','RAM Aurora DDR5 32GB','SSD Swift NVMe 2TB','Tai nghe Sonic Pro 7.1','Webcam Stream 4K','Case E803 Panorama RGB','Tản nhiệt Frost Core 360'];foreach($names as $i=>$name){$p=CatalogProduct::query()->create(['catalog_category_id'=>$categories[$i%4]->id,'name'=>$name,'slug'=>Str::slug('e803-'.$name),'sku'=>'E803-'.str_pad((string)($i+1),2,'0',STR_PAD_LEFT),'price'=>790000+$i*730000,'original_price'=>$i%3!==2?1190000+$i*790000:null,'stock'=>20,'short_description'=>'E803 PERFORMANCE','detail_content'=>'<p>Thiết bị hiệu năng cao, tương thích linh hoạt và được hỗ trợ kỹ thuật xuyên suốt.</p>','image_url'=>$i%2?$hero:$campaign,'is_featured'=>$i<10,'is_highlight'=>$i<10,'sort_order'=>$i,'is_active'=>true]);$this->record($p);}
            $banner=SiteBanner::query()->create(['theme_key'=>self::THEME_KEY,'placement'=>'e803-hero-slider','title'=>'Cỗ máy cho mọi cuộc chơi','subtitle'=>'Khám phá hệ sinh thái PC và gaming gear được tuyển chọn.','image_url'=>$hero,'link_url'=>'#deals','badge'=>'E803 PC','metadata'=>['summary'=>'Hiệu năng mạnh mẽ cho công việc, sáng tạo và giải trí.'],'sort_order'=>0,'is_active'=>true]);$this->record($banner);
            $postCategory=CmsCategory::query()->create(['name'=>'Công nghệ và Review','slug'=>'e803-cong-nghe-review','description'=>'Kiến thức, hướng dẫn và đánh giá PC, laptop, gaming gear.']);$this->record($postCategory);foreach(['Khắc phục sự cố Wi-Fi trên Windows hiệu quả','Chọn laptop OLED cho công việc sáng tạo','Tối ưu nhiệt độ khi chơi game dài giờ','Cách chọn màn hình QHD đúng nhu cầu','Nâng cấp SSD: điều cần biết trước khi mua','Bàn phím cơ nào phù hợp cho văn phòng?','Xây dựng PC làm đồ họa theo ngân sách','Bảo dưỡng máy tính để bàn đúng cách'] as $i=>$title){$post=CmsPost::query()->create(['category_id'=>$postCategory->id,'title'=>$title,'slug'=>Str::slug('e803-'.$title),'status'=>'published','excerpt'=>'Kiến thức công nghệ thực tế, dễ áp dụng cho công việc, học tập và giải trí.','body'=>'<p>Nội dung được tổng hợp từ kinh nghiệm tư vấn, lắp ráp và tối ưu thiết bị thực tế.</p>','publish_at'=>now()->subDays($i+1),'is_highlight'=>true]);$this->record($post);}
            $home=route('site.home');$menu=CmsMenu::query()->create(['name'=>'E803 Main Menu','location'=>'primary-navigation','items'=>[['label'=>'Trang chủ','url'=>$home],['label'=>'Giới thiệu','url'=>$home.'#gioi-thieu'],['label'=>'Xây dựng cấu hình','url'=>$home.'#build-pc'],['label'=>'Gaming Deal','url'=>$home.'#deals'],['label'=>'Sản phẩm','url'=>$home.'#san-pham'],['label'=>'Hệ thống cửa hàng','url'=>$home.'#footer'],['label'=>'Tin tức','url'=>$home.'#tin-tuc'],['label'=>'Liên hệ','url'=>route('site.contact')]]]);$this->record($menu);
            $profile=SiteProfile::query()->firstOrNew();$profile->forceFill(['site_name'=>'E803 Wolf PC','website_type'=>'ecommerce','active_theme_key'=>self::THEME_KEY,'branding'=>array_merge((array)$profile->branding,['company_name'=>'E803 Wolf PC','company_description'=>'Hệ sinh thái PC, linh kiện và gaming gear chính hãng với tư vấn cấu hình tận tâm.','support_hotline'=>'1900 6750','support_email'=>'support@htvietnam.vn','support_location'=>'70 Lữ Gia, Quận 11, TP.HCM'])])->save();
            $existing=LandingPage::query()->where('website_key',$websiteKey)->where('theme_key',self::THEME_KEY)->where('is_home',true)->first();$page=$this->landingPageBuilder->resolveHome($websiteKey,self::THEME_KEY,true);if($page&&$existing===null)$this->record($page);
            return ['preset'=>$this->preset(),'counts'=>['categories'=>4,'products'=>15,'banners'=>1,'post_categories'=>1,'posts'=>8,'menus'=>1,'landing_pages'=>$existing===null&&$page?1:0],'purged'=>$purged];
        });
    }
    public function delete():array{$records=ThemeDemoRecord::query()->where('theme_key',self::THEME_KEY)->where('preset_key',self::PRESET_KEY)->get();$ids=fn(string $type):array=>$records->where('model_type',$type)->pluck('model_id')->all();$counts=['categories'=>0,'products'=>0,'banners'=>0,'post_categories'=>0,'posts'=>0,'menus'=>0,'landing_pages'=>0];if($pageIds=$ids(LandingPage::class)){$blockIds=LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->pluck('id');LandingPageBlockData::query()->whereIn('landing_page_block_id',$blockIds)->delete();LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->delete();LandingPageData::query()->whereIn('landing_page_id',$pageIds)->delete();$counts['landing_pages']=LandingPage::query()->whereKey($pageIds)->delete();}foreach([[CmsPost::class,'posts'],[CmsCategory::class,'post_categories'],[CatalogProduct::class,'products'],[CatalogCategory::class,'categories'],[CmsMenu::class,'menus'],[SiteBanner::class,'banners']] as [$model,$key])if($modelIds=$ids($model))$counts[$key]=$model::query()->whereKey($modelIds)->delete();ThemeDemoRecord::query()->whereKey($records->pluck('id'))->delete();return $counts;}
    private function record(Model $model):void{ThemeDemoRecord::query()->create(['theme_key'=>self::THEME_KEY,'preset_key'=>self::PRESET_KEY,'model_type'=>$model::class,'model_id'=>$model->getKey()]);}
}
