<?php
namespace App\Core\Themes\Demo;
use App\Models\CatalogCategory;use App\Models\CatalogProduct;use App\Models\CmsCategory;use App\Models\CmsMenu;use App\Models\CmsPost;use App\Models\LandingPage;use App\Models\LandingPageBlock;use App\Models\LandingPageBlockData;use App\Models\LandingPageData;use App\Models\SiteBanner;use App\Models\SiteProfile;use App\Models\ThemeDemoRecord;use App\Support\LandingPages\LandingPageBuilder;use App\Support\SiteContext;use Illuminate\Database\Eloquent\Model;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use InvalidArgumentException;
class E806DemoContentProvider implements ThemeDemoContentProvider
{
    private const THEME_KEY='E806';private const PRESET_KEY='e806-electronics';
    public function __construct(private readonly LandingPageBuilder $landingPageBuilder,private readonly SiteContext $siteContext){}public function themeKey():string{return self::THEME_KEY;}public function defaultPreset():string{return self::PRESET_KEY;}public function preset():array{return ['key'=>self::PRESET_KEY,'label'=>'E806 Golden Electronics','description'=>'Cửa hàng điện máy với mega menu, sản phẩm công nghệ và mạng lưới điểm bán.'];}
    public function generate(string $presetKey):array
    {
        $presetKey??=self::PRESET_KEY;if($presetKey!==self::PRESET_KEY)throw new InvalidArgumentException('Preset demo không hợp lệ cho E806.');
        return DB::transaction(function()use($presetKey){$purged=$this->delete();$websiteKey=$this->siteContext->websiteKey();$hero='/themes/E806/images/hero-appliances.png';$campaign='/themes/E806/images/tech-campaign.png';
            $categories=[];foreach([['Điện tử và thiết bị số','e806-dien-tu'],['Nhà cửa và đời sống','e806-nha-cua'],['Làm đẹp và sức khỏe','e806-lam-dep'],['Mẹ và bé','e806-me-va-be'],['Thời trang và phụ kiện','e806-thoi-trang'],['Bách hóa online','e806-bach-hoa']] as $i=>[$name,$slug]){$cat=CatalogCategory::query()->create(['name'=>$name,'slug'=>$slug,'description'=>'Sản phẩm tuyển chọn, nguồn gốc rõ ràng và giao hàng nhanh.','image_url'=>$i%2?$campaign:$hero,'sort_order'=>$i,'is_active'=>true]);$this->record($cat);$categories[]=$cat;}
            $names=['Tai nghe AirComfort W820','Điện thoại Nova Max 256GB','Dầu gội thảo mộc PureMen','Chuột không dây Silent B170','Nồi chiên AirChef 6L','Serum cấp ẩm Aqua B5','Tã quần BabySoft Premium','Sữa dinh dưỡng NutriCare','Balo Urban Daily','Giày thể thao Cloud Walk','Máy xay MiniMix Pro','Đèn bàn Lumi Flex','Bánh hạt dinh dưỡng Granola','Robot hút bụi HomeBot','Đồng hồ Active Fit','Kem chống nắng Daily Shield','Bộ nồi Inox HomeCook','Gấu bông Teddy Joy'];foreach($names as $i=>$name){$p=CatalogProduct::query()->create(['catalog_category_id'=>$categories[$i%6]->id,'name'=>$name,'slug'=>Str::slug('e806-'.$name),'sku'=>'E806-'.str_pad((string)($i+1),2,'0',STR_PAD_LEFT),'price'=>150000+$i*175000,'original_price'=>$i%3!==2?250000+$i*230000:null,'stock'=>30+$i,'short_description'=>'E806 SELECTED','detail_content'=>'<p>Sản phẩm được tuyển chọn cho nhu cầu mua sắm đa ngành, giao nhanh và hỗ trợ tận tâm.</p>','image_url'=>$i%2?$hero:$campaign,'is_featured'=>$i<12,'is_highlight'=>$i<12,'sort_order'=>$i,'is_active'=>true]);$this->record($p);}
            $banner=SiteBanner::query()->create(['theme_key'=>self::THEME_KEY,'placement'=>'e806-hero-market','title'=>'Hàng hay giá tốt mỗi ngày','subtitle'=>'Khám phá hàng ngàn sản phẩm tuyển chọn cho mọi nhu cầu.','image_url'=>$hero,'link_url'=>'#deals','badge'=>'E806 MALL','metadata'=>['summary'=>'Marketplace đa ngành, ưu đãi mới mỗi ngày.'],'sort_order'=>0,'is_active'=>true]);$this->record($banner);
            $postCategory=CmsCategory::query()->create(['name'=>'Cẩm nang mua sắm','slug'=>'e806-cam-nang-mua-sam','description'=>'Xu hướng, kinh nghiệm và mẹo mua sắm thông minh.']);$this->record($postCategory);foreach(['Bí quyết săn ưu đãi đúng lúc và tiết kiệm','Cách chọn thiết bị gia dụng phù hợp căn bếp','Gợi ý quà tặng thiết thực cho gia đình','Chăm sóc da tối giản cho người bận rộn','Mẹo sắp xếp góc làm việc gọn gàng','Xu hướng tiêu dùng thông minh năm nay'] as $i=>$title){$post=CmsPost::query()->create(['category_id'=>$postCategory->id,'title'=>$title,'slug'=>Str::slug('e806-'.$title),'status'=>'published','excerpt'=>'Những gợi ý hữu ích giúp bạn lựa chọn sản phẩm phù hợp và mua sắm hiệu quả.','body'=>'<p>Nội dung được tổng hợp từ kinh nghiệm tư vấn và lựa chọn sản phẩm thực tế.</p>','publish_at'=>now()->subDays($i+1),'is_highlight'=>true]);$this->record($post);}
            $home=route('site.home');$menu=CmsMenu::query()->create(['name'=>'E806 Main Menu','location'=>'primary-navigation','items'=>[['label'=>'Trang chủ','url'=>$home],['label'=>'Giới thiệu','url'=>$home.'#gioi-thieu'],['label'=>'Sản phẩm','url'=>$home.'#san-pham'],['label'=>'Yêu thích','url'=>$home.'#goi-y'],['label'=>'Liên hệ','url'=>route('site.contact')],['label'=>'Tin tức','url'=>$home.'#tin-tuc'],['label'=>'Hệ thống cửa hàng','url'=>$home.'#footer'],['label'=>'Đăng ký Affiliate','url'=>$home.'#footer']]]);$this->record($menu);
            $profile=SiteProfile::query()->firstOrNew();$profile->forceFill(['site_name'=>'E806 Market','website_type'=>'ecommerce','active_theme_key'=>self::THEME_KEY,'branding'=>array_merge((array)$profile->branding,['company_name'=>'E806 Market','company_description'=>'Hệ thống điện máy hiện đại với sản phẩm chính hãng, giá tốt và hỗ trợ tận tâm.','support_hotline'=>'1900 6750','support_email'=>'support@htvietnam.vn','support_location'=>'266 Đội Cấn, Ba Đình, Hà Nội'])])->save();
            $existing=LandingPage::query()->where('website_key',$websiteKey)->where('theme_key',self::THEME_KEY)->where('is_home',true)->first();$page=$this->landingPageBuilder->resolveHome($websiteKey,self::THEME_KEY,true);if($page&&$existing===null)$this->record($page);
            return ['preset'=>$this->preset(),'counts'=>['categories'=>6,'products'=>18,'banners'=>1,'post_categories'=>1,'posts'=>6,'menus'=>1,'landing_pages'=>$existing===null&&$page?1:0],'purged'=>$purged];});
    }
    public function delete():array{$records=ThemeDemoRecord::query()->where('theme_key',self::THEME_KEY)->where('preset_key',self::PRESET_KEY)->get();$ids=fn(string $type):array=>$records->where('model_type',$type)->pluck('model_id')->all();$counts=['categories'=>0,'products'=>0,'banners'=>0,'post_categories'=>0,'posts'=>0,'menus'=>0,'landing_pages'=>0];if($pageIds=$ids(LandingPage::class)){$blockIds=LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->pluck('id');LandingPageBlockData::query()->whereIn('landing_page_block_id',$blockIds)->delete();LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->delete();LandingPageData::query()->whereIn('landing_page_id',$pageIds)->delete();$counts['landing_pages']=LandingPage::query()->whereKey($pageIds)->delete();}foreach([[CmsPost::class,'posts'],[CmsCategory::class,'post_categories'],[CatalogProduct::class,'products'],[CatalogCategory::class,'categories'],[CmsMenu::class,'menus'],[SiteBanner::class,'banners']] as [$model,$key])if($modelIds=$ids($model))$counts[$key]=$model::query()->whereKey($modelIds)->delete();ThemeDemoRecord::query()->whereKey($records->pluck('id'))->delete();return $counts;}
    private function record(Model $model):void{ThemeDemoRecord::query()->create(['theme_key'=>self::THEME_KEY,'preset_key'=>self::PRESET_KEY,'model_type'=>$model::class,'model_id'=>$model->getKey()]);}
}


