<?php
namespace App\Core\Themes\Demo;
use App\Models\CatalogCategory;use App\Models\CatalogProduct;use App\Models\CmsCategory;use App\Models\CmsMenu;use App\Models\CmsPost;use App\Models\LandingPage;use App\Models\LandingPageBlock;use App\Models\LandingPageBlockData;use App\Models\LandingPageData;use App\Models\SiteBanner;use App\Models\SiteProfile;use App\Models\ThemeDemoRecord;use App\Support\LandingPages\LandingPageBuilder;use App\Support\SiteContext;use Illuminate\Database\Eloquent\Model;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use InvalidArgumentException;
class E807DemoContentProvider implements ThemeDemoContentProvider
{
    private const THEME_KEY='E807';private const PRESET_KEY='e807-pro-tools';
    public function __construct(private readonly LandingPageBuilder $landingPageBuilder,private readonly SiteContext $siteContext){}public function themeKey():string{return self::THEME_KEY;}public function defaultPreset():string{return self::PRESET_KEY;}public function preset():array{return ['key'=>self::PRESET_KEY,'label'=>'E807 Pro Tools','description'=>'Cửa hàng dụng cụ cơ khí với danh mục chuyên nghiệp, deal nổi bật và cẩm nang kỹ thuật.'];}
    public function generate(string $presetKey):array
    {
        $presetKey??=self::PRESET_KEY;if($presetKey!==self::PRESET_KEY)throw new InvalidArgumentException('Preset demo không hợp lệ cho E807.');
        return DB::transaction(function()use($presetKey){$purged=$this->delete();$websiteKey=$this->siteContext->websiteKey();$hero='/themes/E807/images/hero-tools.png';$campaign='/themes/E807/images/tool-collection.png';
            $categories=[];foreach([['Dụng cụ điện','e807-dung-cu-dien'],['Máy khoan và bắt vít','e807-may-khoan'],['Máy cưa và máy cắt','e807-may-cua'],['Máy hàn và thiết bị xưởng','e807-may-han'],['Thiết bị vệ sinh công nghiệp','e807-ve-sinh'],['Bảo hộ và phụ kiện','e807-bao-ho']] as $i=>[$name,$slug]){$cat=CatalogCategory::query()->create(['name'=>$name,'slug'=>$slug,'description'=>'Sản phẩm tuyển chọn, nguồn gốc rõ ràng và giao hàng nhanh.','image_url'=>$i%2?$campaign:$hero,'sort_order'=>$i,'is_active'=>true]);$this->record($cat);$categories[]=$cat;}
            $names=['Máy khoan pin Impact Pro','Máy cưa đĩa Circular 185','Máy mài góc GrindMax','Máy xịt rửa Pressure 150','Máy hàn điện tử Arc Mini','Bộ dụng cụ sửa chữa 108 chi tiết','Máy bơm tăng áp FlowMax','Máy cưa xích Chain Pro','Tời điện tải trọng 500kg','Máy nén khí Compact 24L','Bộ mũi khoan đa năng','Balo đồ nghề Technician','Máy phun sơn Air Paint','Máy thổi bụi Workshop','Máy cắt gạch StoneCut','Thang nhôm đa năng','Mũ bảo hộ công trình','Găng tay chống cắt'];foreach($names as $i=>$name){$p=CatalogProduct::query()->create(['catalog_category_id'=>$categories[$i%6]->id,'name'=>$name,'slug'=>Str::slug('e807-'.$name),'sku'=>'E807-'.str_pad((string)($i+1),2,'0',STR_PAD_LEFT),'price'=>150000+$i*175000,'original_price'=>$i%3!==2?250000+$i*230000:null,'stock'=>30+$i,'short_description'=>'E807 PROFESSIONAL','detail_content'=>'<p>Sản phẩm được tuyển chọn cho nhu cầu mua sắm đa ngành, giao nhanh và hỗ trợ tận tâm.</p>','image_url'=>$i%2?$hero:$campaign,'is_featured'=>$i<12,'is_highlight'=>$i<12,'sort_order'=>$i,'is_active'=>true]);$this->record($p);}
            $banner=SiteBanner::query()->create(['theme_key'=>self::THEME_KEY,'placement'=>'e807-hero-tools','title'=>'Sức mạnh cho mọi công trình','subtitle'=>'Dụng cụ chuyên nghiệp, hiệu suất bền bỉ cho mọi dự án.','image_url'=>$hero,'link_url'=>'#deal','badge'=>'E807 PRO','metadata'=>['summary'=>'Giải pháp dụng cụ chuyên nghiệp cho nhà thầu và xưởng sản xuất.'],'sort_order'=>0,'is_active'=>true]);$this->record($banner);
            $postCategory=CmsCategory::query()->create(['name'=>'Cẩm nang dụng cụ','slug'=>'e807-cam-nang-dung-cu','description'=>'Kinh nghiệm lựa chọn, sử dụng và bảo dưỡng dụng cụ an toàn.']);$this->record($postCategory);foreach(['Bí quyết săn ưu đãi đúng lúc và tiết kiệm','Cách chọn thiết bị gia dụng phù hợp căn bếp','Gợi ý quà tặng thiết thực cho gia đình','Chăm sóc da tối giản cho người bận rộn','Mẹo sắp xếp góc làm việc gọn gàng','Xu hướng tiêu dùng thông minh năm nay'] as $i=>$title){$post=CmsPost::query()->create(['category_id'=>$postCategory->id,'title'=>$title,'slug'=>Str::slug('e807-'.$title),'status'=>'published','excerpt'=>'Những gợi ý hữu ích giúp bạn lựa chọn sản phẩm phù hợp và mua sắm hiệu quả.','body'=>'<p>Nội dung được tổng hợp từ kinh nghiệm tư vấn và lựa chọn sản phẩm thực tế.</p>','publish_at'=>now()->subDays($i+1),'is_highlight'=>true]);$this->record($post);}
            $home=route('site.home');$menu=CmsMenu::query()->create(['name'=>'E807 Main Menu','location'=>'primary-navigation','items'=>[['label'=>'Trang chủ','url'=>$home],['label'=>'Giới thiệu','url'=>$home.'#gioi-thieu'],['label'=>'Sản phẩm','url'=>$home.'#san-pham'],['label'=>'Sản phẩm khuyến mãi','url'=>$home.'#deal'],['label'=>'Tin tức','url'=>$home.'#tin-tuc'],['label'=>'Liên hệ','url'=>route('site.contact')],['label'=>'Hệ thống cửa hàng','url'=>$home.'#footer'],['label'=>'Câu hỏi thường gặp','url'=>$home.'#footer']]]);$this->record($menu);
            $profile=SiteProfile::query()->firstOrNew();$profile->forceFill(['site_name'=>'E807 Pro Tools','website_type'=>'ecommerce','active_theme_key'=>self::THEME_KEY,'branding'=>array_merge((array)$profile->branding,['company_name'=>'E807 Pro Tools','company_description'=>'Hệ thống dụng cụ cơ khí chuyên nghiệp với sản phẩm bền bỉ, thông số rõ ràng và hỗ trợ tận tâm.','support_hotline'=>'1900 6750','support_email'=>'support@htvietnam.vn','support_location'=>'70 Lữ Gia, Phường 15, Quận 11, TP.HCM'])])->save();
            $existing=LandingPage::query()->where('website_key',$websiteKey)->where('theme_key',self::THEME_KEY)->where('is_home',true)->first();$page=$this->landingPageBuilder->resolveHome($websiteKey,self::THEME_KEY,true);if($page&&$existing===null)$this->record($page);
            return ['preset'=>$this->preset(),'counts'=>['categories'=>6,'products'=>18,'banners'=>1,'post_categories'=>1,'posts'=>6,'menus'=>1,'landing_pages'=>$existing===null&&$page?1:0],'purged'=>$purged];});
    }
    public function delete():array{$records=ThemeDemoRecord::query()->where('theme_key',self::THEME_KEY)->where('preset_key',self::PRESET_KEY)->get();$ids=fn(string $type):array=>$records->where('model_type',$type)->pluck('model_id')->all();$counts=['categories'=>0,'products'=>0,'banners'=>0,'post_categories'=>0,'posts'=>0,'menus'=>0,'landing_pages'=>0];if($pageIds=$ids(LandingPage::class)){$blockIds=LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->pluck('id');LandingPageBlockData::query()->whereIn('landing_page_block_id',$blockIds)->delete();LandingPageBlock::query()->whereIn('landing_page_id',$pageIds)->delete();LandingPageData::query()->whereIn('landing_page_id',$pageIds)->delete();$counts['landing_pages']=LandingPage::query()->whereKey($pageIds)->delete();}foreach([[CmsPost::class,'posts'],[CmsCategory::class,'post_categories'],[CatalogProduct::class,'products'],[CatalogCategory::class,'categories'],[CmsMenu::class,'menus'],[SiteBanner::class,'banners']] as [$model,$key])if($modelIds=$ids($model))$counts[$key]=$model::query()->whereKey($modelIds)->delete();ThemeDemoRecord::query()->whereKey($records->pluck('id'))->delete();return $counts;}
    private function record(Model $model):void{ThemeDemoRecord::query()->create(['theme_key'=>self::THEME_KEY,'preset_key'=>self::PRESET_KEY,'model_type'=>$model::class,'model_id'=>$model->getKey()]);}
}




