@php
  $blocks = collect($landingBlocks ?? [])->values();
  $canEditLanding = auth('admin')->check() && request('mod') === 'admin' && is_array($landingPage ?? null);
  $blockUpdateUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.update', ['block' => '__BLOCK_ID__']) : '';
  $blockSourcePreviewUrlTemplate = $canEditLanding ? route('admin.api.landing.blocks.source-preview', ['block' => '__BLOCK_ID__']) : '';
  $blockPayload = $canEditLanding ? $blocks->keyBy('id')->toArray() : [];
  $editorLocales = collect(\App\Support\FrontendLocalization::supportedLocales())->map(fn ($locale) => ['code' => $locale, 'label' => strtoupper($locale)])->all();
  $get = fn(string $type): array => (array)($blocks->firstWhere('block_type', $type) ?? []);
  $items = fn(array $block) => collect($block['dynamic_items'] ?? [])->filter()->values()->whenEmpty(fn($list) => $list->push(...collect(data_get($block,'data.content.items',[]))->filter()->values()->all()));
  $image = fn($item,string $fallback) => data_get($item,'image',data_get($item,'image_url',$fallback));
  $money = fn($value) => (float)$value > 0 ? number_format((float)$value,0,',','.').'đ' : app(\App\Core\Themes\ThemeTranslationService::class)->bladeText('E800',app()->getLocale(),'E800.common.contact_price');
  $discount = fn($item) => ((float)data_get($item,'original_price') > (float)data_get($item,'price') && (float)data_get($item,'original_price') > 0) ? round((1-(float)data_get($item,'price')/(float)data_get($item,'original_price'))*100) : 0;
  $hero=$get('hero_slider'); $collections=$get('e800_collections'); $deals=$get('e800_deals'); $look=$get('e800_shop_look'); $needs=$get('e800_needs'); $categories=$get('e800_categories'); $brands=$get('e800_brands'); $promos=$get('e800_promotions'); $benefits=$get('e800_benefits');
  $slides=collect($hero['dynamic_items']??[])->filter()->values(); if($slides->isEmpty())$slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values();
  $productCard=function($item,bool $withSelect=false)use($image,$money,$discount){$off=$discount($item);@endphp
    <article class="e800-product"><a class="e800-product__image" href="{{ data_get($item,'url','#') }}">@if($off)<span class="e800-badge">-{{ $off }}%</span>@endif<img src="{{ $image($item,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=85') }}" alt="{{ data_get($item,'title',data_get($item,'name')) }}"></a><div class="e800-product__body"><small>{{ data_get($item,'summary','E800 PERFORMANCE') }}</small><h3><a href="{{ data_get($item,'url','#') }}">{{ data_get($item,'title',data_get($item,'name')) }}</a></h3><strong>{{ $money(data_get($item,'price')) }}</strong>@if(data_get($item,'original_price'))<del>{{ $money(data_get($item,'original_price')) }}</del>@endif @if($withSelect)<select class="e800-select" aria-label="Biến thể"><option>{{ data_get($item,'variant','Mặc định / Size 40') }}</option></select>@endif</div></article>
  @php };
@endphp
@extends('theme-e800::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','E800')))
@section('content')
<main class="e800-main">
  <section class="e800-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider" data-e800-slider data-autoplay="{{ data_get($hero,'settings.autoplay_ms',6500) }}">@foreach($slides as $i=>$slide)<article class="e800-hero__slide {{ $i===0?'is-active':'' }}" data-e800-slide><img src="{{ $image($slide,asset('themes/E800/images/hero-e800.png')) }}" alt="{{ data_get($slide,'title') }}"><div class="e800-hero__shade"></div><div class="e800-container e800-hero__copy"><p>{{ data_get($slide,'kicker',data_get($hero,'data.subtitle')) }}</p><h1>{{ data_get($slide,'title',data_get($hero,'data.title')) }}</h1><span>{{ data_get($slide,'summary',data_get($hero,'data.description')) }}</span><a class="e800-cta" href="{{ data_get($slide,'link_url','#san-pham') }}">{{ data_get($slide,'button_label',data_get($hero,'data.button_label','Khám phá ngay')) }} →</a></div></article>@endforeach<button data-e800-prev aria-label="Trước"><i class="fa-solid fa-chevron-left"></i></button><button data-e800-next aria-label="Sau"><i class="fa-solid fa-chevron-right"></i></button></section>

  <section id="{{ data_get($collections,'anchor_id','bo-suu-tap') }}" class="e800-section xd-landing-block" data-landing-block-id="{{ data_get($collections,'id') }}" data-block-type="e800_collections"><div class="e800-container"><header class="e800-heading"><h2>{{ data_get($collections,'data.title','Khám phá các') }} <em>{{ data_get($collections,'data.subtitle','bộ sưu tập') }}</em></h2></header><div class="e800-collections">@foreach($items($collections) as $item)<a class="e800-collection-card" href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85') }}" alt="{{ data_get($item,'title') }}"><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></div></section>

  <section id="{{ data_get($deals,'anchor_id','deal-noi-bat') }}" class="e800-section xd-landing-block" data-landing-block-id="{{ data_get($deals,'id') }}" data-block-type="e800_deals"><div class="e800-container e800-deals">@foreach($items($deals) as $item)<article class="e800-deal"><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p><strong>{{ $money(data_get($item,'price')) }}</strong>@if(data_get($item,'original_price'))<del>{{ $money(data_get($item,'original_price')) }}</del>@endif<a href="{{ data_get($item,'url','#') }}">Xem chi tiết &gt;</a><img src="{{ $image($item,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item,'title') }}"></article>@endforeach</div></section>

  @php $lookItems=$items($look); @endphp
  <section id="{{ data_get($look,'anchor_id','mua-tron-bo') }}" class="e800-section xd-landing-block" data-landing-block-id="{{ data_get($look,'id') }}" data-block-type="e800_shop_look"><div class="e800-container e800-look"><div class="e800-look__visual"><img src="{{ data_get($look,'media.image',asset('themes/E800/images/shop-the-look.png')) }}" alt="{{ data_get($look,'data.title') }}"><div><h3>{{ data_get($look,'data.subtitle','YEAR END SALE') }}</h3><p>{{ data_get($look,'data.description') }}</p></div></div><div class="e800-look__body"><h2>{{ data_get($look,'data.title','Mua trọn bộ trang phục') }}</h2><div class="e800-products">@foreach($lookItems->take(3) as $item){{ $productCard($item,true) }}@endforeach</div><a class="e800-cta e800-add-all" href="{{ route('site.cart.index') }}"><i class="fa-solid fa-cart-shopping"></i>&nbsp; {{ data_get($look,'data.button_label','Thêm tất cả vào giỏ hàng') }}</a></div></div></section>

  <section id="{{ data_get($needs,'anchor_id','san-pham') }}" class="e800-section e800-needs xd-landing-block" data-landing-block-id="{{ data_get($needs,'id') }}" data-block-type="e800_needs"><div class="e800-container"><header class="e800-heading"><h2>{{ data_get($needs,'data.title','Mua sắm') }} <em>{{ data_get($needs,'data.subtitle','theo nhu cầu') }}</em></h2></header><div class="e800-tabs" data-e800-tabs>@foreach(data_get($needs,'data.content.tabs',['Thời trang','Luyện tập','Chạy bộ']) as $i=>$tab)<button class="{{ $i===0?'is-active':'' }}">{{ $tab }}</button>@endforeach</div><div class="e800-products">@foreach($items($needs) as $item){{ $productCard($item) }}@endforeach</div></div></section>

  <section id="{{ data_get($categories,'anchor_id','danh-muc') }}" class="e800-section xd-landing-block" data-landing-block-id="{{ data_get($categories,'id') }}" data-block-type="e800_categories"><div class="e800-container"><header class="e800-heading"><h2>{{ data_get($categories,'data.title','Danh mục') }} <em>{{ data_get($categories,'data.subtitle','Nổi bật') }}</em></h2></header><div class="e800-categories">@foreach($items($categories) as $item)<a class="e800-category" href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=700&q=85') }}" alt="{{ data_get($item,'title') }}"><span>{{ data_get($item,'title') }} ›</span></a>@endforeach</div></div></section>

  <section class="e800-brand-strip xd-landing-block" data-landing-block-id="{{ data_get($brands,'id') }}" data-block-type="e800_brands"><div class="e800-container e800-brands">@foreach($items($brands) as $item)<span>{{ data_get($item,'title') }}</span>@endforeach</div></section>

  <section id="{{ data_get($promos,'anchor_id','khuyen-mai') }}" class="e800-section xd-landing-block" data-landing-block-id="{{ data_get($promos,'id') }}" data-block-type="e800_promotions"><div class="e800-container"><header class="e800-heading"><h2>{{ data_get($promos,'data.title','Bản tin') }} <em>{{ data_get($promos,'data.subtitle','khuyến mãi') }}</em></h2></header><div class="e800-news">@foreach($items($promos) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=85') }}" alt="{{ data_get($item,'title') }}"></a><small>{{ data_get($item,'published_at') }}</small><h3><a href="{{ data_get($item,'url','#') }}">{{ data_get($item,'title') }}</a></h3><p>{{ \Illuminate\Support\Str::limit(strip_tags((string)data_get($item,'summary')),125) }}</p></article>@endforeach</div></div></section>
</main>
@endsection
