@php $blocks=collect($landingBlocks??[])->values();$get=fn($t)=>(array)($blocks->firstWhere('block_type',$t)??[]);$items=fn($b)=>collect($b['dynamic_items']??[])->filter()->values()->whenEmpty(fn($x)=>$x->push(...collect(data_get($b,'data.content.items',[]))->filter()->values()->all()));$img=fn($x,$f)=>data_get($x,'image',data_get($x,'image_url',$f));$hero=$get('hero_slider');$cats=$get('e805_categories');$sale=$get('e805_sale_tabs');$tech=$get('e805_technology');$picks=$get('e805_picks');$news=$get('e805_news');$slides=collect($hero['dynamic_items']??data_get($hero,'data.content.slides',[]));@endphp
@extends('theme-e805::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','E805 Mart')))
@section('content')
<main class="e805-main">
<section id="gioi-thieu" class="e805-hero-section xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider"><div class="e805-container"><article class="e805-hero"><img src="{{ $img($slides->first(),asset('themes/E805/images/hero-retail.png')) }}" alt="Siêu sale E805"><div><small>ĐỒ GIA DỤNG · NHÀ CỬA · ĐỜI SỐNG</small><h1>“Siêu” <b>sale</b><br>làm bạn xiêu lòng</h1><a href="#san-pham">Mua ngay</a></div></article></div></section>
<section id="danh-muc" class="e805-categories xd-landing-block" data-landing-block-id="{{ data_get($cats,'id') }}" data-block-type="e805_categories"><div class="e805-container">@foreach($items($cats)->take(10) as $item)<a href="{{ data_get($item,'url','#san-pham') }}"><span><i class="{{ data_get($item,'icon','fa-solid fa-cube') }}"></i></span><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></section>
<section class="e805-section xd-landing-block" data-landing-block-id="{{ data_get($sale,'id') }}" data-block-type="e805_sale_tabs"><div class="e805-container e805-sale"><div class="e805-sale-tabs" data-e805-tabs><button class="is-active"><b>ĐIỆN THOẠI</b><span>Giảm ngay 1 triệu khi mua online</span></button><button><b>THỜI TRANG</b><span>Giảm giá cực lớn lên tới 70%</span></button><button><b>GIA DỤNG</b><span>Giá siêu ưu đãi lên tới 30%</span></button></div><div class="e805-sale-body"><aside><img src="{{ asset('themes/E805/images/tech-sale.png') }}" alt="Deal sốc"><div><b>VOUCHER THẬT XỊN</b><span>Giá sốc mỗi ngày</span></div></aside><div class="e805-products">@foreach($items($sale)->take(5) as $item)@include('theme-e805::partials.product-card',['item'=>$item,'compact'=>false])@endforeach</div></div></div></section>
<section id="san-pham" class="e805-section xd-landing-block" data-landing-block-id="{{ data_get($tech,'id') }}" data-block-type="e805_technology"><div class="e805-container"><header class="e805-heading"><h2>ĐỒ CÔNG NGHỆ</h2><nav>@foreach(['Điện thoại - Máy tính bảng','Phụ kiện - Thiết bị số','Máy ảnh - Quay phim','Điện gia dụng - Nhà bếp','Laptop - Thiết bị IT'] as $x)<a href="#">{{ $x }}</a>@endforeach</nav></header><div class="e805-tech"><aside><article><img src="{{ asset('themes/E805/images/tech-sale.png') }}" alt="Laptop sale"><div><b>LAPTOP & GAMING</b><span>Ưu đãi đặc biệt</span></div></article><article><img src="{{ asset('themes/E805/images/hero-retail.png') }}" alt="Săn sale"><div><b>SĂN SALE CÔNG NGHỆ</b><span>Freeship nội thành</span></div></article></aside><div class="e805-products e805-grid4">@foreach($items($tech)->take(8) as $item)@include('theme-e805::partials.product-card',['item'=>$item,'compact'=>false])@endforeach</div></div></div></section>
<section id="goi-y" class="e805-section xd-landing-block" data-landing-block-id="{{ data_get($picks,'id') }}" data-block-type="e805_picks"><div class="e805-container e805-picks"><header class="e805-heading"><h2>GỢI Ý HÔM NAY</h2><span>‹ &nbsp; ›</span></header><div class="e805-products">@foreach($items($picks)->take(5) as $item)@include('theme-e805::partials.product-card',['item'=>$item,'compact'=>false])@endforeach</div><i class="e805-ribbon">GIÁ CỰC ƯU ĐÃI</i></div></section>
<section id="tin-tuc" class="e805-section xd-landing-block" data-landing-block-id="{{ data_get($news,'id') }}" data-block-type="e805_news"><div class="e805-container"><header class="e805-heading"><h2>TIN TỨC MỚI NHẤT</h2></header><div class="e805-news">@foreach($items($news)->take(4) as $i=>$item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ $img($item,asset('themes/E805/images/hero-retail.png')) }}" alt="{{ data_get($item,'title') }}"><span>{{ ['Tin tức','Đời sống','Khuyến mãi','Sự kiện'][$i]??'Tin tức' }}</span></a><h3>{{ data_get($item,'title') }}</h3><p>{{ \Illuminate\Support\Str::limit(strip_tags((string)data_get($item,'summary')),115) }}</p></article>@endforeach</div></div></section>
</main>
@endsection
