@php
$blocks=collect($landingBlocks??[]);$get=fn($type)=>$blocks->firstWhere('block_type',$type)??[];$items=function($b){$d=collect($b['dynamic_items']??[])->filter()->values();return $d->isNotEmpty()?$d:collect(data_get($b,'data.content.items',[]))->filter()->values();};$image=fn($x,$fallback)=>data_get($x,'image',data_get($x,'image_url',$fallback));$short=fn($x,$n=130)=>\Illuminate\Support\Str::limit(strip_tags((string)$x),$n);
$hero=$get('hero_slider');$about=$get('about_experience');$projects=$get('project_gallery');$services=$get('featured_services');$products=$get('featured_products');$why=$get('featured_categories');$testimonials=$get('testimonials');$team=$get('team_members');$faq=$get('faq_showcase');$process=$get('process_steps');$news=$get('latest_posts');$contact=$get('landing_contact');$partners=$get('partner_logos');
$slides=collect($hero['dynamic_items']??data_get($hero,'data.content.slides',[]));if($slides->isEmpty())$slides=collect([['title'=>'Kiến Tạo Tương Lai Cùng Bean Construction','summary'=>'Giải pháp xây dựng bền vững và hiện đại.','image'=>'/theme-demo/xd0325/hero-construction.png']]);$aboutImages=collect(data_get($about,'media.images',[]));$defaultBuilding='/theme-demo/xd0325/hero-construction.png';$defaultInterior='/theme-demo/curated/home/bathroom/bathroom-02.jpg';
@endphp
@extends('theme-xd0325::layout')
@section('title',data_get($landingPage??[],'meta_title','XD0325 Bean Construction'))
@section('content')
<main class="x325-main">
<section class="x325-hero xd-landing-block" data-block-type="hero_slider" data-x325-slider data-autoplay="{{ data_get($hero,'settings.autoplay_ms',6000) }}">@foreach($slides as $i=>$slide)<article class="x325-slide {{ $i===0?'is-active':'' }}" data-x325-slide><img src="{{ $image($slide,$defaultBuilding) }}" alt="{{ data_get($slide,'title') }}"><div class="x325-hero-content x325-container"><h1>Kiến Tạo Tương Lai<br>Cùng Bean <em>Construction</em></h1><p>{{ data_get($slide,'summary',data_get($hero,'data.description')) }}</p><a class="x325-btn" href="#gioi-thieu">Xem thêm <i class="fa-solid fa-play"></i></a></div></article>@endforeach<div class="x325-quick"><a href="{{ route('site.catalog.search') }}">⌕<br>Tìm nhanh</a><a href="tel:19006750">☎<br>Hotline</a><a href="#lien-he">Zalo<br>Chat</a></div></section>

<section id="gioi-thieu" class="x325-section x325-about xd-landing-block" data-block-type="about_experience"><div class="x325-container x325-about-grid"><div class="x325-mosaic">@foreach([0,1,2] as $i)<img src="{{ $aboutImages[$i]??[$defaultBuilding,$defaultInterior,$defaultBuilding][$i] }}" alt="Bean Construction">@endforeach</div><div class="x325-about-copy"><p class="x325-eyebrow">{{ data_get($about,'data.subtitle','Chúng tôi là ai?') }}</p><h2>{{ data_get($about,'data.title','Về Bean Construction') }}</h2><p>{{ data_get($about,'data.description','Chuyên thi công và phát triển công trình uy tín, cung cấp giải pháp xây dựng hiện đại, bền vững và tối ưu chi phí.') }}</p><div class="x325-checks">@foreach($items($about) as $item)<span>{{ data_get($item,'title',data_get($item,'summary')) }}</span>@endforeach</div><a class="x325-btn" href="#dich-vu">{{ data_get($about,'data.button_label','Xem chi tiết') }} <i class="fa-solid fa-arrow-right"></i></a></div></div></section>

<section id="du-an" class="x325-section xd-landing-block" data-block-type="project_gallery"><div class="x325-container"><header class="x325-heading"><p class="x325-eyebrow">{{ data_get($projects,'data.subtitle','Dự án của chúng tôi') }}</p><h2>{{ data_get($projects,'data.title','Các Dự Án Mới Nhất') }}</h2><p>{{ data_get($projects,'data.description') }}</p></header><div class="x325-track">@forelse($items($projects) as $item)<article class="x325-project"><img src="{{ $image($item,$defaultInterior) }}" alt="{{ data_get($item,'title') }}"><div class="x325-project-info"><h3>{{ data_get($item,'title') }}</h3><p>{{ $short(data_get($item,'summary'),150) }}</p><a href="{{ data_get($item,'url','#') }}">Xem chi tiết →</a></div></article>@empty @foreach(['Biệt thự Mùa Xuân','Nội thất văn phòng','Nhà phố hiện đại'] as $title)<article class="x325-project"><img src="{{ $defaultInterior }}" alt="{{ $title }}"><div class="x325-project-info"><h3>{{ $title }}</h3><p>Thiết kế và thi công trọn gói bởi Bean Construction.</p></div></article>@endforeach @endforelse</div></div></section>

<section id="dich-vu" class="x325-section xd-landing-block" data-block-type="featured_services"><div class="x325-container"><header class="x325-heading"><p class="x325-eyebrow">{{ data_get($services,'data.subtitle','Dịch vụ của chúng tôi') }}</p><h2>{{ data_get($services,'data.title','Chúng Tôi Cung Cấp Các Dịch Vụ') }}</h2><p>{{ data_get($services,'data.description') }}</p></header></div><div class="x325-services">@foreach($items($services) as $i=>$item)@if($i%2===0)<article class="x325-service"><img src="{{ $image($item,$i%4===0?$defaultBuilding:$defaultInterior) }}" alt="{{ data_get($item,'title') }}"></article>@endif<article class="x325-service"><i class="{{ data_get($item,'icon','fa-solid fa-building') }}"></i><h3>{{ data_get($item,'title') }}</h3><p>{{ $short(data_get($item,'summary'),150) }}</p><a href="{{ data_get($item,'url','#') }}">Xem chi tiết →</a></article>@endforeach</div></section>

<section id="san-pham" class="x325-section xd-landing-block" data-block-type="featured_products"><div class="x325-container"><header class="x325-heading" style="text-align:center"><p class="x325-eyebrow">Sản phẩm công trình</p><h2>{{ data_get($products,'data.title','✦ Sản Phẩm Nổi Bật ✦') }}</h2><p>{{ data_get($products,'data.description') }}</p></header><div class="x325-products">@foreach($items($products) as $item)<article class="x325-product"><span class="x325-discount">-15%</span><a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,'/theme-demo/xd0325/safety-products.png') }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title') }}</h3><b>{{ (float)data_get($item,'price')>0?number_format((float)data_get($item,'price'),0,',','.').'đ':'Liên hệ' }}</b>@if((float)data_get($item,'original_price')>0)<del>{{ number_format((float)data_get($item,'original_price'),0,',','.') }}đ</del>@endif</a></article>@endforeach</div></div></section>

<section class="x325-section x325-why xd-landing-block" data-block-type="featured_categories"><div class="x325-container x325-why-grid"><img class="x325-why-image" src="{{ data_get($why,'media.image',$defaultBuilding) }}" alt="Bean Construction"><div><p class="x325-eyebrow">{{ data_get($why,'data.subtitle','Tại sao chọn chúng tôi') }}</p><h2>{{ data_get($why,'data.title','Từ Ý Tưởng Đến Công Trình Hoàn Thiện') }}</h2><p>{{ data_get($why,'data.description') }}</p><div class="x325-reasons">@foreach($items($why) as $i=>$item)<article class="x325-reason"><h3><b>0{{ $i+1 }}</b>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></article>@endforeach</div></div></div></section>

<section class="x325-section x325-dark xd-landing-block" data-block-type="testimonials"><div class="x325-container x325-testimonial-grid"><img class="x325-testimonial-image" src="{{ $defaultBuilding }}" alt="Khách hàng Bean"><div><p class="x325-eyebrow">Phản hồi từ khách hàng</p><h2 style="font-size:54px">{{ data_get($testimonials,'data.title','Khách Hàng Nói Gì?') }}</h2>@foreach($items($testimonials)->take(1) as $item)<div class="x325-quote"><div class="stars">★★★★★</div><blockquote>“{{ data_get($item,'quote',data_get($item,'summary')) }}”</blockquote><h3>{{ data_get($item,'name',data_get($item,'title')) }}</h3><span>{{ data_get($item,'role') }}</span></div>@endforeach</div></div></section>

<section id="doi-ngu" class="x325-section xd-landing-block" data-block-type="team_members"><div class="x325-container"><header class="x325-heading"><p class="x325-eyebrow">Đội ngũ nhân viên</p><h2>{{ data_get($team,'data.title','Đội Ngũ Nhân Viên Chuyên Nghiệp') }}</h2><p>{{ data_get($team,'data.description') }}</p></header><div class="x325-team">@foreach($items($team) as $item)<article class="x325-member"><img src="{{ $image($item,$defaultBuilding) }}" alt="{{ data_get($item,'name',data_get($item,'title')) }}"><div><h3>{{ data_get($item,'name',data_get($item,'title')) }}</h3><p>{{ data_get($item,'role',data_get($item,'summary')) }}</p></div></article>@endforeach</div></div></section>

<section id="faq" class="x325-section xd-landing-block" data-block-type="faq_showcase"><div class="x325-container x325-faq-grid"><div class="x325-faq-images"><img src="{{ $defaultBuilding }}"><img src="{{ $defaultInterior }}"><img src="{{ $defaultBuilding }}"></div><div><p class="x325-eyebrow">Câu hỏi thường gặp</p><h2 style="font-size:54px">{{ data_get($faq,'data.title','Giải Đáp Thắc Mắc Cùng Bean Construction') }}</h2><p>{{ data_get($faq,'data.description') }}</p><div class="x325-faq-list">@foreach($items($faq) as $i=>$item)<article class="x325-faq-item {{ $i===0?'is-open':'' }}" data-x325-faq><button>{{ data_get($item,'title') }} <i class="fa-solid fa-arrow-up-right"></i></button><p>{{ data_get($item,'summary') }}</p></article>@endforeach</div></div></div></section>

<section class="x325-section x325-process xd-landing-block" data-block-type="process_steps"><div class="x325-container x325-process-grid">@foreach($items($process) as $i=>$item)<article class="x325-step"><b>0{{ $i+1 }}</b><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></article>@endforeach</div></section>

<section id="tin-tuc" class="x325-section xd-landing-block" data-block-type="latest_posts"><div class="x325-container"><header class="x325-heading"><p class="x325-eyebrow">Tin tức mới nhất</p><h2>{{ data_get($news,'data.title','Cập Nhật Những Tin Tức Xây Dựng') }}</h2><p>{{ data_get($news,'data.description') }}</p></header><div class="x325-news">@foreach($items($news) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,$defaultInterior) }}" alt="{{ data_get($item,'title') }}"><h3>{{ data_get($item,'title') }}</h3><p>{{ $short(data_get($item,'summary')) }}</p><b>Đọc tiếp ››</b></a></article>@endforeach</div></div></section>

<section id="lien-he" class="x325-section x325-dark xd-landing-block" data-block-type="landing_contact"><div class="x325-container x325-contact-wrap"><aside class="x325-contact-info"><i class="fa-solid fa-phone-volume" style="font-size:50px"></i><p>Gọi Trung tâm hỗ trợ 24/7</p><strong>1800 6750</strong><i class="fa-regular fa-envelope" style="font-size:50px;margin-top:35px"></i><p>Gửi mail cho chúng tôi</p><strong style="font-size:28px">support@sapo.vn</strong></aside><div class="x325-contact"><p class="x325-eyebrow">Tư vấn miễn phí</p><h2>{{ data_get($contact,'data.title','Liên Hệ Ngay Để Được Tư Vấn') }}</h2><p>{{ data_get($contact,'data.description') }}</p><form method="POST" action="{{ route('site.contact.submit') }}">@csrf<input type="hidden" name="source" value="xd0325-landing"><input name="name" required placeholder="Họ và tên"><input name="phone" required placeholder="Điện thoại"><input type="email" name="email" required placeholder="Email"><input name="address" placeholder="Địa chỉ"><textarea name="message" minlength="10" required placeholder="Nội dung"></textarea><button class="x325-btn">@themeT('XD0325.common.send','Gửi thông tin') <i class="fa-solid fa-arrow-right"></i></button></form></div></div></section>

<section class="x325-section xd-landing-block" data-block-type="partner_logos"><div class="x325-container x325-partners"><div><p class="x325-eyebrow">Đối tác chúng tôi</p><h2 style="font-size:52px">{{ data_get($partners,'data.title','Đối Tác Lâu Năm Của Chúng Tôi') }}</h2><p>{{ data_get($partners,'data.description') }}</p></div><div class="x325-partner-grid">@foreach($items($partners) as $item)<a href="{{ data_get($item,'url','#') }}">@if($image($item,''))<img src="{{ $image($item,'') }}" alt="{{ data_get($item,'title') }}">@else {{ data_get($item,'title') }} @endif</a>@endforeach</div></div></section>
</main>
@endsection
