import PlusOutlined from '@ant-design/icons/PlusOutlined';
import Alert from 'antd/es/alert';
import Button from 'antd/es/button';
import Card from 'antd/es/card';
import Col from 'antd/es/col';
import DatePicker from 'antd/es/date-picker';
import Descriptions from 'antd/es/descriptions';
import Drawer from 'antd/es/drawer';
import Form from 'antd/es/form';
import Input from 'antd/es/input';
import InputNumber from 'antd/es/input-number';
import Modal from 'antd/es/modal';
import Row from 'antd/es/row';
import Select from 'antd/es/select';
import Space from 'antd/es/space';
import Statistic from 'antd/es/statistic';
import Table from 'antd/es/table';
import Tag from 'antd/es/tag';
import Typography from 'antd/es/typography';
import dayjs from 'dayjs';
import { useCallback, useEffect, useMemo, useState } from 'react';

const { Title, Text } = Typography;
const labels = { draft:'Nháp',approved:'Đã duyệt',published:'Đã công bố',locked:'Đã khóa' };
const colors = { draft:'default',approved:'blue',published:'green',locked:'purple' };
const money = (value) => new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(value||0));

export default function PayrollManagerPage({ moduleMenu, callAdminApi, runAdminAction, currentPermissions=[] }) {
    const key=moduleMenu?.key??'payroll-dashboard'; const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [loadedEndpoint,setLoadedEndpoint]=useState(null); const [error,setError]=useState(''); const [drawer,setDrawer]=useState(null); const [form]=Form.useForm();
    const endpoint=useMemo(()=>key==='payroll-my-payslips'?'/admin/api/payroll/me/payslips':key==='payroll-periods'?'/admin/api/payroll/periods':'/admin/api/payroll/payslips',[key]);
    const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await callAdminApi(endpoint);setData(response.data);setLoadedEndpoint(endpoint);}catch(e){setData(null);setLoadedEndpoint(endpoint);setError(e.message||'Không thể tải dữ liệu bảng lương.');}finally{setLoading(false);}},[callAdminApi,endpoint]); useEffect(()=>{load();},[load]);
    const can=(p)=>currentPermissions.includes(p);
    const open=(type,record=null)=>{setDrawer({type,record});form.resetFields();if(record)form.setFieldsValue(type==='period'?{...record,start_date:record.start_date?dayjs(record.start_date):null,end_date:record.end_date?dayjs(record.end_date):null}:record);else if(type==='payslip')form.setFieldsValue({allowances:0,deductions:0});};
    const save=async()=>{const values=await form.validateFields();if(drawer.type==='period'){values.start_date=values.start_date?.format?values.start_date.format('YYYY-MM-DD'):values.start_date;values.end_date=values.end_date?.format?values.end_date.format('YYYY-MM-DD'):values.end_date;}const url=drawer.type==='period'?(drawer.record?`/admin/api/payroll/periods/${drawer.record.id}`:'/admin/api/payroll/periods'):'/admin/api/payroll/payslips';await runAdminAction(()=>callAdminApi(url,{method:drawer.record?'PUT':'POST',body:JSON.stringify(values)}),'Đã lưu dữ liệu bảng lương.',async()=>{setDrawer(null);await load();});};
    if(error&&loadedEndpoint===endpoint)return <Alert type="error" showIcon message={error} action={<Button onClick={load}>Thử lại</Button>}/>; if(loading||!data||loadedEndpoint!==endpoint)return <Card loading/>;
    if(key==='payroll-my-payslips') return <Space direction="vertical" size={16} style={{width:'100%'}}><Card><Text type="secondary">CỔNG THÔNG TIN CÁ NHÂN</Text><Title level={3} style={{margin:'4px 0'}}>Phiếu lương của tôi</Title><Text type="secondary">Chỉ hiển thị các kỳ lương đã được công bố.</Text></Card><Row gutter={[16,16]}>{(Array.isArray(data)?data:[]).map(item=><Col xs={24} lg={12} key={item.id}><Card title={item.period?.name} extra={<Tag color={colors[item.status]}>{labels[item.status]}</Tag>}><Descriptions column={1} items={[{key:'base',label:'Lương cơ bản',children:money(item.base_salary)},{key:'allow',label:'Phụ cấp',children:money(item.allowances)},{key:'deduct',label:'Khấu trừ',children:money(item.deductions)},{key:'net',label:'Thực nhận',children:<Text strong style={{color:'#07836f'}}>{money(item.net_salary)}</Text>}]} /></Card></Col>)}</Row></Space>;
    if(key==='payroll-periods') return <Space direction="vertical" size={16} style={{width:'100%'}}><Card><Row justify="space-between" align="middle"><Col><Text type="secondary">BẢNG LƯƠNG</Text><Title level={3} style={{margin:'4px 0'}}>Kỳ lương</Title><Text type="secondary">Kiểm soát quy trình duyệt, công bố và khóa dữ liệu lương.</Text></Col><Col>{can('payroll.period.manage')&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>open('period')}>Tạo kỳ lương</Button>}</Col></Row></Card><Card><Table rowKey="id" dataSource={data??[]} columns={[{title:'Mã kỳ',dataIndex:'code'},{title:'Tên kỳ lương',dataIndex:'name'},{title:'Thời gian',render:(_,r)=>`${r.start_date} – ${r.end_date}`},{title:'Phiếu lương',dataIndex:'payslips_count'},{title:'Trạng thái',render:(_,r)=><Tag color={colors[r.status]}>{labels[r.status]}</Tag>},{title:'Tác vụ',render:(_,r)=><Space>{can('payroll.period.manage')&&r.status==='draft'&&<Button size="small" onClick={()=>open('period',r)}>Sửa</Button>}{can('payroll.run.approve')&&r.status==='draft'&&<Button size="small" onClick={()=>runAdminAction(()=>callAdminApi(`/admin/api/payroll/periods/${r.id}/transition`,{method:'POST',body:JSON.stringify({action:'approve'})}),'Đã duyệt kỳ lương.',load)}>Duyệt</Button>}{can('payroll.run.publish')&&r.status==='approved'&&<Button size="small" type="primary" onClick={()=>runAdminAction(()=>callAdminApi(`/admin/api/payroll/periods/${r.id}/transition`,{method:'POST',body:JSON.stringify({action:'publish'})}),'Đã công bố kỳ lương.',load)}>Công bố</Button>}{can('payroll.run.lock')&&r.status==='published'&&<Button size="small" onClick={()=>runAdminAction(()=>callAdminApi(`/admin/api/payroll/periods/${r.id}/transition`,{method:'POST',body:JSON.stringify({action:'lock'})}),'Đã khóa kỳ lương.',load)}>Khóa</Button>}</Space>}]} /></Card><Modal title={drawer?.record?'Cập nhật kỳ lương':'Tạo kỳ lương'} open={drawer?.type==='period'} width={600} okText="Lưu kỳ lương" cancelText="Hủy" onOk={save} onCancel={()=>setDrawer(null)} destroyOnHidden><Form form={form} layout="vertical" style={{marginTop:20}}><Form.Item name="name" label="Tên kỳ lương" rules={[{required:true}]}><Input placeholder="Ví dụ: Lương tháng 07/2026"/></Form.Item><Row gutter={16}><Col xs={24} md={12}><Form.Item name="start_date" label="Từ ngày" rules={[{required:true}]}><DatePicker format="DD/MM/YYYY" placeholder="Chọn ngày bắt đầu" style={{width:'100%'}}/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="end_date" label="Đến ngày" rules={[{required:true}]}><DatePicker format="DD/MM/YYYY" placeholder="Chọn ngày kết thúc" style={{width:'100%'}}/></Form.Item></Col></Row></Form></Modal></Space>;
    const payload=data&&!Array.isArray(data)?data:{}; const items=Array.isArray(payload.items)?payload.items:[];
    return <Space direction="vertical" size={16} style={{width:'100%'}}><Card><Row justify="space-between" align="middle"><Col><Text type="secondary">BẢNG LƯƠNG</Text><Title level={3} style={{margin:'4px 0'}}>Phiếu lương</Title><Text type="secondary">Dữ liệu lương được bảo vệ và chỉ công bố sau khi duyệt.</Text></Col><Col>{can('payroll.run.calculate')&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>open('payslip')}>Nhập phiếu lương</Button>}</Col></Row></Card><Row gutter={[16,16]}><Col xs={24} md={8}><Card><Statistic title="Số phiếu" value={items.length}/></Card></Col><Col xs={24} md={8}><Card><Statistic title="Tổng thực nhận" value={items.reduce((sum,x)=>sum+Number(x.net_salary||0),0)} formatter={money}/></Card></Col></Row><Card><Table rowKey="id" dataSource={items} columns={[{title:'Nhân sự',render:(_,r)=>r.employee?.full_name},{title:'Kỳ lương',render:(_,r)=>r.period?.name},{title:'Lương cơ bản',render:(_,r)=>money(r.base_salary)},{title:'Phụ cấp',render:(_,r)=>money(r.allowances)},{title:'Khấu trừ',render:(_,r)=>money(r.deductions)},{title:'Thực nhận',render:(_,r)=><Text strong>{money(r.net_salary)}</Text>},{title:'Trạng thái',render:(_,r)=><Tag color={colors[r.status]}>{labels[r.status]}</Tag>}]} /></Card><Drawer title="Nhập phiếu lương" open={drawer?.type==='payslip'} width="min(620px,92vw)" onClose={()=>setDrawer(null)} extra={<Button type="primary" onClick={save}>Lưu</Button>}><Form form={form} layout="vertical"><Form.Item name="payroll_period_id" label="Kỳ lương" rules={[{required:true}]}><Select options={(payload.periods??[]).filter(x=>x.status==='draft').map(x=>({value:x.id,label:x.name}))}/></Form.Item><Form.Item name="employee_id" label="Nhân sự" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(payload.employees??[]).map(x=>({value:x.id,label:`${x.employee_code} · ${x.full_name}`}))}/></Form.Item><Form.Item name="base_salary" label="Lương cơ bản" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="allowances" label="Tổng phụ cấp" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="deductions" label="Tổng khấu trừ" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="note" label="Ghi chú"><Input.TextArea rows={4}/></Form.Item></Form></Drawer></Space>;
}
