@extends('theme-shop602::layout')
@section('title',data_get($landingPage??[],'meta_title',data_get($siteProfile??[],'site_name','SHOP602')))
@section('content')
@php
$blocks=collect($landingBlocks??[])->values();$canEditLanding=auth('admin')->check()&&request('mod')==='admin'&&is_array($landingPage??null);$editorLocales=collect(\App\Support\FrontendLocalization::supportedLocales())->map(fn($locale)=>['code'=>$locale,'label'=>strtoupper($locale)])->all();$get=fn(string $type):array=>(array)($blocks->firstWhere('block_type',$type)??[]);$items=fn(array $block)=>collect($block['dynamic_items']??[])->filter()->values()->whenEmpty(fn($list)=>$list->push(...collect(data_get($block,'data.content.items',[]))->filter()->values()->all()));$image=fn($item,string $fallback)=>data_get($item,'image',data_get($item,'image_url',$fallback));$money=fn($value)=>(float)$value>0?number_format((float)$value,0,',','.').'đ':'Liên hệ';$hero=$get('hero_slider');$quality=$get('shop602_quality_slider');$flash=$get('shop602_flash_sale');$ads=$get('shop602_dual_ads');$new=$get('shop602_new_arrivals');$explore=$get('shop602_product_explorer');$accessories=$get('shop602_accessories');$single=$get('shop602_single_ad');$news=$get('shop602_latest_news');$contact=$get('shop602_contact_form');$slides=collect($hero['dynamic_items']??[])->filter()->values();if($slides->isEmpty())$slides=collect(data_get($hero,'data.content.slides',[]))->filter()->values();
@endphp
<main class="s602-main">
<section class="s602-hero xd-landing-block" data-landing-block-id="{{ data_get($hero,'id') }}" data-block-type="hero_slider" data-s602-slider data-autoplay="{{ data_get($hero,'settings.autoplay_ms',5600) }}">@foreach($slides as $index=>$slide)<article class="s602-hero-slide {{ $index===0?'is-active':'' }}" data-s602-slide><img src="{{ $image($slide,'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=2200&q=90') }}" alt="{{ data_get($slide,'title') }}"><div class="s602-container s602-hero-copy"><p>{{ data_get($slide,'kicker',data_get($hero,'data.subtitle')) }}</p><h1>{!! data_get($slide,'title',data_get($hero,'data.title')) !!}</h1><span>{{ data_get($slide,'summary',data_get($hero,'data.description')) }}</span><a href="{{ data_get($slide,'link_url','#san-pham-moi') }}">{{ data_get($slide,'button_label',data_get($hero,'data.button_label')) }} <i class="fa-solid fa-arrow-right"></i></a></div></article>@endforeach<button data-s602-prev aria-label="Trước"><i class="fa-solid fa-chevron-left"></i></button><button data-s602-next aria-label="Sau"><i class="fa-solid fa-chevron-right"></i></button></section>

<section id="{{ data_get($quality,'anchor_id','cam-ket') }}" class="s602-quality xd-landing-block" data-landing-block-id="{{ data_get($quality,'id') }}" data-block-type="shop602_quality_slider" data-s602-strip data-autoplay="{{ data_get($quality,'settings.autoplay_ms',3600) }}"><div class="s602-container"><div class="s602-quality-track" data-s602-strip-track>@foreach($items($quality) as $item)<article><img src="{{ $image($item,'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=240&q=80') }}" alt=""><div><h3>{{ data_get($item,'title') }}</h3><p>{{ data_get($item,'summary') }}</p></div></article>@endforeach</div></div></section>

<section id="{{ data_get($flash,'anchor_id','flash-sale') }}" class="s602-section xd-landing-block" data-landing-block-id="{{ data_get($flash,'id') }}" data-block-type="shop602_flash_sale"><div class="s602-container s602-flash"><header><div><p>{{ data_get($flash,'data.subtitle') }}</p><h2>{{ data_get($flash,'data.title') }}</h2><span>{{ data_get($flash,'data.description') }}</span></div><div class="s602-count"><b>KẾT THÚC SAU</b><time data-s602-countdown="{{ data_get($flash,'settings.ends_at') }}">00 : 00 : 00 : 00</time></div></header><div class="s602-product-grid">@foreach($items($flash) as $item)@include('theme-shop602::partials.product-card',['item'=>$item])@endforeach</div></div></section>

<section id="{{ data_get($ads,'anchor_id','uu-dai') }}" class="s602-section xd-landing-block" data-landing-block-id="{{ data_get($ads,'id') }}" data-block-type="shop602_dual_ads"><div class="s602-container s602-dual-ads">@foreach($items($ads) as $item)<a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1400&q=85') }}" alt="{{ data_get($item,'title') }}"><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></section>

<section id="{{ data_get($new,'anchor_id','san-pham-moi') }}" class="s602-section xd-landing-block" data-landing-block-id="{{ data_get($new,'id') }}" data-block-type="shop602_new_arrivals"><div class="s602-container"><div class="s602-editorial"><div><p>{{ data_get($new,'data.subtitle') }}</p><h2>{{ data_get($new,'data.title') }}</h2><span>{{ data_get($new,'data.description') }}</span><a href="{{ route('site.catalog.search') }}">{{ data_get($new,'data.button_label') }} <i class="fa-solid fa-arrow-right"></i></a></div><img src="{{ data_get($new,'settings.feature_image','https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1600&q=85') }}" alt=""></div><div class="s602-product-grid">@foreach($items($new) as $item)@include('theme-shop602::partials.product-card',['item'=>$item])@endforeach</div></div></section>

<section id="{{ data_get($explore,'anchor_id','kham-pha') }}" class="s602-section xd-landing-block" data-landing-block-id="{{ data_get($explore,'id') }}" data-block-type="shop602_product_explorer"><div class="s602-container"><header class="s602-heading"><p>{{ data_get($explore,'data.subtitle') }}</p><h2>{{ data_get($explore,'data.title') }}</h2><span>{{ data_get($explore,'data.description') }}</span></header><div class="s602-explorer">@foreach($items($explore) as $item)<a href="{{ data_get($item,'url','#') }}"><div><small>{{ data_get($item,'summary','WOLF YOGA') }}</small><h3>{{ data_get($item,'title') }}</h3><span>XEM THÊM <i class="fa-solid fa-arrow-right"></i></span></div><img src="{{ $image($item,'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=700&q=85') }}" alt="{{ data_get($item,'title') }}"></a>@endforeach</div></div></section>

<section id="{{ data_get($accessories,'anchor_id','phu-kien') }}" class="s602-section xd-landing-block" data-landing-block-id="{{ data_get($accessories,'id') }}" data-block-type="shop602_accessories"><div class="s602-container"><div class="s602-editorial s602-editorial-reverse"><img src="{{ data_get($accessories,'settings.feature_image','https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=1600&q=85') }}" alt=""><div><p>{{ data_get($accessories,'data.subtitle') }}</p><h2>{{ data_get($accessories,'data.title') }}</h2><span>{{ data_get($accessories,'data.description') }}</span><a href="{{ route('site.catalog.search') }}">{{ data_get($accessories,'data.button_label') }} <i class="fa-solid fa-arrow-right"></i></a></div></div><div class="s602-product-grid">@foreach($items($accessories) as $item)@include('theme-shop602::partials.product-card',['item'=>$item])@endforeach</div></div></section>

<section id="{{ data_get($single,'anchor_id','banner-bo-suu-tap') }}" class="s602-section xd-landing-block" data-landing-block-id="{{ data_get($single,'id') }}" data-block-type="shop602_single_ad"><div class="s602-container">@foreach($items($single)->take(1) as $item)<a class="s602-single-ad" href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=2200&q=88') }}" alt="{{ data_get($item,'title') }}"><b>{{ data_get($item,'title') }}</b></a>@endforeach</div></section>

<section id="{{ data_get($news,'anchor_id','tin-tuc') }}" class="s602-section xd-landing-block" data-landing-block-id="{{ data_get($news,'id') }}" data-block-type="shop602_latest_news"><div class="s602-container"><header class="s602-heading"><p>{{ data_get($news,'data.subtitle') }}</p><h2>{{ data_get($news,'data.title') }}</h2><span>{{ data_get($news,'data.description') }}</span></header><div class="s602-news">@foreach($items($news) as $item)<article><a href="{{ data_get($item,'url','#') }}"><img src="{{ $image($item,'https://images.unsplash.com/photo-1545389336-cf090694435e?auto=format&fit=crop&w=900&q=85') }}" alt="{{ data_get($item,'title') }}"></a><time><i class="fa-regular fa-calendar"></i> {{ data_get($item,'published_at',now()->format('d/m/Y')) }}</time><h3><a href="{{ data_get($item,'url','#') }}">{{ data_get($item,'title') }}</a></h3><p>{{ \Illuminate\Support\Str::limit(strip_tags((string)data_get($item,'summary')),110) }}</p><a href="{{ data_get($item,'url','#') }}">Đọc tiếp <i class="fa-solid fa-arrow-right"></i></a></article>@endforeach</div><a class="s602-button" href="{{ route('site.blog.index') }}">{{ data_get($news,'data.button_label') }} <i class="fa-solid fa-arrow-right"></i></a></div></section>

<section id="{{ data_get($contact,'anchor_id','lien-he') }}" class="s602-contact xd-landing-block" data-landing-block-id="{{ data_get($contact,'id') }}" data-block-type="shop602_contact_form"><div class="s602-container s602-contact-grid"><div><p>{{ data_get($contact,'data.subtitle') }}</p><h2>{{ data_get($contact,'data.title') }}</h2><span>{{ data_get($contact,'data.description') }}</span></div><form method="POST" action="{{ route('site.contact.submit') }}">@csrf<input type="hidden" name="source" value="contact"><label>Họ và tên<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Số điện thoại<input name="phone"></label><label class="wide">Nội dung<textarea name="message" required minlength="10"></textarea></label><button class="wide">{{ data_get($contact,'data.button_label') }} <i class="fa-solid fa-arrow-right"></i></button></form></div></section>
</main>
@endsection
